// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: searchindexer.proto

package server

import (
	"context"

	"go-video/services/search-indexer/internal/logic"
	"go-video/services/search-indexer/internal/svc"
	"go-video/services/search-indexer/rpc"
)

type SearchIndexerServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedSearchIndexerServer
}

func NewSearchIndexerServer(svcCtx *svc.ServiceContext) *SearchIndexerServer {
	return &SearchIndexerServer{
		svcCtx: svcCtx,
	}
}

// 按 content_id 写入/覆盖一条内容投影（上游显式触发或回填）。
func (s *SearchIndexerServer) UpsertContentDoc(ctx context.Context, in *rpc.UpsertContentDocReq) (*rpc.UpsertContentDocReply, error) {
	l := logic.NewUpsertContentDocLogic(ctx, s.svcCtx)
	return l.UpsertContentDoc(in)
}

// 下架/删除时移除或降级投影，并说明 CDN/搜索投影一致性处理。
func (s *SearchIndexerServer) DeleteContentDoc(ctx context.Context, in *rpc.DeleteContentDocReq) (*rpc.DeleteContentDocReply, error) {
	l := logic.NewDeleteContentDocLogic(ctx, s.svcCtx)
	return l.DeleteContentDoc(in)
}

// 提交全量/分区重建任务（request_id 幂等），返回 task_id 与预分配目标索引。
func (s *SearchIndexerServer) SubmitRebuildTask(ctx context.Context, in *rpc.SubmitRebuildTaskReq) (*rpc.SubmitRebuildTaskReply, error) {
	l := logic.NewSubmitRebuildTaskLogic(ctx, s.svcCtx)
	return l.SubmitRebuildTask(in)
}

// 查询单个重建任务进度。
func (s *SearchIndexerServer) GetRebuildTask(ctx context.Context, in *rpc.GetRebuildTaskReq) (*rpc.RebuildTask, error) {
	l := logic.NewGetRebuildTaskLogic(ctx, s.svcCtx)
	return l.GetRebuildTask(in)
}

// 分页查询重建任务（cursor + 状态过滤）。
func (s *SearchIndexerServer) ListRebuildTasks(ctx context.Context, in *rpc.ListRebuildTasksReq) (*rpc.ListRebuildTasksReply, error) {
	l := logic.NewListRebuildTasksLogic(ctx, s.svcCtx)
	return l.ListRebuildTasks(in)
}

// 把查询别名从旧索引切到新版本索引（expected_current 乐观校验，失败返回明确错误）。
func (s *SearchIndexerServer) SwitchAlias(ctx context.Context, in *rpc.SwitchAliasReq) (*rpc.SwitchAliasReply, error) {
	l := logic.NewSwitchAliasLogic(ctx, s.svcCtx)
	return l.SwitchAlias(in)
}

// 返回各别名/索引的 doc 数与健康状态，以及重试/死信积压。
func (s *SearchIndexerServer) GetIndexHealth(ctx context.Context, in *rpc.GetIndexHealthReq) (*rpc.GetIndexHealthReply, error) {
	l := logic.NewGetIndexHealthLogic(ctx, s.svcCtx)
	return l.GetIndexHealth(in)
}
