// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.9
// source: tradeorder.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeOrder_CreateOrder_FullMethodName     = "/tradeorder.v1.TradeOrder/CreateOrder"
	TradeOrder_GetOrder_FullMethodName        = "/tradeorder.v1.TradeOrder/GetOrder"
	TradeOrder_ListMyOrders_FullMethodName    = "/tradeorder.v1.TradeOrder/ListMyOrders"
	TradeOrder_ListOrders_FullMethodName      = "/tradeorder.v1.TradeOrder/ListOrders"
	TradeOrder_ListOrderEvents_FullMethodName = "/tradeorder.v1.TradeOrder/ListOrderEvents"
	TradeOrder_CancelOrder_FullMethodName     = "/tradeorder.v1.TradeOrder/CancelOrder"
	TradeOrder_BindPayment_FullMethodName     = "/tradeorder.v1.TradeOrder/BindPayment"
	TradeOrder_FulfillOrder_FullMethodName    = "/tradeorder.v1.TradeOrder/FulfillOrder"
	TradeOrder_ListStuckOrders_FullMethodName = "/tradeorder.v1.TradeOrder/ListStuckOrders"
	TradeOrder_RequestRefund_FullMethodName   = "/tradeorder.v1.TradeOrder/RequestRefund"
	TradeOrder_ApproveRefund_FullMethodName   = "/tradeorder.v1.TradeOrder/ApproveRefund"
	TradeOrder_RejectRefund_FullMethodName    = "/tradeorder.v1.TradeOrder/RejectRefund"
)

// TradeOrderClient is the client API for TradeOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TradeOrder 商业订单服务。
type TradeOrderClient interface {
	// 下单（服务端重算金额，沙箱下内联受理）
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderReply, error)
	// 订单详情（带归属校验）
	GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderReply, error)
	// 我的订单
	ListMyOrders(ctx context.Context, in *ListMyOrdersReq, opts ...grpc.CallOption) (*ListMyOrdersReply, error)
	// 运营面订单查询（有界窗口）
	ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersReply, error)
	// 订单状态流转台账
	ListOrderEvents(ctx context.Context, in *ListOrderEventsReq, opts ...grpc.CallOption) (*ListOrderEventsReply, error)
	// 取消未支付订单
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderReply, error)
	// 绑定支付结论（补偿推进）
	BindPayment(ctx context.Context, in *BindPaymentReq, opts ...grpc.CallOption) (*BindPaymentReply, error)
	// 执行/重试履约
	FulfillOrder(ctx context.Context, in *FulfillOrderReq, opts ...grpc.CallOption) (*FulfillOrderReply, error)
	// cron：卡单扫描
	ListStuckOrders(ctx context.Context, in *ListStuckOrdersReq, opts ...grpc.CallOption) (*ListStuckOrdersReply, error)
	// 申请退款
	RequestRefund(ctx context.Context, in *RequestRefundReq, opts ...grpc.CallOption) (*RequestRefundReply, error)
	// 审批通过并回收权益
	ApproveRefund(ctx context.Context, in *ApproveRefundReq, opts ...grpc.CallOption) (*ApproveRefundReply, error)
	// 驳回退款
	RejectRefund(ctx context.Context, in *RejectRefundReq, opts ...grpc.CallOption) (*RejectRefundReply, error)
}

type tradeOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeOrderClient(cc grpc.ClientConnInterface) TradeOrderClient {
	return &tradeOrderClient{cc}
}

func (c *tradeOrderClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderReply)
	err := c.cc.Invoke(ctx, TradeOrder_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderReply)
	err := c.cc.Invoke(ctx, TradeOrder_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) ListMyOrders(ctx context.Context, in *ListMyOrdersReq, opts ...grpc.CallOption) (*ListMyOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyOrdersReply)
	err := c.cc.Invoke(ctx, TradeOrder_ListMyOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersReply)
	err := c.cc.Invoke(ctx, TradeOrder_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) ListOrderEvents(ctx context.Context, in *ListOrderEventsReq, opts ...grpc.CallOption) (*ListOrderEventsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrderEventsReply)
	err := c.cc.Invoke(ctx, TradeOrder_ListOrderEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderReply)
	err := c.cc.Invoke(ctx, TradeOrder_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) BindPayment(ctx context.Context, in *BindPaymentReq, opts ...grpc.CallOption) (*BindPaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindPaymentReply)
	err := c.cc.Invoke(ctx, TradeOrder_BindPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) FulfillOrder(ctx context.Context, in *FulfillOrderReq, opts ...grpc.CallOption) (*FulfillOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FulfillOrderReply)
	err := c.cc.Invoke(ctx, TradeOrder_FulfillOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) ListStuckOrders(ctx context.Context, in *ListStuckOrdersReq, opts ...grpc.CallOption) (*ListStuckOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStuckOrdersReply)
	err := c.cc.Invoke(ctx, TradeOrder_ListStuckOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) RequestRefund(ctx context.Context, in *RequestRefundReq, opts ...grpc.CallOption) (*RequestRefundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestRefundReply)
	err := c.cc.Invoke(ctx, TradeOrder_RequestRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) ApproveRefund(ctx context.Context, in *ApproveRefundReq, opts ...grpc.CallOption) (*ApproveRefundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveRefundReply)
	err := c.cc.Invoke(ctx, TradeOrder_ApproveRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeOrderClient) RejectRefund(ctx context.Context, in *RejectRefundReq, opts ...grpc.CallOption) (*RejectRefundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectRefundReply)
	err := c.cc.Invoke(ctx, TradeOrder_RejectRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeOrderServer is the server API for TradeOrder service.
// All implementations must embed UnimplementedTradeOrderServer
// for forward compatibility.
//
// TradeOrder 商业订单服务。
type TradeOrderServer interface {
	// 下单（服务端重算金额，沙箱下内联受理）
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderReply, error)
	// 订单详情（带归属校验）
	GetOrder(context.Context, *GetOrderReq) (*GetOrderReply, error)
	// 我的订单
	ListMyOrders(context.Context, *ListMyOrdersReq) (*ListMyOrdersReply, error)
	// 运营面订单查询（有界窗口）
	ListOrders(context.Context, *ListOrdersReq) (*ListOrdersReply, error)
	// 订单状态流转台账
	ListOrderEvents(context.Context, *ListOrderEventsReq) (*ListOrderEventsReply, error)
	// 取消未支付订单
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderReply, error)
	// 绑定支付结论（补偿推进）
	BindPayment(context.Context, *BindPaymentReq) (*BindPaymentReply, error)
	// 执行/重试履约
	FulfillOrder(context.Context, *FulfillOrderReq) (*FulfillOrderReply, error)
	// cron：卡单扫描
	ListStuckOrders(context.Context, *ListStuckOrdersReq) (*ListStuckOrdersReply, error)
	// 申请退款
	RequestRefund(context.Context, *RequestRefundReq) (*RequestRefundReply, error)
	// 审批通过并回收权益
	ApproveRefund(context.Context, *ApproveRefundReq) (*ApproveRefundReply, error)
	// 驳回退款
	RejectRefund(context.Context, *RejectRefundReq) (*RejectRefundReply, error)
	mustEmbedUnimplementedTradeOrderServer()
}

// UnimplementedTradeOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeOrderServer struct{}

func (UnimplementedTradeOrderServer) CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedTradeOrderServer) GetOrder(context.Context, *GetOrderReq) (*GetOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedTradeOrderServer) ListMyOrders(context.Context, *ListMyOrdersReq) (*ListMyOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyOrders not implemented")
}
func (UnimplementedTradeOrderServer) ListOrders(context.Context, *ListOrdersReq) (*ListOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedTradeOrderServer) ListOrderEvents(context.Context, *ListOrderEventsReq) (*ListOrderEventsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrderEvents not implemented")
}
func (UnimplementedTradeOrderServer) CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedTradeOrderServer) BindPayment(context.Context, *BindPaymentReq) (*BindPaymentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindPayment not implemented")
}
func (UnimplementedTradeOrderServer) FulfillOrder(context.Context, *FulfillOrderReq) (*FulfillOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FulfillOrder not implemented")
}
func (UnimplementedTradeOrderServer) ListStuckOrders(context.Context, *ListStuckOrdersReq) (*ListStuckOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStuckOrders not implemented")
}
func (UnimplementedTradeOrderServer) RequestRefund(context.Context, *RequestRefundReq) (*RequestRefundReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRefund not implemented")
}
func (UnimplementedTradeOrderServer) ApproveRefund(context.Context, *ApproveRefundReq) (*ApproveRefundReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveRefund not implemented")
}
func (UnimplementedTradeOrderServer) RejectRefund(context.Context, *RejectRefundReq) (*RejectRefundReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectRefund not implemented")
}
func (UnimplementedTradeOrderServer) mustEmbedUnimplementedTradeOrderServer() {}
func (UnimplementedTradeOrderServer) testEmbeddedByValue()                    {}

// UnsafeTradeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeOrderServer will
// result in compilation errors.
type UnsafeTradeOrderServer interface {
	mustEmbedUnimplementedTradeOrderServer()
}

func RegisterTradeOrderServer(s grpc.ServiceRegistrar, srv TradeOrderServer) {
	// If the following call pancis, it indicates UnimplementedTradeOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeOrder_ServiceDesc, srv)
}

func _TradeOrder_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).GetOrder(ctx, req.(*GetOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_ListMyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).ListMyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_ListMyOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).ListMyOrders(ctx, req.(*ListMyOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).ListOrders(ctx, req.(*ListOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_ListOrderEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).ListOrderEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_ListOrderEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).ListOrderEvents(ctx, req.(*ListOrderEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_BindPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).BindPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_BindPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).BindPayment(ctx, req.(*BindPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_FulfillOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FulfillOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).FulfillOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_FulfillOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).FulfillOrder(ctx, req.(*FulfillOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_ListStuckOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStuckOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).ListStuckOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_ListStuckOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).ListStuckOrders(ctx, req.(*ListStuckOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_RequestRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).RequestRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_RequestRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).RequestRefund(ctx, req.(*RequestRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_ApproveRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).ApproveRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_ApproveRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).ApproveRefund(ctx, req.(*ApproveRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeOrder_RejectRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeOrderServer).RejectRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeOrder_RejectRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeOrderServer).RejectRefund(ctx, req.(*RejectRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeOrder_ServiceDesc is the grpc.ServiceDesc for TradeOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradeorder.v1.TradeOrder",
	HandlerType: (*TradeOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _TradeOrder_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _TradeOrder_GetOrder_Handler,
		},
		{
			MethodName: "ListMyOrders",
			Handler:    _TradeOrder_ListMyOrders_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _TradeOrder_ListOrders_Handler,
		},
		{
			MethodName: "ListOrderEvents",
			Handler:    _TradeOrder_ListOrderEvents_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _TradeOrder_CancelOrder_Handler,
		},
		{
			MethodName: "BindPayment",
			Handler:    _TradeOrder_BindPayment_Handler,
		},
		{
			MethodName: "FulfillOrder",
			Handler:    _TradeOrder_FulfillOrder_Handler,
		},
		{
			MethodName: "ListStuckOrders",
			Handler:    _TradeOrder_ListStuckOrders_Handler,
		},
		{
			MethodName: "RequestRefund",
			Handler:    _TradeOrder_RequestRefund_Handler,
		},
		{
			MethodName: "ApproveRefund",
			Handler:    _TradeOrder_ApproveRefund_Handler,
		},
		{
			MethodName: "RejectRefund",
			Handler:    _TradeOrder_RejectRefund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tradeorder.proto",
}
