// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.9
// source: services/membership/rpc/membership.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Membership_ListPlans_FullMethodName               = "/membership.v1.Membership/ListPlans"
	Membership_GetPlan_FullMethodName                 = "/membership.v1.Membership/GetPlan"
	Membership_UpsertPlan_FullMethodName              = "/membership.v1.Membership/UpsertPlan"
	Membership_SetPlanState_FullMethodName            = "/membership.v1.Membership/SetPlanState"
	Membership_ListPlansAdmin_FullMethodName          = "/membership.v1.Membership/ListPlansAdmin"
	Membership_GetMembership_FullMethodName           = "/membership.v1.Membership/GetMembership"
	Membership_CheckEntitlement_FullMethodName        = "/membership.v1.Membership/CheckEntitlement"
	Membership_CheckEntitlements_FullMethodName       = "/membership.v1.Membership/CheckEntitlements"
	Membership_GrantMembership_FullMethodName         = "/membership.v1.Membership/GrantMembership"
	Membership_RevokeMembership_FullMethodName        = "/membership.v1.Membership/RevokeMembership"
	Membership_SetAutoRenew_FullMethodName            = "/membership.v1.Membership/SetAutoRenew"
	Membership_ListGrants_FullMethodName              = "/membership.v1.Membership/ListGrants"
	Membership_ListExpiringMemberships_FullMethodName = "/membership.v1.Membership/ListExpiringMemberships"
	Membership_ExpireMembership_FullMethodName        = "/membership.v1.Membership/ExpireMembership"
	Membership_ListEntitlements_FullMethodName        = "/membership.v1.Membership/ListEntitlements"
	Membership_UpsertEntitlement_FullMethodName       = "/membership.v1.Membership/UpsertEntitlement"
)

// MembershipClient is the client API for Membership service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Membership 会员身份、套餐与权益判定服务。
type MembershipClient interface {
	// 终端套餐列表（只含在售且平台可见）
	ListPlans(ctx context.Context, in *ListPlansReq, opts ...grpc.CallOption) (*ListPlansReply, error)
	// 单个套餐读取（下单前置校验用）
	GetPlan(ctx context.Context, in *GetPlanReq, opts ...grpc.CallOption) (*GetPlanReply, error)
	// 运营面：新建或修改套餐草稿
	UpsertPlan(ctx context.Context, in *UpsertPlanReq, opts ...grpc.CallOption) (*PlanInfo, error)
	// 运营面：上下架（带理由，写变更台账）
	SetPlanState(ctx context.Context, in *SetPlanStateReq, opts ...grpc.CallOption) (*PlanInfo, error)
	// 运营面：分页查询全部套餐（含草稿与已下架）
	ListPlansAdmin(ctx context.Context, in *ListPlansAdminReq, opts ...grpc.CallOption) (*ListPlansAdminReply, error)
	// 我的会员状态
	GetMembership(ctx context.Context, in *GetMembershipReq, opts ...grpc.CallOption) (*GetMembershipReply, error)
	// 单项权益判定——全站唯一的会员权益口径出口
	CheckEntitlement(ctx context.Context, in *CheckEntitlementReq, opts ...grpc.CallOption) (*CheckEntitlementReply, error)
	// 多项权益判定（播放详情页等一次问多项）
	CheckEntitlements(ctx context.Context, in *CheckEntitlementsReq, opts ...grpc.CallOption) (*CheckEntitlementsReply, error)
	// 开通/续期（只由订单履约或运营授权调用）
	GrantMembership(ctx context.Context, in *GrantMembershipReq, opts ...grpc.CallOption) (*GrantMembershipReply, error)
	// 收回（退款回收/运营纠错）
	RevokeMembership(ctx context.Context, in *RevokeMembershipReq, opts ...grpc.CallOption) (*RevokeMembershipReply, error)
	// 自动续费签约位翻转（沙箱，不建真实代扣协议）
	SetAutoRenew(ctx context.Context, in *SetAutoRenewReq, opts ...grpc.CallOption) (*SetAutoRenewReply, error)
	// 授予台账分页（运营面与用户面共用，mid=0 才有跨用户语义）
	ListGrants(ctx context.Context, in *ListGrantsReq, opts ...grpc.CallOption) (*ListGrantsReply, error)
	// cron：扫描到期区间
	ListExpiringMemberships(ctx context.Context, in *ListExpiringMembershipsReq, opts ...grpc.CallOption) (*ListExpiringMembershipsReply, error)
	// cron：幂等置过期
	ExpireMembership(ctx context.Context, in *ExpireMembershipReq, opts ...grpc.CallOption) (*ExpireMembershipReply, error)
	// 权益码目录读取
	ListEntitlements(ctx context.Context, in *ListEntitlementsReq, opts ...grpc.CallOption) (*ListEntitlementsReply, error)
	// 运营面：权益码新增/开关
	UpsertEntitlement(ctx context.Context, in *UpsertEntitlementReq, opts ...grpc.CallOption) (*EntitlementInfo, error)
}

type membershipClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipClient(cc grpc.ClientConnInterface) MembershipClient {
	return &membershipClient{cc}
}

func (c *membershipClient) ListPlans(ctx context.Context, in *ListPlansReq, opts ...grpc.CallOption) (*ListPlansReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlansReply)
	err := c.cc.Invoke(ctx, Membership_ListPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) GetPlan(ctx context.Context, in *GetPlanReq, opts ...grpc.CallOption) (*GetPlanReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanReply)
	err := c.cc.Invoke(ctx, Membership_GetPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) UpsertPlan(ctx context.Context, in *UpsertPlanReq, opts ...grpc.CallOption) (*PlanInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanInfo)
	err := c.cc.Invoke(ctx, Membership_UpsertPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) SetPlanState(ctx context.Context, in *SetPlanStateReq, opts ...grpc.CallOption) (*PlanInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanInfo)
	err := c.cc.Invoke(ctx, Membership_SetPlanState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) ListPlansAdmin(ctx context.Context, in *ListPlansAdminReq, opts ...grpc.CallOption) (*ListPlansAdminReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlansAdminReply)
	err := c.cc.Invoke(ctx, Membership_ListPlansAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) GetMembership(ctx context.Context, in *GetMembershipReq, opts ...grpc.CallOption) (*GetMembershipReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembershipReply)
	err := c.cc.Invoke(ctx, Membership_GetMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) CheckEntitlement(ctx context.Context, in *CheckEntitlementReq, opts ...grpc.CallOption) (*CheckEntitlementReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEntitlementReply)
	err := c.cc.Invoke(ctx, Membership_CheckEntitlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) CheckEntitlements(ctx context.Context, in *CheckEntitlementsReq, opts ...grpc.CallOption) (*CheckEntitlementsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEntitlementsReply)
	err := c.cc.Invoke(ctx, Membership_CheckEntitlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) GrantMembership(ctx context.Context, in *GrantMembershipReq, opts ...grpc.CallOption) (*GrantMembershipReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantMembershipReply)
	err := c.cc.Invoke(ctx, Membership_GrantMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) RevokeMembership(ctx context.Context, in *RevokeMembershipReq, opts ...grpc.CallOption) (*RevokeMembershipReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeMembershipReply)
	err := c.cc.Invoke(ctx, Membership_RevokeMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) SetAutoRenew(ctx context.Context, in *SetAutoRenewReq, opts ...grpc.CallOption) (*SetAutoRenewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAutoRenewReply)
	err := c.cc.Invoke(ctx, Membership_SetAutoRenew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) ListGrants(ctx context.Context, in *ListGrantsReq, opts ...grpc.CallOption) (*ListGrantsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGrantsReply)
	err := c.cc.Invoke(ctx, Membership_ListGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) ListExpiringMemberships(ctx context.Context, in *ListExpiringMembershipsReq, opts ...grpc.CallOption) (*ListExpiringMembershipsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExpiringMembershipsReply)
	err := c.cc.Invoke(ctx, Membership_ListExpiringMemberships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) ExpireMembership(ctx context.Context, in *ExpireMembershipReq, opts ...grpc.CallOption) (*ExpireMembershipReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpireMembershipReply)
	err := c.cc.Invoke(ctx, Membership_ExpireMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) ListEntitlements(ctx context.Context, in *ListEntitlementsReq, opts ...grpc.CallOption) (*ListEntitlementsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntitlementsReply)
	err := c.cc.Invoke(ctx, Membership_ListEntitlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) UpsertEntitlement(ctx context.Context, in *UpsertEntitlementReq, opts ...grpc.CallOption) (*EntitlementInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntitlementInfo)
	err := c.cc.Invoke(ctx, Membership_UpsertEntitlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServer is the server API for Membership service.
// All implementations must embed UnimplementedMembershipServer
// for forward compatibility.
//
// Membership 会员身份、套餐与权益判定服务。
type MembershipServer interface {
	// 终端套餐列表（只含在售且平台可见）
	ListPlans(context.Context, *ListPlansReq) (*ListPlansReply, error)
	// 单个套餐读取（下单前置校验用）
	GetPlan(context.Context, *GetPlanReq) (*GetPlanReply, error)
	// 运营面：新建或修改套餐草稿
	UpsertPlan(context.Context, *UpsertPlanReq) (*PlanInfo, error)
	// 运营面：上下架（带理由，写变更台账）
	SetPlanState(context.Context, *SetPlanStateReq) (*PlanInfo, error)
	// 运营面：分页查询全部套餐（含草稿与已下架）
	ListPlansAdmin(context.Context, *ListPlansAdminReq) (*ListPlansAdminReply, error)
	// 我的会员状态
	GetMembership(context.Context, *GetMembershipReq) (*GetMembershipReply, error)
	// 单项权益判定——全站唯一的会员权益口径出口
	CheckEntitlement(context.Context, *CheckEntitlementReq) (*CheckEntitlementReply, error)
	// 多项权益判定（播放详情页等一次问多项）
	CheckEntitlements(context.Context, *CheckEntitlementsReq) (*CheckEntitlementsReply, error)
	// 开通/续期（只由订单履约或运营授权调用）
	GrantMembership(context.Context, *GrantMembershipReq) (*GrantMembershipReply, error)
	// 收回（退款回收/运营纠错）
	RevokeMembership(context.Context, *RevokeMembershipReq) (*RevokeMembershipReply, error)
	// 自动续费签约位翻转（沙箱，不建真实代扣协议）
	SetAutoRenew(context.Context, *SetAutoRenewReq) (*SetAutoRenewReply, error)
	// 授予台账分页（运营面与用户面共用，mid=0 才有跨用户语义）
	ListGrants(context.Context, *ListGrantsReq) (*ListGrantsReply, error)
	// cron：扫描到期区间
	ListExpiringMemberships(context.Context, *ListExpiringMembershipsReq) (*ListExpiringMembershipsReply, error)
	// cron：幂等置过期
	ExpireMembership(context.Context, *ExpireMembershipReq) (*ExpireMembershipReply, error)
	// 权益码目录读取
	ListEntitlements(context.Context, *ListEntitlementsReq) (*ListEntitlementsReply, error)
	// 运营面：权益码新增/开关
	UpsertEntitlement(context.Context, *UpsertEntitlementReq) (*EntitlementInfo, error)
	mustEmbedUnimplementedMembershipServer()
}

// UnimplementedMembershipServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipServer struct{}

func (UnimplementedMembershipServer) ListPlans(context.Context, *ListPlansReq) (*ListPlansReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlans not implemented")
}
func (UnimplementedMembershipServer) GetPlan(context.Context, *GetPlanReq) (*GetPlanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedMembershipServer) UpsertPlan(context.Context, *UpsertPlanReq) (*PlanInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPlan not implemented")
}
func (UnimplementedMembershipServer) SetPlanState(context.Context, *SetPlanStateReq) (*PlanInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPlanState not implemented")
}
func (UnimplementedMembershipServer) ListPlansAdmin(context.Context, *ListPlansAdminReq) (*ListPlansAdminReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlansAdmin not implemented")
}
func (UnimplementedMembershipServer) GetMembership(context.Context, *GetMembershipReq) (*GetMembershipReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembership not implemented")
}
func (UnimplementedMembershipServer) CheckEntitlement(context.Context, *CheckEntitlementReq) (*CheckEntitlementReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEntitlement not implemented")
}
func (UnimplementedMembershipServer) CheckEntitlements(context.Context, *CheckEntitlementsReq) (*CheckEntitlementsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEntitlements not implemented")
}
func (UnimplementedMembershipServer) GrantMembership(context.Context, *GrantMembershipReq) (*GrantMembershipReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantMembership not implemented")
}
func (UnimplementedMembershipServer) RevokeMembership(context.Context, *RevokeMembershipReq) (*RevokeMembershipReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeMembership not implemented")
}
func (UnimplementedMembershipServer) SetAutoRenew(context.Context, *SetAutoRenewReq) (*SetAutoRenewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAutoRenew not implemented")
}
func (UnimplementedMembershipServer) ListGrants(context.Context, *ListGrantsReq) (*ListGrantsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGrants not implemented")
}
func (UnimplementedMembershipServer) ListExpiringMemberships(context.Context, *ListExpiringMembershipsReq) (*ListExpiringMembershipsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExpiringMemberships not implemented")
}
func (UnimplementedMembershipServer) ExpireMembership(context.Context, *ExpireMembershipReq) (*ExpireMembershipReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpireMembership not implemented")
}
func (UnimplementedMembershipServer) ListEntitlements(context.Context, *ListEntitlementsReq) (*ListEntitlementsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEntitlements not implemented")
}
func (UnimplementedMembershipServer) UpsertEntitlement(context.Context, *UpsertEntitlementReq) (*EntitlementInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertEntitlement not implemented")
}
func (UnimplementedMembershipServer) mustEmbedUnimplementedMembershipServer() {}
func (UnimplementedMembershipServer) testEmbeddedByValue()                    {}

// UnsafeMembershipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipServer will
// result in compilation errors.
type UnsafeMembershipServer interface {
	mustEmbedUnimplementedMembershipServer()
}

func RegisterMembershipServer(s grpc.ServiceRegistrar, srv MembershipServer) {
	// If the following call pancis, it indicates UnimplementedMembershipServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Membership_ServiceDesc, srv)
}

func _Membership_ListPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlansReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).ListPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_ListPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).ListPlans(ctx, req.(*ListPlansReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_GetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).GetPlan(ctx, req.(*GetPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_UpsertPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).UpsertPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_UpsertPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).UpsertPlan(ctx, req.(*UpsertPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_SetPlanState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlanStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).SetPlanState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_SetPlanState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).SetPlanState(ctx, req.(*SetPlanStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_ListPlansAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlansAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).ListPlansAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_ListPlansAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).ListPlansAdmin(ctx, req.(*ListPlansAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_GetMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).GetMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_GetMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).GetMembership(ctx, req.(*GetMembershipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_CheckEntitlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEntitlementReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).CheckEntitlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_CheckEntitlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).CheckEntitlement(ctx, req.(*CheckEntitlementReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_CheckEntitlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEntitlementsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).CheckEntitlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_CheckEntitlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).CheckEntitlements(ctx, req.(*CheckEntitlementsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_GrantMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantMembershipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).GrantMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_GrantMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).GrantMembership(ctx, req.(*GrantMembershipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_RevokeMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMembershipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).RevokeMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_RevokeMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).RevokeMembership(ctx, req.(*RevokeMembershipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_SetAutoRenew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoRenewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).SetAutoRenew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_SetAutoRenew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).SetAutoRenew(ctx, req.(*SetAutoRenewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_ListGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGrantsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).ListGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_ListGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).ListGrants(ctx, req.(*ListGrantsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_ListExpiringMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExpiringMembershipsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).ListExpiringMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_ListExpiringMemberships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).ListExpiringMemberships(ctx, req.(*ListExpiringMembershipsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_ExpireMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireMembershipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).ExpireMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_ExpireMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).ExpireMembership(ctx, req.(*ExpireMembershipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_ListEntitlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntitlementsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).ListEntitlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_ListEntitlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).ListEntitlements(ctx, req.(*ListEntitlementsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_UpsertEntitlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEntitlementReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).UpsertEntitlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_UpsertEntitlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).UpsertEntitlement(ctx, req.(*UpsertEntitlementReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Membership_ServiceDesc is the grpc.ServiceDesc for Membership service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Membership_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "membership.v1.Membership",
	HandlerType: (*MembershipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlans",
			Handler:    _Membership_ListPlans_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _Membership_GetPlan_Handler,
		},
		{
			MethodName: "UpsertPlan",
			Handler:    _Membership_UpsertPlan_Handler,
		},
		{
			MethodName: "SetPlanState",
			Handler:    _Membership_SetPlanState_Handler,
		},
		{
			MethodName: "ListPlansAdmin",
			Handler:    _Membership_ListPlansAdmin_Handler,
		},
		{
			MethodName: "GetMembership",
			Handler:    _Membership_GetMembership_Handler,
		},
		{
			MethodName: "CheckEntitlement",
			Handler:    _Membership_CheckEntitlement_Handler,
		},
		{
			MethodName: "CheckEntitlements",
			Handler:    _Membership_CheckEntitlements_Handler,
		},
		{
			MethodName: "GrantMembership",
			Handler:    _Membership_GrantMembership_Handler,
		},
		{
			MethodName: "RevokeMembership",
			Handler:    _Membership_RevokeMembership_Handler,
		},
		{
			MethodName: "SetAutoRenew",
			Handler:    _Membership_SetAutoRenew_Handler,
		},
		{
			MethodName: "ListGrants",
			Handler:    _Membership_ListGrants_Handler,
		},
		{
			MethodName: "ListExpiringMemberships",
			Handler:    _Membership_ListExpiringMemberships_Handler,
		},
		{
			MethodName: "ExpireMembership",
			Handler:    _Membership_ExpireMembership_Handler,
		},
		{
			MethodName: "ListEntitlements",
			Handler:    _Membership_ListEntitlements_Handler,
		},
		{
			MethodName: "UpsertEntitlement",
			Handler:    _Membership_UpsertEntitlement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/membership/rpc/membership.proto",
}
