// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: livemedia.proto

package server

import (
	"context"

	"go-video/services/live-media/internal/logic"
	"go-video/services/live-media/internal/svc"
	"go-video/services/live-media/rpc"
)

type LiveMediaServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedLiveMediaServer
}

func NewLiveMediaServer(svcCtx *svc.ServiceContext) *LiveMediaServer {
	return &LiveMediaServer{
		svcCtx: svcCtx,
	}
}

// 登记直播转码任务（PENDING），request_id 幂等；不在此调用 FFmpeg
func (s *LiveMediaServer) StartLiveTranscode(ctx context.Context, in *rpc.StartLiveTranscodeReq) (*rpc.LiveTranscodeTaskInfo, error) {
	l := logic.NewStartLiveTranscodeLogic(ctx, s.svcCtx)
	return l.StartLiveTranscode(in)
}

// 请求停止（RUNNING→STOPPING，Worker 收尾后 STOPPED）
func (s *LiveMediaServer) StopLiveTranscode(ctx context.Context, in *rpc.StopLiveTranscodeReq) (*rpc.LiveTranscodeTaskInfo, error) {
	l := logic.NewStopLiveTranscodeLogic(ctx, s.svcCtx)
	return l.StopLiveTranscode(in)
}

// 重试失败任务（FAILED→PENDING，attempt+1，受 max_attempts 限制）
func (s *LiveMediaServer) RetryLiveTranscode(ctx context.Context, in *rpc.RetryLiveTranscodeReq) (*rpc.LiveTranscodeTaskInfo, error) {
	l := logic.NewRetryLiveTranscodeLogic(ctx, s.svcCtx)
	return l.RetryLiveTranscode(in)
}

// 取消未运行/停止中的任务（PENDING|STOPPING→CANCELLED 终态）
func (s *LiveMediaServer) CancelLiveTranscode(ctx context.Context, in *rpc.CancelLiveTranscodeReq) (*rpc.LiveTranscodeTaskInfo, error) {
	l := logic.NewCancelLiveTranscodeLogic(ctx, s.svcCtx)
	return l.CancelLiveTranscode(in)
}

// Worker 上报心跳/进度/终态（含超时判定），条件 UPDATE + 版本校验
func (s *LiveMediaServer) ReportLiveTranscodeProgress(ctx context.Context, in *rpc.ReportLiveTranscodeProgressReq) (*rpc.LiveTranscodeTaskInfo, error) {
	l := logic.NewReportLiveTranscodeProgressLogic(ctx, s.svcCtx)
	return l.ReportLiveTranscodeProgress(in)
}

// 查询单个转码任务
func (s *LiveMediaServer) GetLiveTranscodeTask(ctx context.Context, in *rpc.LiveTranscodeTaskReq) (*rpc.LiveTranscodeTaskInfo, error) {
	l := logic.NewGetLiveTranscodeTaskLogic(ctx, s.svcCtx)
	return l.GetLiveTranscodeTask(in)
}

// 分页查询转码任务（房间/场次/状态/模板）
func (s *LiveMediaServer) ListLiveTranscodeTasks(ctx context.Context, in *rpc.ListLiveTranscodeTasksReq) (*rpc.ListLiveTranscodeTasksReply, error) {
	l := logic.NewListLiveTranscodeTasksLogic(ctx, s.svcCtx)
	return l.ListLiveTranscodeTasks(in)
}

// 登记或刷新一个码率档位的分发输出（(room,session,level,protocol) 唯一）
func (s *LiveMediaServer) UpsertStreamOutput(ctx context.Context, in *rpc.UpsertStreamOutputReq) (*rpc.StreamOutputInfo, error) {
	l := logic.NewUpsertStreamOutputLogic(ctx, s.svcCtx)
	return l.UpsertStreamOutput(in)
}

// 下线一个档位（断流/到期/人工），与回放发布状态无关
func (s *LiveMediaServer) OfflineStreamOutput(ctx context.Context, in *rpc.OfflineStreamOutputReq) (*rpc.StreamOutputInfo, error) {
	l := logic.NewOfflineStreamOutputLogic(ctx, s.svcCtx)
	return l.OfflineStreamOutput(in)
}

// 查询房间当前可分发档位（live-gateway / live-room 只读投影）
func (s *LiveMediaServer) ListStreamOutputs(ctx context.Context, in *rpc.ListStreamOutputsReq) (*rpc.ListStreamOutputsReply, error) {
	l := logic.NewListStreamOutputsLogic(ctx, s.svcCtx)
	return l.ListStreamOutputs(in)
}

// 登记录制任务（PENDING），request_id 幂等
func (s *LiveMediaServer) StartLiveRecord(ctx context.Context, in *rpc.StartLiveRecordReq) (*rpc.LiveRecordTaskInfo, error) {
	l := logic.NewStartLiveRecordLogic(ctx, s.svcCtx)
	return l.StartLiveRecord(in)
}

// 停止录制（RECORDING→STOPPING，最后一片落库后 STOPPED）
func (s *LiveMediaServer) StopLiveRecord(ctx context.Context, in *rpc.StopLiveRecordReq) (*rpc.LiveRecordTaskInfo, error) {
	l := logic.NewStopLiveRecordLogic(ctx, s.svcCtx)
	return l.StopLiveRecord(in)
}

// Worker 上报录制心跳与状态（含超时/断点续录）
func (s *LiveMediaServer) ReportLiveRecordProgress(ctx context.Context, in *rpc.ReportLiveRecordProgressReq) (*rpc.LiveRecordTaskInfo, error) {
	l := logic.NewReportLiveRecordProgressLogic(ctx, s.svcCtx)
	return l.ReportLiveRecordProgress(in)
}

// 查询单个录制任务（含 last_seq，供断点续录）
func (s *LiveMediaServer) GetLiveRecordTask(ctx context.Context, in *rpc.LiveRecordTaskReq) (*rpc.LiveRecordTaskInfo, error) {
	l := logic.NewGetLiveRecordTaskLogic(ctx, s.svcCtx)
	return l.GetLiveRecordTask(in)
}

// 分页查询录制任务
func (s *LiveMediaServer) ListLiveRecordTasks(ctx context.Context, in *rpc.ListLiveRecordTasksReq) (*rpc.ListLiveRecordTasksReply, error) {
	l := logic.NewListLiveRecordTasksLogic(ctx, s.svcCtx)
	return l.ListLiveRecordTasks(in)
}

// 逐片登记切片（(record_id,seq) 幂等，缺口必须显式登记 MISSING）
func (s *LiveMediaServer) ReportRecordSegment(ctx context.Context, in *rpc.ReportRecordSegmentReq) (*rpc.RecordSegmentInfo, error) {
	l := logic.NewReportRecordSegmentLogic(ctx, s.svcCtx)
	return l.ReportRecordSegment(in)
}

// keyset 分页拉取切片（回放拼接与排障）
func (s *LiveMediaServer) ListRecordSegments(ctx context.Context, in *rpc.ListRecordSegmentsReq) (*rpc.ListRecordSegmentsReply, error) {
	l := logic.NewListRecordSegmentsLogic(ctx, s.svcCtx)
	return l.ListRecordSegments(in)
}

// 提交回放拼接任务（只登记与校验切片区间，不拼接、不发布）
func (s *LiveMediaServer) SubmitReplayTask(ctx context.Context, in *rpc.SubmitReplayTaskReq) (*rpc.LiveReplayTaskInfo, error) {
	l := logic.NewSubmitReplayTaskLogic(ctx, s.svcCtx)
	return l.SubmitReplayTask(in)
}

// Worker 上报回放进度（拼接/上传/登记/送审）
func (s *LiveMediaServer) ReportReplayProgress(ctx context.Context, in *rpc.ReportReplayProgressReq) (*rpc.LiveReplayTaskInfo, error) {
	l := logic.NewReportReplayProgressLogic(ctx, s.svcCtx)
	return l.ReportReplayProgress(in)
}

// 查询单个回放任务
func (s *LiveMediaServer) GetReplayTask(ctx context.Context, in *rpc.ReplayTaskReq) (*rpc.LiveReplayTaskInfo, error) {
	l := logic.NewGetReplayTaskLogic(ctx, s.svcCtx)
	return l.GetReplayTask(in)
}

// 分页查询回放任务
func (s *LiveMediaServer) ListReplayTasks(ctx context.Context, in *rpc.ListReplayTasksReq) (*rpc.ListReplayTasksReply, error) {
	l := logic.NewListReplayTasksLogic(ctx, s.svcCtx)
	return l.ListReplayTasks(in)
}

// 回填回放产物与 asset/稿件的引用关系（只存引用，不推进稿件状态）
func (s *LiveMediaServer) BindReplayAsset(ctx context.Context, in *rpc.BindReplayAssetReq) (*rpc.ReplayAssetRefInfo, error) {
	l := logic.NewBindReplayAssetLogic(ctx, s.svcCtx)
	return l.BindReplayAsset(in)
}

// 同步 video 侧审核/发布投影（单向：video → live-media）
func (s *LiveMediaServer) ApplyReplayContentState(ctx context.Context, in *rpc.ApplyReplayContentStateReq) (*rpc.ReplayAssetRefInfo, error) {
	l := logic.NewApplyReplayContentStateLogic(ctx, s.svcCtx)
	return l.ApplyReplayContentState(in)
}

// 分页查询回放资产引用（房间/场次/主播/投影状态）
func (s *LiveMediaServer) ListReplayAssetRefs(ctx context.Context, in *rpc.ListReplayAssetRefsReq) (*rpc.ListReplayAssetRefsReply, error) {
	l := logic.NewListReplayAssetRefsLogic(ctx, s.svcCtx)
	return l.ListReplayAssetRefs(in)
}

// 提交回收任务（超期切片/回放产物/残留档位），先登记后执行，保留审计证据
func (s *LiveMediaServer) SubmitRetentionTask(ctx context.Context, in *rpc.SubmitRetentionTaskReq) (*rpc.LiveRetentionTaskInfo, error) {
	l := logic.NewSubmitRetentionTaskLogic(ctx, s.svcCtx)
	return l.SubmitRetentionTask(in)
}

// Worker 上报回收结果（扫描/删除/跳过计数）
func (s *LiveMediaServer) ReportRetentionResult(ctx context.Context, in *rpc.ReportRetentionResultReq) (*rpc.LiveRetentionTaskInfo, error) {
	l := logic.NewReportRetentionResultLogic(ctx, s.svcCtx)
	return l.ReportRetentionResult(in)
}

// 查询单个回收任务
func (s *LiveMediaServer) GetRetentionTask(ctx context.Context, in *rpc.RetentionTaskReq) (*rpc.LiveRetentionTaskInfo, error) {
	l := logic.NewGetRetentionTaskLogic(ctx, s.svcCtx)
	return l.GetRetentionTask(in)
}

// 分页查询回收任务
func (s *LiveMediaServer) ListRetentionTasks(ctx context.Context, in *rpc.ListRetentionTasksReq) (*rpc.ListRetentionTasksReply, error) {
	l := logic.NewListRetentionTasksLogic(ctx, s.svcCtx)
	return l.ListRetentionTasks(in)
}
