// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.9
// source: comment.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 评论排序
type SortMode int32

const (
	SortMode_SORT_UNSPECIFIED SortMode = 0 // 未指定（默认按热度）
	SortMode_SORT_HOT         SortMode = 1 // 按热度
	SortMode_SORT_TIME        SortMode = 2 // 按时间倒序
)

// Enum value maps for SortMode.
var (
	SortMode_name = map[int32]string{
		0: "SORT_UNSPECIFIED",
		1: "SORT_HOT",
		2: "SORT_TIME",
	}
	SortMode_value = map[string]int32{
		"SORT_UNSPECIFIED": 0,
		"SORT_HOT":         1,
		"SORT_TIME":        2,
	}
)

func (x SortMode) Enum() *SortMode {
	p := new(SortMode)
	*p = x
	return p
}

func (x SortMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortMode) Descriptor() protoreflect.EnumDescriptor {
	return file_comment_proto_enumTypes[0].Descriptor()
}

func (SortMode) Type() protoreflect.EnumType {
	return &file_comment_proto_enumTypes[0]
}

func (x SortMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortMode.Descriptor instead.
func (SortMode) EnumDescriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{0}
}

// 评论状态
type CommentState int32

const (
	CommentState_STATE_NORMAL   CommentState = 0 // 正常
	CommentState_STATE_FOLDED   CommentState = 1 // 折叠（被举报或低质）
	CommentState_STATE_DELETED  CommentState = 2 // 已删除
	CommentState_STATE_PINNED   CommentState = 3 // 置顶
	CommentState_STATE_PENDING  CommentState = 4 // 待审核
	CommentState_STATE_REJECTED CommentState = 5 // 审核驳回
)

// Enum value maps for CommentState.
var (
	CommentState_name = map[int32]string{
		0: "STATE_NORMAL",
		1: "STATE_FOLDED",
		2: "STATE_DELETED",
		3: "STATE_PINNED",
		4: "STATE_PENDING",
		5: "STATE_REJECTED",
	}
	CommentState_value = map[string]int32{
		"STATE_NORMAL":   0,
		"STATE_FOLDED":   1,
		"STATE_DELETED":  2,
		"STATE_PINNED":   3,
		"STATE_PENDING":  4,
		"STATE_REJECTED": 5,
	}
)

func (x CommentState) Enum() *CommentState {
	p := new(CommentState)
	*p = x
	return p
}

func (x CommentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentState) Descriptor() protoreflect.EnumDescriptor {
	return file_comment_proto_enumTypes[1].Descriptor()
}

func (CommentState) Type() protoreflect.EnumType {
	return &file_comment_proto_enumTypes[1]
}

func (x CommentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentState.Descriptor instead.
func (CommentState) EnumDescriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{1}
}

// 空响应
type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{0}
}

// 评论目标类型（与 obc reply 兼容：1 视频、4 评论回复、5 图片、6 视频（UGV）、9 番剧、10 番剧评论）
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           int64                  `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"` // 目标 ID（视频 aid / 评论 root 等）
	Tp            int32                  `protobuf:"varint,2,opt,name=tp,proto3" json:"tp,omitempty"`   // 目标类型，参见上文注释
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{1}
}

func (x *Target) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *Target) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

// 评论主体（DB 行投影）。
// 注：message 名取 CommentInfo 而非 Comment，避免与 service Comment 同名冲突。
type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rpid          int64                  `protobuf:"varint,1,opt,name=rpid,proto3" json:"rpid,omitempty"`                                // 评论 ID
	Oid           int64                  `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`                                  // 目标 ID
	Tp            int32                  `protobuf:"varint,3,opt,name=tp,proto3" json:"tp,omitempty"`                                    // 目标类型
	Root          int64                  `protobuf:"varint,4,opt,name=root,proto3" json:"root,omitempty"`                                // 根评论 ID（0 表示本身是根评论）
	Parent        int64                  `protobuf:"varint,5,opt,name=parent,proto3" json:"parent,omitempty"`                            // 父评论 ID（0 表示直接对 oid 评论）
	Mid           int64                  `protobuf:"varint,6,opt,name=mid,proto3" json:"mid,omitempty"`                                  // 评论者用户 ID
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`                           // 评论内容（明文，富文本由 gateway 渲染）
	State         int32                  `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`                              // 评论状态，参见 CommentState
	Ctime         int64                  `protobuf:"varint,9,opt,name=ctime,proto3" json:"ctime,omitempty"`                              // 创建时间（Unix 秒）
	Mtime         int64                  `protobuf:"varint,10,opt,name=mtime,proto3" json:"mtime,omitempty"`                             // 修改时间（Unix 秒）
	LikeCount     int32                  `protobuf:"varint,11,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`    // 点赞数快照（真实计数归 engagement）
	ReplyCount    int32                  `protobuf:"varint,12,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"` // 回复数快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CommentInfo) GetRpid() int64 {
	if x != nil {
		return x.Rpid
	}
	return 0
}

func (x *CommentInfo) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *CommentInfo) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

func (x *CommentInfo) GetRoot() int64 {
	if x != nil {
		return x.Root
	}
	return 0
}

func (x *CommentInfo) GetParent() int64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *CommentInfo) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CommentInfo) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *CommentInfo) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *CommentInfo) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentInfo) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

type PostCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           int64                  `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`                       // 目标 ID
	Tp            int32                  `protobuf:"varint,2,opt,name=tp,proto3" json:"tp,omitempty"`                         // 目标类型
	Root          int64                  `protobuf:"varint,3,opt,name=root,proto3" json:"root,omitempty"`                     // 根评论 ID（直接对 oid 评论时为 0）
	Parent        int64                  `protobuf:"varint,4,opt,name=parent,proto3" json:"parent,omitempty"`                 // 父评论 ID（同上）
	Mid           int64                  `protobuf:"varint,5,opt,name=mid,proto3" json:"mid,omitempty"`                       // 评论者用户 ID
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                // 评论内容
	State         int32                  `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`                   // 初始状态（通常为 STATE_PENDING 待审核）
	TraceId       string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 调用方透传 trace_id，便于审核链路关联
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentReq) Reset() {
	*x = PostCommentReq{}
	mi := &file_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentReq) ProtoMessage() {}

func (x *PostCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentReq.ProtoReflect.Descriptor instead.
func (*PostCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{3}
}

func (x *PostCommentReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *PostCommentReq) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

func (x *PostCommentReq) GetRoot() int64 {
	if x != nil {
		return x.Root
	}
	return 0
}

func (x *PostCommentReq) GetParent() int64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *PostCommentReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *PostCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostCommentReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *PostCommentReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type PostCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rpid          int64                  `protobuf:"varint,1,opt,name=rpid,proto3" json:"rpid,omitempty"`   // 新评论 ID
	Ctime         int64                  `protobuf:"varint,2,opt,name=ctime,proto3" json:"ctime,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentReply) Reset() {
	*x = PostCommentReply{}
	mi := &file_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentReply) ProtoMessage() {}

func (x *PostCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentReply.ProtoReflect.Descriptor instead.
func (*PostCommentReply) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{4}
}

func (x *PostCommentReply) GetRpid() int64 {
	if x != nil {
		return x.Rpid
	}
	return 0
}

func (x *PostCommentReply) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rpid          int64                  `protobuf:"varint,1,opt,name=rpid,proto3" json:"rpid,omitempty"`   // 评论 ID
	Mid           int64                  `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`     // 操作者用户 ID（用于鉴权校验）
	Admin         bool                   `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"` // 是否管理员操作（管理员可绕过本人校验）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentReq) GetRpid() int64 {
	if x != nil {
		return x.Rpid
	}
	return 0
}

func (x *DeleteCommentReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *DeleteCommentReq) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type ListCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           int64                  `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`                              // 目标 ID
	Tp            int32                  `protobuf:"varint,2,opt,name=tp,proto3" json:"tp,omitempty"`                                // 目标类型
	ViewerMid     int64                  `protobuf:"varint,3,opt,name=viewer_mid,json=viewerMid,proto3" json:"viewer_mid,omitempty"` // 查看者用户 ID（用于过滤黑名单/屏蔽词）
	Sort          SortMode               `protobuf:"varint,4,opt,name=sort,proto3,enum=comment.v1.SortMode" json:"sort,omitempty"`   // 排序方式
	Pn            int32                  `protobuf:"varint,5,opt,name=pn,proto3" json:"pn,omitempty"`                                // 页码（从 1 开始）
	Ps            int32                  `protobuf:"varint,6,opt,name=ps,proto3" json:"ps,omitempty"`                                // 每页大小（最大 49，与 obc 一致）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReq) Reset() {
	*x = ListCommentsReq{}
	mi := &file_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReq) ProtoMessage() {}

func (x *ListCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReq.ProtoReflect.Descriptor instead.
func (*ListCommentsReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{6}
}

func (x *ListCommentsReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *ListCommentsReq) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

func (x *ListCommentsReq) GetViewerMid() int64 {
	if x != nil {
		return x.ViewerMid
	}
	return 0
}

func (x *ListCommentsReq) GetSort() SortMode {
	if x != nil {
		return x.Sort
	}
	return SortMode_SORT_UNSPECIFIED
}

func (x *ListCommentsReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *ListCommentsReq) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

type ListCommentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"` // 评论列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`      // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReply) Reset() {
	*x = ListCommentsReply{}
	mi := &file_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReply) ProtoMessage() {}

func (x *ListCommentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReply.ProtoReflect.Descriptor instead.
func (*ListCommentsReply) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{7}
}

func (x *ListCommentsReply) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListRepliesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          int64                  `protobuf:"varint,1,opt,name=root,proto3" json:"root,omitempty"`                            // 根评论 ID
	ViewerMid     int64                  `protobuf:"varint,2,opt,name=viewer_mid,json=viewerMid,proto3" json:"viewer_mid,omitempty"` // 查看者用户 ID
	Pn            int32                  `protobuf:"varint,3,opt,name=pn,proto3" json:"pn,omitempty"`                                // 页码
	Ps            int32                  `protobuf:"varint,4,opt,name=ps,proto3" json:"ps,omitempty"`                                // 每页大小（最大 49）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepliesReq) Reset() {
	*x = ListRepliesReq{}
	mi := &file_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepliesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepliesReq) ProtoMessage() {}

func (x *ListRepliesReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepliesReq.ProtoReflect.Descriptor instead.
func (*ListRepliesReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{8}
}

func (x *ListRepliesReq) GetRoot() int64 {
	if x != nil {
		return x.Root
	}
	return 0
}

func (x *ListRepliesReq) GetViewerMid() int64 {
	if x != nil {
		return x.ViewerMid
	}
	return 0
}

func (x *ListRepliesReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *ListRepliesReq) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

type ListRepliesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*CommentInfo         `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"` // 回复列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`    // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepliesReply) Reset() {
	*x = ListRepliesReply{}
	mi := &file_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepliesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepliesReply) ProtoMessage() {}

func (x *ListRepliesReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepliesReply.ProtoReflect.Descriptor instead.
func (*ListRepliesReply) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{9}
}

func (x *ListRepliesReply) GetReplies() []*CommentInfo {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *ListRepliesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PinCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rpid          int64                  `protobuf:"varint,1,opt,name=rpid,proto3" json:"rpid,omitempty"`                         // 评论 ID
	Oid           int64                  `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`                           // 目标 ID（用于校验）
	Pin           bool                   `protobuf:"varint,3,opt,name=pin,proto3" json:"pin,omitempty"`                           // true 置顶、false 取消
	AdminMid      int64                  `protobuf:"varint,4,opt,name=admin_mid,json=adminMid,proto3" json:"admin_mid,omitempty"` // 操作管理员（需为视频 UP 或管理员）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinCommentReq) Reset() {
	*x = PinCommentReq{}
	mi := &file_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinCommentReq) ProtoMessage() {}

func (x *PinCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinCommentReq.ProtoReflect.Descriptor instead.
func (*PinCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{10}
}

func (x *PinCommentReq) GetRpid() int64 {
	if x != nil {
		return x.Rpid
	}
	return 0
}

func (x *PinCommentReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *PinCommentReq) GetPin() bool {
	if x != nil {
		return x.Pin
	}
	return false
}

func (x *PinCommentReq) GetAdminMid() int64 {
	if x != nil {
		return x.AdminMid
	}
	return 0
}

type ReportCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rpid          int64                  `protobuf:"varint,1,opt,name=rpid,proto3" json:"rpid,omitempty"`                                  // 被举报评论 ID
	ReporterMid   int64                  `protobuf:"varint,2,opt,name=reporter_mid,json=reporterMid,proto3" json:"reporter_mid,omitempty"` // 举报者用户 ID
	Reason        int32                  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`                              // 举报原因码
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                             // 举报理由补充说明
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`              // 透传 trace_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCommentReq) Reset() {
	*x = ReportCommentReq{}
	mi := &file_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCommentReq) ProtoMessage() {}

func (x *ReportCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCommentReq.ProtoReflect.Descriptor instead.
func (*ReportCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{11}
}

func (x *ReportCommentReq) GetRpid() int64 {
	if x != nil {
		return x.Rpid
	}
	return 0
}

func (x *ReportCommentReq) GetReporterMid() int64 {
	if x != nil {
		return x.ReporterMid
	}
	return 0
}

func (x *ReportCommentReq) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *ReportCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReportCommentReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CommentStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           int64                  `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"` // 目标 ID
	Tp            int32                  `protobuf:"varint,2,opt,name=tp,proto3" json:"tp,omitempty"`   // 目标类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentStatsReq) Reset() {
	*x = CommentStatsReq{}
	mi := &file_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentStatsReq) ProtoMessage() {}

func (x *CommentStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentStatsReq.ProtoReflect.Descriptor instead.
func (*CommentStatsReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{12}
}

func (x *CommentStatsReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *CommentStatsReq) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

type CommentStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                          // 目标下评论总数（含回复）
	RootTotal     int64                  `protobuf:"varint,2,opt,name=root_total,json=rootTotal,proto3" json:"root_total,omitempty"` // 根评论数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentStatsReply) Reset() {
	*x = CommentStatsReply{}
	mi := &file_comment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentStatsReply) ProtoMessage() {}

func (x *CommentStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentStatsReply.ProtoReflect.Descriptor instead.
func (*CommentStatsReply) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{13}
}

func (x *CommentStatsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CommentStatsReply) GetRootTotal() int64 {
	if x != nil {
		return x.RootTotal
	}
	return 0
}

var File_comment_proto protoreflect.FileDescriptor

const file_comment_proto_rawDesc = "" +
	"\n" +
	"\rcomment.proto\x12\n" +
	"comment.v1\"\f\n" +
	"\n" +
	"EmptyReply\"*\n" +
	"\x06Target\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x03R\x03oid\x12\x0e\n" +
	"\x02tp\x18\x02 \x01(\x05R\x02tp\"\x9d\x02\n" +
	"\vCommentInfo\x12\x12\n" +
	"\x04rpid\x18\x01 \x01(\x03R\x04rpid\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x12\x0e\n" +
	"\x02tp\x18\x03 \x01(\x05R\x02tp\x12\x12\n" +
	"\x04root\x18\x04 \x01(\x03R\x04root\x12\x16\n" +
	"\x06parent\x18\x05 \x01(\x03R\x06parent\x12\x10\n" +
	"\x03mid\x18\x06 \x01(\x03R\x03mid\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x14\n" +
	"\x05state\x18\b \x01(\x05R\x05state\x12\x14\n" +
	"\x05ctime\x18\t \x01(\x03R\x05ctime\x12\x14\n" +
	"\x05mtime\x18\n" +
	" \x01(\x03R\x05mtime\x12\x1d\n" +
	"\n" +
	"like_count\x18\v \x01(\x05R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\f \x01(\x05R\n" +
	"replyCount\"\xbb\x01\n" +
	"\x0ePostCommentReq\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x03R\x03oid\x12\x0e\n" +
	"\x02tp\x18\x02 \x01(\x05R\x02tp\x12\x12\n" +
	"\x04root\x18\x03 \x01(\x03R\x04root\x12\x16\n" +
	"\x06parent\x18\x04 \x01(\x03R\x06parent\x12\x10\n" +
	"\x03mid\x18\x05 \x01(\x03R\x03mid\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x14\n" +
	"\x05state\x18\a \x01(\x05R\x05state\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\"<\n" +
	"\x10PostCommentReply\x12\x12\n" +
	"\x04rpid\x18\x01 \x01(\x03R\x04rpid\x12\x14\n" +
	"\x05ctime\x18\x02 \x01(\x03R\x05ctime\"N\n" +
	"\x10DeleteCommentReq\x12\x12\n" +
	"\x04rpid\x18\x01 \x01(\x03R\x04rpid\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05admin\x18\x03 \x01(\bR\x05admin\"\x9c\x01\n" +
	"\x0fListCommentsReq\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x03R\x03oid\x12\x0e\n" +
	"\x02tp\x18\x02 \x01(\x05R\x02tp\x12\x1d\n" +
	"\n" +
	"viewer_mid\x18\x03 \x01(\x03R\tviewerMid\x12(\n" +
	"\x04sort\x18\x04 \x01(\x0e2\x14.comment.v1.SortModeR\x04sort\x12\x0e\n" +
	"\x02pn\x18\x05 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\x06 \x01(\x05R\x02ps\"^\n" +
	"\x11ListCommentsReply\x123\n" +
	"\bcomments\x18\x01 \x03(\v2\x17.comment.v1.CommentInfoR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"c\n" +
	"\x0eListRepliesReq\x12\x12\n" +
	"\x04root\x18\x01 \x01(\x03R\x04root\x12\x1d\n" +
	"\n" +
	"viewer_mid\x18\x02 \x01(\x03R\tviewerMid\x12\x0e\n" +
	"\x02pn\x18\x03 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\x04 \x01(\x05R\x02ps\"[\n" +
	"\x10ListRepliesReply\x121\n" +
	"\areplies\x18\x01 \x03(\v2\x17.comment.v1.CommentInfoR\areplies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"d\n" +
	"\rPinCommentReq\x12\x12\n" +
	"\x04rpid\x18\x01 \x01(\x03R\x04rpid\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\x03R\x03oid\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\bR\x03pin\x12\x1b\n" +
	"\tadmin_mid\x18\x04 \x01(\x03R\badminMid\"\x96\x01\n" +
	"\x10ReportCommentReq\x12\x12\n" +
	"\x04rpid\x18\x01 \x01(\x03R\x04rpid\x12!\n" +
	"\freporter_mid\x18\x02 \x01(\x03R\vreporterMid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"3\n" +
	"\x0fCommentStatsReq\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x03R\x03oid\x12\x0e\n" +
	"\x02tp\x18\x02 \x01(\x05R\x02tp\"H\n" +
	"\x11CommentStatsReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"root_total\x18\x02 \x01(\x03R\trootTotal*=\n" +
	"\bSortMode\x12\x14\n" +
	"\x10SORT_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSORT_HOT\x10\x01\x12\r\n" +
	"\tSORT_TIME\x10\x02*~\n" +
	"\fCommentState\x12\x10\n" +
	"\fSTATE_NORMAL\x10\x00\x12\x10\n" +
	"\fSTATE_FOLDED\x10\x01\x12\x11\n" +
	"\rSTATE_DELETED\x10\x02\x12\x10\n" +
	"\fSTATE_PINNED\x10\x03\x12\x11\n" +
	"\rSTATE_PENDING\x10\x04\x12\x12\n" +
	"\x0eSTATE_REJECTED\x10\x052\x82\x04\n" +
	"\aComment\x12G\n" +
	"\vPostComment\x12\x1a.comment.v1.PostCommentReq\x1a\x1c.comment.v1.PostCommentReply\x12E\n" +
	"\rDeleteComment\x12\x1c.comment.v1.DeleteCommentReq\x1a\x16.comment.v1.EmptyReply\x12J\n" +
	"\fListComments\x12\x1b.comment.v1.ListCommentsReq\x1a\x1d.comment.v1.ListCommentsReply\x12G\n" +
	"\vListReplies\x12\x1a.comment.v1.ListRepliesReq\x1a\x1c.comment.v1.ListRepliesReply\x12?\n" +
	"\n" +
	"PinComment\x12\x19.comment.v1.PinCommentReq\x1a\x16.comment.v1.EmptyReply\x12E\n" +
	"\rReportComment\x12\x1c.comment.v1.ReportCommentReq\x1a\x16.comment.v1.EmptyReply\x12J\n" +
	"\fCommentStats\x12\x1b.comment.v1.CommentStatsReq\x1a\x1d.comment.v1.CommentStatsReplyB\x1fZ\x1dgo-video/services/comment/rpcb\x06proto3"

var (
	file_comment_proto_rawDescOnce sync.Once
	file_comment_proto_rawDescData []byte
)

func file_comment_proto_rawDescGZIP() []byte {
	file_comment_proto_rawDescOnce.Do(func() {
		file_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)))
	})
	return file_comment_proto_rawDescData
}

var file_comment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_comment_proto_goTypes = []any{
	(SortMode)(0),             // 0: comment.v1.SortMode
	(CommentState)(0),         // 1: comment.v1.CommentState
	(*EmptyReply)(nil),        // 2: comment.v1.EmptyReply
	(*Target)(nil),            // 3: comment.v1.Target
	(*CommentInfo)(nil),       // 4: comment.v1.CommentInfo
	(*PostCommentReq)(nil),    // 5: comment.v1.PostCommentReq
	(*PostCommentReply)(nil),  // 6: comment.v1.PostCommentReply
	(*DeleteCommentReq)(nil),  // 7: comment.v1.DeleteCommentReq
	(*ListCommentsReq)(nil),   // 8: comment.v1.ListCommentsReq
	(*ListCommentsReply)(nil), // 9: comment.v1.ListCommentsReply
	(*ListRepliesReq)(nil),    // 10: comment.v1.ListRepliesReq
	(*ListRepliesReply)(nil),  // 11: comment.v1.ListRepliesReply
	(*PinCommentReq)(nil),     // 12: comment.v1.PinCommentReq
	(*ReportCommentReq)(nil),  // 13: comment.v1.ReportCommentReq
	(*CommentStatsReq)(nil),   // 14: comment.v1.CommentStatsReq
	(*CommentStatsReply)(nil), // 15: comment.v1.CommentStatsReply
}
var file_comment_proto_depIdxs = []int32{
	0,  // 0: comment.v1.ListCommentsReq.sort:type_name -> comment.v1.SortMode
	4,  // 1: comment.v1.ListCommentsReply.comments:type_name -> comment.v1.CommentInfo
	4,  // 2: comment.v1.ListRepliesReply.replies:type_name -> comment.v1.CommentInfo
	5,  // 3: comment.v1.Comment.PostComment:input_type -> comment.v1.PostCommentReq
	7,  // 4: comment.v1.Comment.DeleteComment:input_type -> comment.v1.DeleteCommentReq
	8,  // 5: comment.v1.Comment.ListComments:input_type -> comment.v1.ListCommentsReq
	10, // 6: comment.v1.Comment.ListReplies:input_type -> comment.v1.ListRepliesReq
	12, // 7: comment.v1.Comment.PinComment:input_type -> comment.v1.PinCommentReq
	13, // 8: comment.v1.Comment.ReportComment:input_type -> comment.v1.ReportCommentReq
	14, // 9: comment.v1.Comment.CommentStats:input_type -> comment.v1.CommentStatsReq
	6,  // 10: comment.v1.Comment.PostComment:output_type -> comment.v1.PostCommentReply
	2,  // 11: comment.v1.Comment.DeleteComment:output_type -> comment.v1.EmptyReply
	9,  // 12: comment.v1.Comment.ListComments:output_type -> comment.v1.ListCommentsReply
	11, // 13: comment.v1.Comment.ListReplies:output_type -> comment.v1.ListRepliesReply
	2,  // 14: comment.v1.Comment.PinComment:output_type -> comment.v1.EmptyReply
	2,  // 15: comment.v1.Comment.ReportComment:output_type -> comment.v1.EmptyReply
	15, // 16: comment.v1.Comment.CommentStats:output_type -> comment.v1.CommentStatsReply
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_comment_proto_init() }
func file_comment_proto_init() {
	if File_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_proto_goTypes,
		DependencyIndexes: file_comment_proto_depIdxs,
		EnumInfos:         file_comment_proto_enumTypes,
		MessageInfos:      file_comment_proto_msgTypes,
	}.Build()
	File_comment_proto = out.File
	file_comment_proto_goTypes = nil
	file_comment_proto_depIdxs = nil
}
