// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.9
// source: creator.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空请求（对应参考仓库 NoArgReq）
type NoArgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoArgReq) Reset() {
	*x = NoArgReq{}
	mi := &file_creator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoArgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoArgReq) ProtoMessage() {}

func (x *NoArgReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoArgReq.ProtoReflect.Descriptor instead.
func (*NoArgReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{0}
}

// 空响应（对应参考仓库 NoReply）
type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_creator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{1}
}

// 单个创作者请求
type MidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"` // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MidReq) Reset() {
	*x = MidReq{}
	mi := &file_creator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MidReq) ProtoMessage() {}

func (x *MidReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MidReq.ProtoReflect.Descriptor instead.
func (*MidReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{2}
}

func (x *MidReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

// 批量创作者请求（最多 100 个）
type MidsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mids          []int64                `protobuf:"varint,1,rep,packed,name=mids,proto3" json:"mids,omitempty"` // 用户 ID 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MidsReq) Reset() {
	*x = MidsReq{}
	mi := &file_creator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MidsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MidsReq) ProtoMessage() {}

func (x *MidsReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MidsReq.ProtoReflect.Descriptor instead.
func (*MidsReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{3}
}

func (x *MidsReq) GetMids() []int64 {
	if x != nil {
		return x.Mids
	}
	return nil
}

// UP 主特殊用户组信息
type UpGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // 分组 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // 分组名
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`                              // 标签名称
	ShortTag      string                 `protobuf:"bytes,4,opt,name=short_tag,json=shortTag,proto3" json:"short_tag,omitempty"`    // 标签简称
	FontColor     string                 `protobuf:"bytes,5,opt,name=font_color,json=fontColor,proto3" json:"font_color,omitempty"` // 字体色
	BgColor       string                 `protobuf:"bytes,6,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"`       // 背景色
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`                            // 备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpGroup) Reset() {
	*x = UpGroup{}
	mi := &file_creator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpGroup) ProtoMessage() {}

func (x *UpGroup) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpGroup.ProtoReflect.Descriptor instead.
func (*UpGroup) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{4}
}

func (x *UpGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpGroup) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UpGroup) GetShortTag() string {
	if x != nil {
		return x.ShortTag
	}
	return ""
}

func (x *UpGroup) GetFontColor() string {
	if x != nil {
		return x.FontColor
	}
	return ""
}

func (x *UpGroup) GetBgColor() string {
	if x != nil {
		return x.BgColor
	}
	return ""
}

func (x *UpGroup) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// UP 主特殊属性
type UpSpecial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIds      []int64                `protobuf:"varint,1,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"` // 所属特殊分组 ID 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpSpecial) Reset() {
	*x = UpSpecial{}
	mi := &file_creator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpSpecial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpSpecial) ProtoMessage() {}

func (x *UpSpecial) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpSpecial.ProtoReflect.Descriptor instead.
func (*UpSpecial) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{5}
}

func (x *UpSpecial) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

// 单个 UP 主特殊属性请求
type UpSpecialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"` // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpSpecialReq) Reset() {
	*x = UpSpecialReq{}
	mi := &file_creator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpSpecialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpSpecialReq) ProtoMessage() {}

func (x *UpSpecialReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpSpecialReq.ProtoReflect.Descriptor instead.
func (*UpSpecialReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{6}
}

func (x *UpSpecialReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

// 多个 UP 主特殊属性请求
type UpsSpecialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mids          []int64                `protobuf:"varint,1,rep,packed,name=mids,proto3" json:"mids,omitempty"` // 用户 ID 列表（最多 100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsSpecialReq) Reset() {
	*x = UpsSpecialReq{}
	mi := &file_creator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsSpecialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsSpecialReq) ProtoMessage() {}

func (x *UpsSpecialReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsSpecialReq.ProtoReflect.Descriptor instead.
func (*UpsSpecialReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{7}
}

func (x *UpsSpecialReq) GetMids() []int64 {
	if x != nil {
		return x.Mids
	}
	return nil
}

// 特殊属性响应
type UpSpecialReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpSpecial     *UpSpecial             `protobuf:"bytes,1,opt,name=up_special,json=upSpecial,proto3" json:"up_special,omitempty"` // 特殊属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpSpecialReply) Reset() {
	*x = UpSpecialReply{}
	mi := &file_creator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpSpecialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpSpecialReply) ProtoMessage() {}

func (x *UpSpecialReply) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpSpecialReply.ProtoReflect.Descriptor instead.
func (*UpSpecialReply) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{8}
}

func (x *UpSpecialReply) GetUpSpecial() *UpSpecial {
	if x != nil {
		return x.UpSpecial
	}
	return nil
}

// 多个特殊属性响应
type UpsSpecialReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpSpecials    map[int64]*UpSpecial   `protobuf:"bytes,1,rep,name=up_specials,json=upSpecials,proto3" json:"up_specials,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // mid → 特殊属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsSpecialReply) Reset() {
	*x = UpsSpecialReply{}
	mi := &file_creator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsSpecialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsSpecialReply) ProtoMessage() {}

func (x *UpsSpecialReply) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsSpecialReply.ProtoReflect.Descriptor instead.
func (*UpsSpecialReply) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{9}
}

func (x *UpsSpecialReply) GetUpSpecials() map[int64]*UpSpecial {
	if x != nil {
		return x.UpSpecials
	}
	return nil
}

// 所有特殊分组响应
type UpGroupsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpGroups      map[int64]*UpGroup     `protobuf:"bytes,1,rep,name=up_groups,json=upGroups,proto3" json:"up_groups,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 分组 ID → 分组信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpGroupsReply) Reset() {
	*x = UpGroupsReply{}
	mi := &file_creator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpGroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpGroupsReply) ProtoMessage() {}

func (x *UpGroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpGroupsReply.ProtoReflect.Descriptor instead.
func (*UpGroupsReply) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{10}
}

func (x *UpGroupsReply) GetUpGroups() map[int64]*UpGroup {
	if x != nil {
		return x.UpGroups
	}
	return nil
}

// 分组下用户请求
type UpGroupMidsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 分组 ID
	Pn            int32                  `protobuf:"varint,2,opt,name=pn,proto3" json:"pn,omitempty"`                          // 页码（从 1 开始）
	Ps            int32                  `protobuf:"varint,3,opt,name=ps,proto3" json:"ps,omitempty"`                          // 每页大小（最大 1000）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpGroupMidsReq) Reset() {
	*x = UpGroupMidsReq{}
	mi := &file_creator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpGroupMidsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpGroupMidsReq) ProtoMessage() {}

func (x *UpGroupMidsReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpGroupMidsReq.ProtoReflect.Descriptor instead.
func (*UpGroupMidsReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{11}
}

func (x *UpGroupMidsReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpGroupMidsReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *UpGroupMidsReq) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

// 分组下用户响应
type UpGroupMidsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mids          []int64                `protobuf:"varint,1,rep,packed,name=mids,proto3" json:"mids,omitempty"` // 分组下用户 ID
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`      // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpGroupMidsReply) Reset() {
	*x = UpGroupMidsReply{}
	mi := &file_creator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpGroupMidsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpGroupMidsReply) ProtoMessage() {}

func (x *UpGroupMidsReply) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpGroupMidsReply.ProtoReflect.Descriptor instead.
func (*UpGroupMidsReply) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{12}
}

func (x *UpGroupMidsReply) GetMids() []int64 {
	if x != nil {
		return x.Mids
	}
	return nil
}

func (x *UpGroupMidsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UP 主身份属性请求
type UpAttrReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`   // 用户 ID
	From          int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"` // 来源：0 稿件作者、1 移动投稿作者、2 直播 UP、3 直播白名单
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpAttrReq) Reset() {
	*x = UpAttrReq{}
	mi := &file_creator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpAttrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpAttrReq) ProtoMessage() {}

func (x *UpAttrReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpAttrReq.ProtoReflect.Descriptor instead.
func (*UpAttrReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{13}
}

func (x *UpAttrReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UpAttrReq) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

// UP 主身份属性响应
type UpAttrReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAuthor      int32                  `protobuf:"varint,1,opt,name=is_author,json=isAuthor,proto3" json:"is_author,omitempty"` // 是否有身份：0 否、1 是
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpAttrReply) Reset() {
	*x = UpAttrReply{}
	mi := &file_creator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpAttrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpAttrReply) ProtoMessage() {}

func (x *UpAttrReply) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpAttrReply.ProtoReflect.Descriptor instead.
func (*UpAttrReply) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{14}
}

func (x *UpAttrReply) GetIsAuthor() int32 {
	if x != nil {
		return x.IsAuthor
	}
	return 0
}

// 关注弹窗开关请求（设置和查询共用）
type UpSwitchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`     // 用户 ID
	From          int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`   // 业务来源：0 播放器关注开关、1 UP 主荣誉周报退订
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"` // 开关状态：0 关闭、1 打开（仅 SetUpSwitch 使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpSwitchReq) Reset() {
	*x = UpSwitchReq{}
	mi := &file_creator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpSwitchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpSwitchReq) ProtoMessage() {}

func (x *UpSwitchReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpSwitchReq.ProtoReflect.Descriptor instead.
func (*UpSwitchReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{15}
}

func (x *UpSwitchReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UpSwitchReq) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *UpSwitchReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 关注弹窗开关响应
type UpSwitchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         int32                  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"` // 当前开关状态：0 关闭、1 打开
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpSwitchReply) Reset() {
	*x = UpSwitchReply{}
	mi := &file_creator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpSwitchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpSwitchReply) ProtoMessage() {}

func (x *UpSwitchReply) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpSwitchReply.ProtoReflect.Descriptor instead.
func (*UpSwitchReply) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{16}
}

func (x *UpSwitchReply) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 高能联盟 UP 主请求
type HighAllyUpsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mids          []int64                `protobuf:"varint,1,rep,packed,name=mids,proto3" json:"mids,omitempty"` // 用户 ID 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighAllyUpsReq) Reset() {
	*x = HighAllyUpsReq{}
	mi := &file_creator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighAllyUpsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighAllyUpsReq) ProtoMessage() {}

func (x *HighAllyUpsReq) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighAllyUpsReq.ProtoReflect.Descriptor instead.
func (*HighAllyUpsReq) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{17}
}

func (x *HighAllyUpsReq) GetMids() []int64 {
	if x != nil {
		return x.Mids
	}
	return nil
}

// 签约信息
type SignUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`                              // 签约 UP 主 ID
	State         int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`                          // 签约状态
	BeginDate     int64                  `protobuf:"varint,3,opt,name=begin_date,json=beginDate,proto3" json:"begin_date,omitempty"` // 签约开始时间（Unix 秒）
	EndDate       int64                  `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 签约结束时间（Unix 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUp) Reset() {
	*x = SignUp{}
	mi := &file_creator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUp) ProtoMessage() {}

func (x *SignUp) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUp.ProtoReflect.Descriptor instead.
func (*SignUp) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{18}
}

func (x *SignUp) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *SignUp) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *SignUp) GetBeginDate() int64 {
	if x != nil {
		return x.BeginDate
	}
	return 0
}

func (x *SignUp) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

// 高能联盟 UP 主响应
type HighAllyUpsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lists         map[int64]*SignUp      `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // mid → 签约信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighAllyUpsReply) Reset() {
	*x = HighAllyUpsReply{}
	mi := &file_creator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighAllyUpsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighAllyUpsReply) ProtoMessage() {}

func (x *HighAllyUpsReply) ProtoReflect() protoreflect.Message {
	mi := &file_creator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighAllyUpsReply.ProtoReflect.Descriptor instead.
func (*HighAllyUpsReply) Descriptor() ([]byte, []int) {
	return file_creator_proto_rawDescGZIP(), []int{19}
}

func (x *HighAllyUpsReply) GetLists() map[int64]*SignUp {
	if x != nil {
		return x.Lists
	}
	return nil
}

var File_creator_proto protoreflect.FileDescriptor

const file_creator_proto_rawDesc = "" +
	"\n" +
	"\rcreator.proto\x12\n" +
	"creator.v1\"\n" +
	"\n" +
	"\bNoArgReq\"\f\n" +
	"\n" +
	"EmptyReply\"\x1a\n" +
	"\x06MidReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\"\x1d\n" +
	"\aMidsReq\x12\x12\n" +
	"\x04mids\x18\x01 \x03(\x03R\x04mids\"\xaa\x01\n" +
	"\aUpGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x1b\n" +
	"\tshort_tag\x18\x04 \x01(\tR\bshortTag\x12\x1d\n" +
	"\n" +
	"font_color\x18\x05 \x01(\tR\tfontColor\x12\x19\n" +
	"\bbg_color\x18\x06 \x01(\tR\abgColor\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\"(\n" +
	"\tUpSpecial\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\x03R\bgroupIds\" \n" +
	"\fUpSpecialReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\"#\n" +
	"\rUpsSpecialReq\x12\x12\n" +
	"\x04mids\x18\x01 \x03(\x03R\x04mids\"F\n" +
	"\x0eUpSpecialReply\x124\n" +
	"\n" +
	"up_special\x18\x01 \x01(\v2\x15.creator.v1.UpSpecialR\tupSpecial\"\xb5\x01\n" +
	"\x0fUpsSpecialReply\x12L\n" +
	"\vup_specials\x18\x01 \x03(\v2+.creator.v1.UpsSpecialReply.UpSpecialsEntryR\n" +
	"upSpecials\x1aT\n" +
	"\x0fUpSpecialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.creator.v1.UpSpecialR\x05value:\x028\x01\"\xa7\x01\n" +
	"\rUpGroupsReply\x12D\n" +
	"\tup_groups\x18\x01 \x03(\v2'.creator.v1.UpGroupsReply.UpGroupsEntryR\bupGroups\x1aP\n" +
	"\rUpGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.creator.v1.UpGroupR\x05value:\x028\x01\"K\n" +
	"\x0eUpGroupMidsReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x0e\n" +
	"\x02pn\x18\x02 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\x03 \x01(\x05R\x02ps\"<\n" +
	"\x10UpGroupMidsReply\x12\x12\n" +
	"\x04mids\x18\x01 \x03(\x03R\x04mids\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"1\n" +
	"\tUpAttrReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\"*\n" +
	"\vUpAttrReply\x12\x1b\n" +
	"\tis_author\x18\x01 \x01(\x05R\bisAuthor\"I\n" +
	"\vUpSwitchReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\"%\n" +
	"\rUpSwitchReply\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state\"$\n" +
	"\x0eHighAllyUpsReq\x12\x12\n" +
	"\x04mids\x18\x01 \x03(\x03R\x04mids\"j\n" +
	"\x06SignUp\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12\x1d\n" +
	"\n" +
	"begin_date\x18\x03 \x01(\x03R\tbeginDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\x03R\aendDate\"\x9f\x01\n" +
	"\x10HighAllyUpsReply\x12=\n" +
	"\x05lists\x18\x01 \x03(\v2'.creator.v1.HighAllyUpsReply.ListsEntryR\x05lists\x1aL\n" +
	"\n" +
	"ListsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.creator.v1.SignUpR\x05value:\x028\x012\x9e\x04\n" +
	"\aCreator\x12A\n" +
	"\tUpSpecial\x12\x18.creator.v1.UpSpecialReq\x1a\x1a.creator.v1.UpSpecialReply\x12D\n" +
	"\n" +
	"UpsSpecial\x12\x19.creator.v1.UpsSpecialReq\x1a\x1b.creator.v1.UpsSpecialReply\x12;\n" +
	"\bUpGroups\x12\x14.creator.v1.NoArgReq\x1a\x19.creator.v1.UpGroupsReply\x12G\n" +
	"\vUpGroupMids\x12\x1a.creator.v1.UpGroupMidsReq\x1a\x1c.creator.v1.UpGroupMidsReply\x128\n" +
	"\x06UpAttr\x12\x15.creator.v1.UpAttrReq\x1a\x17.creator.v1.UpAttrReply\x12>\n" +
	"\vSetUpSwitch\x12\x17.creator.v1.UpSwitchReq\x1a\x16.creator.v1.EmptyReply\x12>\n" +
	"\bUpSwitch\x12\x17.creator.v1.UpSwitchReq\x1a\x19.creator.v1.UpSwitchReply\x12J\n" +
	"\x0eGetHighAllyUps\x12\x1a.creator.v1.HighAllyUpsReq\x1a\x1c.creator.v1.HighAllyUpsReplyB\x1fZ\x1dgo-video/services/creator/rpcb\x06proto3"

var (
	file_creator_proto_rawDescOnce sync.Once
	file_creator_proto_rawDescData []byte
)

func file_creator_proto_rawDescGZIP() []byte {
	file_creator_proto_rawDescOnce.Do(func() {
		file_creator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_creator_proto_rawDesc), len(file_creator_proto_rawDesc)))
	})
	return file_creator_proto_rawDescData
}

var file_creator_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_creator_proto_goTypes = []any{
	(*NoArgReq)(nil),         // 0: creator.v1.NoArgReq
	(*EmptyReply)(nil),       // 1: creator.v1.EmptyReply
	(*MidReq)(nil),           // 2: creator.v1.MidReq
	(*MidsReq)(nil),          // 3: creator.v1.MidsReq
	(*UpGroup)(nil),          // 4: creator.v1.UpGroup
	(*UpSpecial)(nil),        // 5: creator.v1.UpSpecial
	(*UpSpecialReq)(nil),     // 6: creator.v1.UpSpecialReq
	(*UpsSpecialReq)(nil),    // 7: creator.v1.UpsSpecialReq
	(*UpSpecialReply)(nil),   // 8: creator.v1.UpSpecialReply
	(*UpsSpecialReply)(nil),  // 9: creator.v1.UpsSpecialReply
	(*UpGroupsReply)(nil),    // 10: creator.v1.UpGroupsReply
	(*UpGroupMidsReq)(nil),   // 11: creator.v1.UpGroupMidsReq
	(*UpGroupMidsReply)(nil), // 12: creator.v1.UpGroupMidsReply
	(*UpAttrReq)(nil),        // 13: creator.v1.UpAttrReq
	(*UpAttrReply)(nil),      // 14: creator.v1.UpAttrReply
	(*UpSwitchReq)(nil),      // 15: creator.v1.UpSwitchReq
	(*UpSwitchReply)(nil),    // 16: creator.v1.UpSwitchReply
	(*HighAllyUpsReq)(nil),   // 17: creator.v1.HighAllyUpsReq
	(*SignUp)(nil),           // 18: creator.v1.SignUp
	(*HighAllyUpsReply)(nil), // 19: creator.v1.HighAllyUpsReply
	nil,                      // 20: creator.v1.UpsSpecialReply.UpSpecialsEntry
	nil,                      // 21: creator.v1.UpGroupsReply.UpGroupsEntry
	nil,                      // 22: creator.v1.HighAllyUpsReply.ListsEntry
}
var file_creator_proto_depIdxs = []int32{
	5,  // 0: creator.v1.UpSpecialReply.up_special:type_name -> creator.v1.UpSpecial
	20, // 1: creator.v1.UpsSpecialReply.up_specials:type_name -> creator.v1.UpsSpecialReply.UpSpecialsEntry
	21, // 2: creator.v1.UpGroupsReply.up_groups:type_name -> creator.v1.UpGroupsReply.UpGroupsEntry
	22, // 3: creator.v1.HighAllyUpsReply.lists:type_name -> creator.v1.HighAllyUpsReply.ListsEntry
	5,  // 4: creator.v1.UpsSpecialReply.UpSpecialsEntry.value:type_name -> creator.v1.UpSpecial
	4,  // 5: creator.v1.UpGroupsReply.UpGroupsEntry.value:type_name -> creator.v1.UpGroup
	18, // 6: creator.v1.HighAllyUpsReply.ListsEntry.value:type_name -> creator.v1.SignUp
	6,  // 7: creator.v1.Creator.UpSpecial:input_type -> creator.v1.UpSpecialReq
	7,  // 8: creator.v1.Creator.UpsSpecial:input_type -> creator.v1.UpsSpecialReq
	0,  // 9: creator.v1.Creator.UpGroups:input_type -> creator.v1.NoArgReq
	11, // 10: creator.v1.Creator.UpGroupMids:input_type -> creator.v1.UpGroupMidsReq
	13, // 11: creator.v1.Creator.UpAttr:input_type -> creator.v1.UpAttrReq
	15, // 12: creator.v1.Creator.SetUpSwitch:input_type -> creator.v1.UpSwitchReq
	15, // 13: creator.v1.Creator.UpSwitch:input_type -> creator.v1.UpSwitchReq
	17, // 14: creator.v1.Creator.GetHighAllyUps:input_type -> creator.v1.HighAllyUpsReq
	8,  // 15: creator.v1.Creator.UpSpecial:output_type -> creator.v1.UpSpecialReply
	9,  // 16: creator.v1.Creator.UpsSpecial:output_type -> creator.v1.UpsSpecialReply
	10, // 17: creator.v1.Creator.UpGroups:output_type -> creator.v1.UpGroupsReply
	12, // 18: creator.v1.Creator.UpGroupMids:output_type -> creator.v1.UpGroupMidsReply
	14, // 19: creator.v1.Creator.UpAttr:output_type -> creator.v1.UpAttrReply
	1,  // 20: creator.v1.Creator.SetUpSwitch:output_type -> creator.v1.EmptyReply
	16, // 21: creator.v1.Creator.UpSwitch:output_type -> creator.v1.UpSwitchReply
	19, // 22: creator.v1.Creator.GetHighAllyUps:output_type -> creator.v1.HighAllyUpsReply
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_creator_proto_init() }
func file_creator_proto_init() {
	if File_creator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_creator_proto_rawDesc), len(file_creator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_creator_proto_goTypes,
		DependencyIndexes: file_creator_proto_depIdxs,
		MessageInfos:      file_creator_proto_msgTypes,
	}.Build()
	File_creator_proto = out.File
	file_creator_proto_goTypes = nil
	file_creator_proto_depIdxs = nil
}
