// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.9
// source: notification.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 投递通道（不含小程序，AGENTS.md §6）
type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0 // 未指定
	Channel_CHANNEL_PUSH        Channel = 1 // 应用推送（Android/iOS/HarmonyOS/桌面端）
	Channel_CHANNEL_SMS         Channel = 2 // 短信
	Channel_CHANNEL_EMAIL       Channel = 3 // 邮件
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_PUSH",
		2: "CHANNEL_SMS",
		3: "CHANNEL_EMAIL",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_PUSH":        1,
		"CHANNEL_SMS":         2,
		"CHANNEL_EMAIL":       3,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

// 模板语言（不含小程序端专属语言包）
type Language int32

const (
	Language_LANGUAGE_UNSPECIFIED Language = 0 // 未指定，按用户偏好或全局默认回落
	Language_LANGUAGE_ZH_CN       Language = 1 // 简体中文
	Language_LANGUAGE_ZH_TW       Language = 2 // 繁体中文
	Language_LANGUAGE_EN          Language = 3 // 英文
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANGUAGE_UNSPECIFIED",
		1: "LANGUAGE_ZH_CN",
		2: "LANGUAGE_ZH_TW",
		3: "LANGUAGE_EN",
	}
	Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"LANGUAGE_ZH_CN":       1,
		"LANGUAGE_ZH_TW":       2,
		"LANGUAGE_EN":          3,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[1].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[1]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

// 投递任务状态机（合法迁移见 services/notification/README.md）
type DeliveryState int32

const (
	DeliveryState_DELIVERY_STATE_UNSPECIFIED DeliveryState = 0 // 未指定
	DeliveryState_DELIVERY_PENDING           DeliveryState = 1 // 已落库待投递
	DeliveryState_DELIVERY_SENT              DeliveryState = 2 // 供应商已受理（终态）
	DeliveryState_DELIVERY_FAILED            DeliveryState = 3 // 不可重试失败（终态，需人工介入）
	DeliveryState_DELIVERY_RETRY             DeliveryState = 4 // 待退避重试
	DeliveryState_DELIVERY_DEAD_LETTER       DeliveryState = 5 // 超过重试上限，转死信留档（终态）
	DeliveryState_DELIVERY_SUPPRESSED        DeliveryState = 6 // 被免打扰/频控/去重拦截，未调用供应商（终态）
)

// Enum value maps for DeliveryState.
var (
	DeliveryState_name = map[int32]string{
		0: "DELIVERY_STATE_UNSPECIFIED",
		1: "DELIVERY_PENDING",
		2: "DELIVERY_SENT",
		3: "DELIVERY_FAILED",
		4: "DELIVERY_RETRY",
		5: "DELIVERY_DEAD_LETTER",
		6: "DELIVERY_SUPPRESSED",
	}
	DeliveryState_value = map[string]int32{
		"DELIVERY_STATE_UNSPECIFIED": 0,
		"DELIVERY_PENDING":           1,
		"DELIVERY_SENT":              2,
		"DELIVERY_FAILED":            3,
		"DELIVERY_RETRY":             4,
		"DELIVERY_DEAD_LETTER":       5,
		"DELIVERY_SUPPRESSED":        6,
	}
)

func (x DeliveryState) Enum() *DeliveryState {
	p := new(DeliveryState)
	*p = x
	return p
}

func (x DeliveryState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryState) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[2].Descriptor()
}

func (DeliveryState) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[2]
}

func (x DeliveryState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryState.Descriptor instead.
func (DeliveryState) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

// 模板状态
type TemplateState int32

const (
	TemplateState_TEMPLATE_STATE_UNSPECIFIED TemplateState = 0 // 未指定
	TemplateState_TEMPLATE_STATE_DRAFT       TemplateState = 1 // 草稿，不可用于投递
	TemplateState_TEMPLATE_STATE_PUBLISHED   TemplateState = 2 // 已发布，可投递
	TemplateState_TEMPLATE_STATE_OFFLINE     TemplateState = 3 // 已下线，只读留档
)

// Enum value maps for TemplateState.
var (
	TemplateState_name = map[int32]string{
		0: "TEMPLATE_STATE_UNSPECIFIED",
		1: "TEMPLATE_STATE_DRAFT",
		2: "TEMPLATE_STATE_PUBLISHED",
		3: "TEMPLATE_STATE_OFFLINE",
	}
	TemplateState_value = map[string]int32{
		"TEMPLATE_STATE_UNSPECIFIED": 0,
		"TEMPLATE_STATE_DRAFT":       1,
		"TEMPLATE_STATE_PUBLISHED":   2,
		"TEMPLATE_STATE_OFFLINE":     3,
	}
)

func (x TemplateState) Enum() *TemplateState {
	p := new(TemplateState)
	*p = x
	return p
}

func (x TemplateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateState) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[3].Descriptor()
}

func (TemplateState) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[3]
}

func (x TemplateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateState.Descriptor instead.
func (TemplateState) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

// 事件消费状态（docs/api-and-events.md §6）
type EventState int32

const (
	EventState_EVENT_STATE_UNSPECIFIED EventState = 0 // 未指定
	EventState_EVENT_RECEIVED          EventState = 1 // 已收到，未开始处理
	EventState_EVENT_PROCESSING        EventState = 2 // 处理中
	EventState_EVENT_SUCCEEDED         EventState = 3 // 处理成功（终态）
	EventState_EVENT_RETRY             EventState = 4 // 处理失败，等待退避重试
	EventState_EVENT_DEAD_LETTER       EventState = 5 // 重试耗尽，转死信留档（终态）
)

// Enum value maps for EventState.
var (
	EventState_name = map[int32]string{
		0: "EVENT_STATE_UNSPECIFIED",
		1: "EVENT_RECEIVED",
		2: "EVENT_PROCESSING",
		3: "EVENT_SUCCEEDED",
		4: "EVENT_RETRY",
		5: "EVENT_DEAD_LETTER",
	}
	EventState_value = map[string]int32{
		"EVENT_STATE_UNSPECIFIED": 0,
		"EVENT_RECEIVED":          1,
		"EVENT_PROCESSING":        2,
		"EVENT_SUCCEEDED":         3,
		"EVENT_RETRY":             4,
		"EVENT_DEAD_LETTER":       5,
	}
)

func (x EventState) Enum() *EventState {
	p := new(EventState)
	*p = x
	return p
}

func (x EventState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventState) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[4].Descriptor()
}

func (EventState) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[4]
}

func (x EventState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventState.Descriptor instead.
func (EventState) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

// 死信处置状态
type DeadLetterState int32

const (
	DeadLetterState_DEAD_LETTER_STATE_UNSPECIFIED DeadLetterState = 0 // 未指定
	DeadLetterState_DEAD_LETTER_PENDING           DeadLetterState = 1 // 待运营处理
	DeadLetterState_DEAD_LETTER_RETRIED           DeadLetterState = 2 // 已被重投（终态）
	DeadLetterState_DEAD_LETTER_DISCARDED         DeadLetterState = 3 // 已丢弃（终态）
)

// Enum value maps for DeadLetterState.
var (
	DeadLetterState_name = map[int32]string{
		0: "DEAD_LETTER_STATE_UNSPECIFIED",
		1: "DEAD_LETTER_PENDING",
		2: "DEAD_LETTER_RETRIED",
		3: "DEAD_LETTER_DISCARDED",
	}
	DeadLetterState_value = map[string]int32{
		"DEAD_LETTER_STATE_UNSPECIFIED": 0,
		"DEAD_LETTER_PENDING":           1,
		"DEAD_LETTER_RETRIED":           2,
		"DEAD_LETTER_DISCARDED":         3,
	}
)

func (x DeadLetterState) Enum() *DeadLetterState {
	p := new(DeadLetterState)
	*p = x
	return p
}

func (x DeadLetterState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeadLetterState) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[5].Descriptor()
}

func (DeadLetterState) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[5]
}

func (x DeadLetterState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeadLetterState.Descriptor instead.
func (DeadLetterState) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

// 投递优先级；HIGH 用于验证码/安全提醒，可绕过免打扰窗口（不绕过频控）
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1 // 低优先（运营类提醒）
	Priority_PRIORITY_NORMAL      Priority = 2 // 普通
	Priority_PRIORITY_HIGH        Priority = 3 // 高优先（安全提醒、审核结论）
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[6].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[6]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

// 空响应
type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

// 接收人（只携带受控标识，不放明文联系方式）
type Recipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`                                         // 用户 ID（首选，account 域主键）
	TargetRef     string                 `protobuf:"bytes,2,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`             // 受控投递引用：push 设备 token 引用、供应商侧收件人 ID 或哈希标识
	Language      Language               `protobuf:"varint,3,opt,name=language,proto3,enum=notification.v1.Language" json:"language,omitempty"` // 期望语言；LANGUAGE_UNSPECIFIED 时按用户偏好回落
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                // push 设备标识（客户端上报，可用于多设备去重）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Recipient) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *Recipient) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *Recipient) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *Recipient) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// 模板（notification_template 表投影）
type TemplateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // 自增主键
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`    // 模板业务码
	Channel       Channel                `protobuf:"varint,3,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`    // 通道
	Language      Language               `protobuf:"varint,4,opt,name=language,proto3,enum=notification.v1.Language" json:"language,omitempty"` // 语言
	TitleTpl      string                 `protobuf:"bytes,5,opt,name=title_tpl,json=titleTpl,proto3" json:"title_tpl,omitempty"`                // 标题模板
	BodyTpl       string                 `protobuf:"bytes,6,opt,name=body_tpl,json=bodyTpl,proto3" json:"body_tpl,omitempty"`                   // 正文模板
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`                                 // 版本号（同一 code/channel/lang 递增）
	State         TemplateState          `protobuf:"varint,8,opt,name=state,proto3,enum=notification.v1.TemplateState" json:"state,omitempty"`  // 模板状态
	Operator      string                 `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`                                // 最后操作人（运营账号，来自 operation 域）
	Ctime         int64                  `protobuf:"varint,10,opt,name=ctime,proto3" json:"ctime,omitempty"`                                    // 创建时间（Unix 秒）
	Mtime         int64                  `protobuf:"varint,11,opt,name=mtime,proto3" json:"mtime,omitempty"`                                    // 修改时间（Unix 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateInfo) Reset() {
	*x = TemplateInfo{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateInfo) ProtoMessage() {}

func (x *TemplateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateInfo.ProtoReflect.Descriptor instead.
func (*TemplateInfo) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TemplateInfo) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *TemplateInfo) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *TemplateInfo) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *TemplateInfo) GetTitleTpl() string {
	if x != nil {
		return x.TitleTpl
	}
	return ""
}

func (x *TemplateInfo) GetBodyTpl() string {
	if x != nil {
		return x.BodyTpl
	}
	return ""
}

func (x *TemplateInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TemplateInfo) GetState() TemplateState {
	if x != nil {
		return x.State
	}
	return TemplateState_TEMPLATE_STATE_UNSPECIFIED
}

func (x *TemplateInfo) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *TemplateInfo) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *TemplateInfo) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

// 投递记录（notification_delivery 表投影，含供应商回执）
type DeliveryInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId      string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`                 // 投递任务 ID
	BizKey          string                 `protobuf:"bytes,2,opt,name=biz_key,json=bizKey,proto3" json:"biz_key,omitempty"`                             // 业务幂等键（唯一索引）
	Mid             int64                  `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`                                                // 接收人用户 ID（0 表示仅有 target_ref）
	Channel         Channel                `protobuf:"varint,4,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`           // 通道
	TemplateCode    string                 `protobuf:"bytes,5,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`           // 模板码
	TemplateVersion int32                  `protobuf:"varint,6,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"` // 模板版本
	TargetRef       string                 `protobuf:"bytes,7,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`                    // 受控投递标识（非明文号码）
	PayloadDigest   string                 `protobuf:"bytes,8,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`        // 渲染结果摘要（sha256 hex），不落明文正文
	State           DeliveryState          `protobuf:"varint,9,opt,name=state,proto3,enum=notification.v1.DeliveryState" json:"state,omitempty"`         // 状态
	Provider        string                 `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`                                      // 实际使用的通道适配器名
	ProviderMsgId   string                 `protobuf:"bytes,11,opt,name=provider_msg_id,json=providerMsgId,proto3" json:"provider_msg_id,omitempty"`     // 供应商回执消息 ID
	RetryCount      int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`               // 已重试次数
	NextRetryAt     int64                  `protobuf:"varint,13,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`          // 下次重试时间（Unix 秒，0 表示不再重试）
	LastError       string                 `protobuf:"bytes,14,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`                   // 最近一次错误（脱敏）
	SentAt          int64                  `protobuf:"varint,15,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`                           // 投递成功时间（Unix 秒）
	ExpireAt        int64                  `protobuf:"varint,16,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`                     // 过期时间（Unix 秒，0 表示不过期）
	Priority        int32                  `protobuf:"varint,17,opt,name=priority,proto3" json:"priority,omitempty"`                                     // 优先级，参见 Priority
	TraceId         string                 `protobuf:"bytes,18,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                         // 链路 ID
	Ctime           int64                  `protobuf:"varint,19,opt,name=ctime,proto3" json:"ctime,omitempty"`                                           // 创建时间（Unix 秒）
	Mtime           int64                  `protobuf:"varint,20,opt,name=mtime,proto3" json:"mtime,omitempty"`                                           // 修改时间（Unix 秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeliveryInfo) Reset() {
	*x = DeliveryInfo{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryInfo) ProtoMessage() {}

func (x *DeliveryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryInfo.ProtoReflect.Descriptor instead.
func (*DeliveryInfo) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryInfo) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryInfo) GetBizKey() string {
	if x != nil {
		return x.BizKey
	}
	return ""
}

func (x *DeliveryInfo) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *DeliveryInfo) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *DeliveryInfo) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *DeliveryInfo) GetTemplateVersion() int32 {
	if x != nil {
		return x.TemplateVersion
	}
	return 0
}

func (x *DeliveryInfo) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *DeliveryInfo) GetPayloadDigest() string {
	if x != nil {
		return x.PayloadDigest
	}
	return ""
}

func (x *DeliveryInfo) GetState() DeliveryState {
	if x != nil {
		return x.State
	}
	return DeliveryState_DELIVERY_STATE_UNSPECIFIED
}

func (x *DeliveryInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DeliveryInfo) GetProviderMsgId() string {
	if x != nil {
		return x.ProviderMsgId
	}
	return ""
}

func (x *DeliveryInfo) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *DeliveryInfo) GetNextRetryAt() int64 {
	if x != nil {
		return x.NextRetryAt
	}
	return 0
}

func (x *DeliveryInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *DeliveryInfo) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *DeliveryInfo) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *DeliveryInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DeliveryInfo) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DeliveryInfo) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *DeliveryInfo) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

// 死信记录（notification_dead_letter 表投影）
type DeadLetterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 自增主键
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                    // 事件 ID（去重键）
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`              // 事件类型
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`                                       // 来源 topic
	PayloadDigest string                 `protobuf:"bytes,5,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`  // 原始报文摘要（不落明文，避免敏感信息留档）
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                     // 死信原因
	State         DeadLetterState        `protobuf:"varint,7,opt,name=state,proto3,enum=notification.v1.DeadLetterState" json:"state,omitempty"` // 处置状态
	Operator      string                 `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`                                 // 处置人
	Ctime         int64                  `protobuf:"varint,9,opt,name=ctime,proto3" json:"ctime,omitempty"`                                      // 创建时间（Unix 秒）
	Mtime         int64                  `protobuf:"varint,10,opt,name=mtime,proto3" json:"mtime,omitempty"`                                     // 修改时间（Unix 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeadLetterInfo) Reset() {
	*x = DeadLetterInfo{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetterInfo) ProtoMessage() {}

func (x *DeadLetterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetterInfo.ProtoReflect.Descriptor instead.
func (*DeadLetterInfo) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *DeadLetterInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeadLetterInfo) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeadLetterInfo) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DeadLetterInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DeadLetterInfo) GetPayloadDigest() string {
	if x != nil {
		return x.PayloadDigest
	}
	return ""
}

func (x *DeadLetterInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DeadLetterInfo) GetState() DeadLetterState {
	if x != nil {
		return x.State
	}
	return DeadLetterState_DEAD_LETTER_STATE_UNSPECIFIED
}

func (x *DeadLetterInfo) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *DeadLetterInfo) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *DeadLetterInfo) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

// 用户通道偏好与免打扰设置（notification_dnd_pref 表投影）
type DndPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`                                                                              // 用户 ID
	MutedChannels []Channel              `protobuf:"varint,2,rep,packed,name=muted_channels,json=mutedChannels,proto3,enum=notification.v1.Channel" json:"muted_channels,omitempty"` // 已关闭的通道（不在列表内表示允许）
	QuietStart    string                 `protobuf:"bytes,3,opt,name=quiet_start,json=quietStart,proto3" json:"quiet_start,omitempty"`                                               // 免打扰开始时间 HH:MM（本地时区）
	QuietEnd      string                 `protobuf:"bytes,4,opt,name=quiet_end,json=quietEnd,proto3" json:"quiet_end,omitempty"`                                                     // 免打扰结束时间 HH:MM（支持跨天，如 22:00-08:00）
	Timezone      string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`                                                                     // IANA 时区名，例如 Asia/Shanghai
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                                      // 免打扰总开关
	Ctime         int64                  `protobuf:"varint,7,opt,name=ctime,proto3" json:"ctime,omitempty"`                                                                          // 创建时间（Unix 秒）
	Mtime         int64                  `protobuf:"varint,8,opt,name=mtime,proto3" json:"mtime,omitempty"`                                                                          // 修改时间（Unix 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DndPreference) Reset() {
	*x = DndPreference{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DndPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DndPreference) ProtoMessage() {}

func (x *DndPreference) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DndPreference.ProtoReflect.Descriptor instead.
func (*DndPreference) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *DndPreference) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *DndPreference) GetMutedChannels() []Channel {
	if x != nil {
		return x.MutedChannels
	}
	return nil
}

func (x *DndPreference) GetQuietStart() string {
	if x != nil {
		return x.QuietStart
	}
	return ""
}

func (x *DndPreference) GetQuietEnd() string {
	if x != nil {
		return x.QuietEnd
	}
	return ""
}

func (x *DndPreference) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *DndPreference) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DndPreference) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *DndPreference) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

type SendNotificationReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recipients      []*Recipient           `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`                                                                                                         // 接收人列表（1..200，超出拒绝，避免批量放大）
	Channel         Channel                `protobuf:"varint,2,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`                                                                                 // 通道
	TemplateCode    string                 `protobuf:"bytes,3,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`                                                                                 // 模板码（必须为已发布版本）
	TemplateParams  map[string]string      `protobuf:"bytes,4,rep,name=template_params,json=templateParams,proto3" json:"template_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 模板变量（禁止放手机号/身份证等明文敏感值）
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`                                                                           // 调用方幂等键；同 key 重复调用不产生新任务
	BizKey          string                 `protobuf:"bytes,6,opt,name=biz_key,json=bizKey,proto3" json:"biz_key,omitempty"`                                                                                                   // 业务唯一键（落库唯一索引，跨实例去重）
	Priority        Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=notification.v1.Priority" json:"priority,omitempty"`                                                                              // 优先级
	ExpireAt        int64                  `protobuf:"varint,8,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`                                                                                            // 过期时间（Unix 秒）；0 表示不过期，过期任务不再投递
	TraceId         string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                                                                                // 调用方 trace_id
	DefaultLanguage Language               `protobuf:"varint,10,opt,name=default_language,json=defaultLanguage,proto3,enum=notification.v1.Language" json:"default_language,omitempty"`                                        // 请求级默认语言；接收人未指定语言时回落此值，再回落全局默认
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendNotificationReq) Reset() {
	*x = SendNotificationReq{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationReq) ProtoMessage() {}

func (x *SendNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationReq.ProtoReflect.Descriptor instead.
func (*SendNotificationReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *SendNotificationReq) GetRecipients() []*Recipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendNotificationReq) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *SendNotificationReq) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SendNotificationReq) GetTemplateParams() map[string]string {
	if x != nil {
		return x.TemplateParams
	}
	return nil
}

func (x *SendNotificationReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendNotificationReq) GetBizKey() string {
	if x != nil {
		return x.BizKey
	}
	return ""
}

func (x *SendNotificationReq) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *SendNotificationReq) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *SendNotificationReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SendNotificationReq) GetDefaultLanguage() Language {
	if x != nil {
		return x.DefaultLanguage
	}
	return Language_LANGUAGE_UNSPECIFIED
}

type SendNotificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*DeliveryInfo        `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`  // 每个接收人一条投递记录
	Suppressed    int32                  `protobuf:"varint,2,opt,name=suppressed,proto3" json:"suppressed,omitempty"` // 被免打扰/频控拦截的数量
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`   // biz_key 是否命中已存在的任务（幂等回放）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationReply) Reset() {
	*x = SendNotificationReply{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationReply) ProtoMessage() {}

func (x *SendNotificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationReply.ProtoReflect.Descriptor instead.
func (*SendNotificationReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *SendNotificationReply) GetDeliveries() []*DeliveryInfo {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *SendNotificationReply) GetSuppressed() int32 {
	if x != nil {
		return x.Suppressed
	}
	return 0
}

func (x *SendNotificationReply) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type RenderTemplateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Channel        Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`                                                                                 // 通道
	TemplateCode   string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`                                                                                 // 模板码
	Version        int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                                                                                                              // 指定版本；0 表示使用当前已发布版本
	Language       Language               `protobuf:"varint,4,opt,name=language,proto3,enum=notification.v1.Language" json:"language,omitempty"`                                                                              // 语言
	TemplateParams map[string]string      `protobuf:"bytes,5,rep,name=template_params,json=templateParams,proto3" json:"template_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 模板变量
	Operator       string                 `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`                                                                                                             // 预览操作人（必填，供审计）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenderTemplateReq) Reset() {
	*x = RenderTemplateReq{}
	mi := &file_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderTemplateReq) ProtoMessage() {}

func (x *RenderTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderTemplateReq.ProtoReflect.Descriptor instead.
func (*RenderTemplateReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{8}
}

func (x *RenderTemplateReq) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *RenderTemplateReq) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *RenderTemplateReq) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RenderTemplateReq) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *RenderTemplateReq) GetTemplateParams() map[string]string {
	if x != nil {
		return x.TemplateParams
	}
	return nil
}

func (x *RenderTemplateReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type RenderTemplateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                      // 渲染后标题
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                        // 渲染后正文
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                                 // 实际使用的模板版本
	Language      Language               `protobuf:"varint,4,opt,name=language,proto3,enum=notification.v1.Language" json:"language,omitempty"` // 实际使用的语言
	MissingVars   []string               `protobuf:"bytes,5,rep,name=missing_vars,json=missingVars,proto3" json:"missing_vars,omitempty"`       // 缺失变量名（非空即渲染被拒绝）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderTemplateReply) Reset() {
	*x = RenderTemplateReply{}
	mi := &file_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderTemplateReply) ProtoMessage() {}

func (x *RenderTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderTemplateReply.ProtoReflect.Descriptor instead.
func (*RenderTemplateReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{9}
}

func (x *RenderTemplateReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RenderTemplateReply) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RenderTemplateReply) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RenderTemplateReply) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *RenderTemplateReply) GetMissingVars() []string {
	if x != nil {
		return x.MissingVars
	}
	return nil
}

type UpsertTemplateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateCode  string                 `protobuf:"bytes,1,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`    // 模板码
	Channel       Channel                `protobuf:"varint,2,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`    // 通道
	Language      Language               `protobuf:"varint,3,opt,name=language,proto3,enum=notification.v1.Language" json:"language,omitempty"` // 语言
	TitleTpl      string                 `protobuf:"bytes,4,opt,name=title_tpl,json=titleTpl,proto3" json:"title_tpl,omitempty"`                // 标题模板
	BodyTpl       string                 `protobuf:"bytes,5,opt,name=body_tpl,json=bodyTpl,proto3" json:"body_tpl,omitempty"`                   // 正文模板
	Operator      string                 `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`                                // 操作人（必填）
	Publish       bool                   `protobuf:"varint,7,opt,name=publish,proto3" json:"publish,omitempty"`                                 // true 时直接发布为新版本；false 保存为草稿
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTemplateReq) Reset() {
	*x = UpsertTemplateReq{}
	mi := &file_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTemplateReq) ProtoMessage() {}

func (x *UpsertTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTemplateReq.ProtoReflect.Descriptor instead.
func (*UpsertTemplateReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertTemplateReq) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *UpsertTemplateReq) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *UpsertTemplateReq) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *UpsertTemplateReq) GetTitleTpl() string {
	if x != nil {
		return x.TitleTpl
	}
	return ""
}

func (x *UpsertTemplateReq) GetBodyTpl() string {
	if x != nil {
		return x.BodyTpl
	}
	return ""
}

func (x *UpsertTemplateReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *UpsertTemplateReq) GetPublish() bool {
	if x != nil {
		return x.Publish
	}
	return false
}

type UpsertTemplateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *TemplateInfo          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"` // 落库后的模板（含 version 与 state）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTemplateReply) Reset() {
	*x = UpsertTemplateReply{}
	mi := &file_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTemplateReply) ProtoMessage() {}

func (x *UpsertTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTemplateReply.ProtoReflect.Descriptor instead.
func (*UpsertTemplateReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertTemplateReply) GetTemplate() *TemplateInfo {
	if x != nil {
		return x.Template
	}
	return nil
}

type ListTemplatesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateCode  string                 `protobuf:"bytes,1,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`    // 可选过滤
	Channel       Channel                `protobuf:"varint,2,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`    // 可选过滤（CHANNEL_UNSPECIFIED 表示不过滤）
	Language      Language               `protobuf:"varint,3,opt,name=language,proto3,enum=notification.v1.Language" json:"language,omitempty"` // 可选过滤
	State         TemplateState          `protobuf:"varint,4,opt,name=state,proto3,enum=notification.v1.TemplateState" json:"state,omitempty"`  // 可选过滤
	Pn            int32                  `protobuf:"varint,5,opt,name=pn,proto3" json:"pn,omitempty"`                                           // 页码，从 1 开始
	Ps            int32                  `protobuf:"varint,6,opt,name=ps,proto3" json:"ps,omitempty"`                                           // 每页大小，最大 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesReq) Reset() {
	*x = ListTemplatesReq{}
	mi := &file_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesReq) ProtoMessage() {}

func (x *ListTemplatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesReq.ProtoReflect.Descriptor instead.
func (*ListTemplatesReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{12}
}

func (x *ListTemplatesReq) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *ListTemplatesReq) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ListTemplatesReq) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *ListTemplatesReq) GetState() TemplateState {
	if x != nil {
		return x.State
	}
	return TemplateState_TEMPLATE_STATE_UNSPECIFIED
}

func (x *ListTemplatesReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *ListTemplatesReq) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

type ListTemplatesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateInfo        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"` // 模板列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`        // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesReply) Reset() {
	*x = ListTemplatesReply{}
	mi := &file_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesReply) ProtoMessage() {}

func (x *ListTemplatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesReply.ProtoReflect.Descriptor instead.
func (*ListTemplatesReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{13}
}

func (x *ListTemplatesReply) GetTemplates() []*TemplateInfo {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PublishTemplateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateCode  string                 `protobuf:"bytes,1,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`    // 模板码
	Channel       Channel                `protobuf:"varint,2,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`    // 通道
	Language      Language               `protobuf:"varint,3,opt,name=language,proto3,enum=notification.v1.Language" json:"language,omitempty"` // 语言
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                                 // 要发布的草稿版本
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`                                // 操作人（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTemplateReq) Reset() {
	*x = PublishTemplateReq{}
	mi := &file_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTemplateReq) ProtoMessage() {}

func (x *PublishTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTemplateReq.ProtoReflect.Descriptor instead.
func (*PublishTemplateReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{14}
}

func (x *PublishTemplateReq) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *PublishTemplateReq) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *PublishTemplateReq) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *PublishTemplateReq) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PublishTemplateReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type PublishTemplateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *TemplateInfo          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"` // 发布后的模板
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTemplateReply) Reset() {
	*x = PublishTemplateReply{}
	mi := &file_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTemplateReply) ProtoMessage() {}

func (x *PublishTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTemplateReply.ProtoReflect.Descriptor instead.
func (*PublishTemplateReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{15}
}

func (x *PublishTemplateReply) GetTemplate() *TemplateInfo {
	if x != nil {
		return x.Template
	}
	return nil
}

type GetDeliveryStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"` // 投递任务 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusReq) Reset() {
	*x = GetDeliveryStatusReq{}
	mi := &file_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusReq) ProtoMessage() {}

func (x *GetDeliveryStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusReq.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{16}
}

func (x *GetDeliveryStatusReq) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

type GetDeliveryStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliveryInfo          `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"` // 投递记录（未找到时为默认值，found=false）
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`      // 是否存在
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusReply) Reset() {
	*x = GetDeliveryStatusReply{}
	mi := &file_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusReply) ProtoMessage() {}

func (x *GetDeliveryStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusReply.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{17}
}

func (x *GetDeliveryStatusReply) GetDelivery() *DeliveryInfo {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *GetDeliveryStatusReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListDeliveriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`                                        // 可选：按接收人过滤
	Channel       Channel                `protobuf:"varint,2,opt,name=channel,proto3,enum=notification.v1.Channel" json:"channel,omitempty"`   // 可选过滤
	State         DeliveryState          `protobuf:"varint,3,opt,name=state,proto3,enum=notification.v1.DeliveryState" json:"state,omitempty"` // 可选过滤
	BizKey        string                 `protobuf:"bytes,4,opt,name=biz_key,json=bizKey,proto3" json:"biz_key,omitempty"`                     // 可选：按幂等键精确查询
	StartCtime    int64                  `protobuf:"varint,5,opt,name=start_ctime,json=startCtime,proto3" json:"start_ctime,omitempty"`        // 可选：创建时间下界（Unix 秒）
	EndCtime      int64                  `protobuf:"varint,6,opt,name=end_ctime,json=endCtime,proto3" json:"end_ctime,omitempty"`              // 可选：创建时间上界（Unix 秒）
	Pn            int32                  `protobuf:"varint,7,opt,name=pn,proto3" json:"pn,omitempty"`                                          // 页码，从 1 开始
	Ps            int32                  `protobuf:"varint,8,opt,name=ps,proto3" json:"ps,omitempty"`                                          // 每页大小，最大 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesReq) Reset() {
	*x = ListDeliveriesReq{}
	mi := &file_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesReq) ProtoMessage() {}

func (x *ListDeliveriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesReq.ProtoReflect.Descriptor instead.
func (*ListDeliveriesReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{18}
}

func (x *ListDeliveriesReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ListDeliveriesReq) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ListDeliveriesReq) GetState() DeliveryState {
	if x != nil {
		return x.State
	}
	return DeliveryState_DELIVERY_STATE_UNSPECIFIED
}

func (x *ListDeliveriesReq) GetBizKey() string {
	if x != nil {
		return x.BizKey
	}
	return ""
}

func (x *ListDeliveriesReq) GetStartCtime() int64 {
	if x != nil {
		return x.StartCtime
	}
	return 0
}

func (x *ListDeliveriesReq) GetEndCtime() int64 {
	if x != nil {
		return x.EndCtime
	}
	return 0
}

func (x *ListDeliveriesReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *ListDeliveriesReq) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

type ListDeliveriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*DeliveryInfo        `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"` // 投递记录
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`          // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesReply) Reset() {
	*x = ListDeliveriesReply{}
	mi := &file_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesReply) ProtoMessage() {}

func (x *ListDeliveriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesReply.ProtoReflect.Descriptor instead.
func (*ListDeliveriesReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{19}
}

func (x *ListDeliveriesReply) GetDeliveries() []*DeliveryInfo {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *ListDeliveriesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListDeadLettersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                    // 可选：按事件 ID 精确查询
	State         DeadLetterState        `protobuf:"varint,2,opt,name=state,proto3,enum=notification.v1.DeadLetterState" json:"state,omitempty"` // 可选过滤
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`                                       // 可选过滤
	Pn            int32                  `protobuf:"varint,4,opt,name=pn,proto3" json:"pn,omitempty"`                                            // 页码，从 1 开始
	Ps            int32                  `protobuf:"varint,5,opt,name=ps,proto3" json:"ps,omitempty"`                                            // 每页大小，最大 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLettersReq) Reset() {
	*x = ListDeadLettersReq{}
	mi := &file_notification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLettersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLettersReq) ProtoMessage() {}

func (x *ListDeadLettersReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLettersReq.ProtoReflect.Descriptor instead.
func (*ListDeadLettersReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{20}
}

func (x *ListDeadLettersReq) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ListDeadLettersReq) GetState() DeadLetterState {
	if x != nil {
		return x.State
	}
	return DeadLetterState_DEAD_LETTER_STATE_UNSPECIFIED
}

func (x *ListDeadLettersReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ListDeadLettersReq) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *ListDeadLettersReq) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

type ListDeadLettersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadLetters   []*DeadLetterInfo      `protobuf:"bytes,1,rep,name=dead_letters,json=deadLetters,proto3" json:"dead_letters,omitempty"` // 死信列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                               // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLettersReply) Reset() {
	*x = ListDeadLettersReply{}
	mi := &file_notification_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLettersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLettersReply) ProtoMessage() {}

func (x *ListDeadLettersReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLettersReply.ProtoReflect.Descriptor instead.
func (*ListDeadLettersReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{21}
}

func (x *ListDeadLettersReply) GetDeadLetters() []*DeadLetterInfo {
	if x != nil {
		return x.DeadLetters
	}
	return nil
}

func (x *ListDeadLettersReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RetryDeadLetterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // 死信记录 ID
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // 操作人（必填，写审计）
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`     // 重投原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDeadLetterReq) Reset() {
	*x = RetryDeadLetterReq{}
	mi := &file_notification_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDeadLetterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDeadLetterReq) ProtoMessage() {}

func (x *RetryDeadLetterReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDeadLetterReq.ProtoReflect.Descriptor instead.
func (*RetryDeadLetterReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{22}
}

func (x *RetryDeadLetterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetryDeadLetterReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *RetryDeadLetterReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RetryDeadLetterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryIds   []string               `protobuf:"bytes,1,rep,name=delivery_ids,json=deliveryIds,proto3" json:"delivery_ids,omitempty"` // 重投产生的投递任务 ID
	Retried       int32                  `protobuf:"varint,2,opt,name=retried,proto3" json:"retried,omitempty"`                           // 重投数量
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                            // 结果说明（脱敏）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDeadLetterReply) Reset() {
	*x = RetryDeadLetterReply{}
	mi := &file_notification_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDeadLetterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDeadLetterReply) ProtoMessage() {}

func (x *RetryDeadLetterReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDeadLetterReply.ProtoReflect.Descriptor instead.
func (*RetryDeadLetterReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{23}
}

func (x *RetryDeadLetterReply) GetDeliveryIds() []string {
	if x != nil {
		return x.DeliveryIds
	}
	return nil
}

func (x *RetryDeadLetterReply) GetRetried() int32 {
	if x != nil {
		return x.Retried
	}
	return 0
}

func (x *RetryDeadLetterReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateDndPreferenceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`                                                                              // 用户 ID
	MutedChannels []Channel              `protobuf:"varint,2,rep,packed,name=muted_channels,json=mutedChannels,proto3,enum=notification.v1.Channel" json:"muted_channels,omitempty"` // 关闭的通道列表（全量覆盖语义）
	QuietStart    string                 `protobuf:"bytes,3,opt,name=quiet_start,json=quietStart,proto3" json:"quiet_start,omitempty"`                                               // HH:MM，空串表示不设置免打扰时段
	QuietEnd      string                 `protobuf:"bytes,4,opt,name=quiet_end,json=quietEnd,proto3" json:"quiet_end,omitempty"`                                                     // HH:MM，与 quiet_start 成对
	Timezone      string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`                                                                     // IANA 时区名，空串表示使用全局默认
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                                      // 免打扰总开关
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDndPreferenceReq) Reset() {
	*x = UpdateDndPreferenceReq{}
	mi := &file_notification_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDndPreferenceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDndPreferenceReq) ProtoMessage() {}

func (x *UpdateDndPreferenceReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDndPreferenceReq.ProtoReflect.Descriptor instead.
func (*UpdateDndPreferenceReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateDndPreferenceReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UpdateDndPreferenceReq) GetMutedChannels() []Channel {
	if x != nil {
		return x.MutedChannels
	}
	return nil
}

func (x *UpdateDndPreferenceReq) GetQuietStart() string {
	if x != nil {
		return x.QuietStart
	}
	return ""
}

func (x *UpdateDndPreferenceReq) GetQuietEnd() string {
	if x != nil {
		return x.QuietEnd
	}
	return ""
}

func (x *UpdateDndPreferenceReq) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UpdateDndPreferenceReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateDndPreferenceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *DndPreference         `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"` // 落库后的偏好
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDndPreferenceReply) Reset() {
	*x = UpdateDndPreferenceReply{}
	mi := &file_notification_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDndPreferenceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDndPreferenceReply) ProtoMessage() {}

func (x *UpdateDndPreferenceReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDndPreferenceReply.ProtoReflect.Descriptor instead.
func (*UpdateDndPreferenceReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateDndPreferenceReply) GetPreference() *DndPreference {
	if x != nil {
		return x.Preference
	}
	return nil
}

type GetDndPreferenceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"` // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDndPreferenceReq) Reset() {
	*x = GetDndPreferenceReq{}
	mi := &file_notification_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDndPreferenceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDndPreferenceReq) ProtoMessage() {}

func (x *GetDndPreferenceReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDndPreferenceReq.ProtoReflect.Descriptor instead.
func (*GetDndPreferenceReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{26}
}

func (x *GetDndPreferenceReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type GetDndPreferenceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *DndPreference         `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"` // 偏好（未设置过时返回默认值）
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`          // 是否已存在设置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDndPreferenceReply) Reset() {
	*x = GetDndPreferenceReply{}
	mi := &file_notification_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDndPreferenceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDndPreferenceReply) ProtoMessage() {}

func (x *GetDndPreferenceReply) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDndPreferenceReply.ProtoReflect.Descriptor instead.
func (*GetDndPreferenceReply) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{27}
}

func (x *GetDndPreferenceReply) GetPreference() *DndPreference {
	if x != nil {
		return x.Preference
	}
	return nil
}

func (x *GetDndPreferenceReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x0fnotification.v1\"\f\n" +
	"\n" +
	"EmptyReply\"\x90\x01\n" +
	"\tRecipient\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x02 \x01(\tR\ttargetRef\x125\n" +
	"\blanguage\x18\x03 \x01(\x0e2\x19.notification.v1.LanguageR\blanguage\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"\xfe\x02\n" +
	"\fTemplateInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x122\n" +
	"\achannel\x18\x03 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x125\n" +
	"\blanguage\x18\x04 \x01(\x0e2\x19.notification.v1.LanguageR\blanguage\x12\x1b\n" +
	"\ttitle_tpl\x18\x05 \x01(\tR\btitleTpl\x12\x19\n" +
	"\bbody_tpl\x18\x06 \x01(\tR\abodyTpl\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x124\n" +
	"\x05state\x18\b \x01(\x0e2\x1e.notification.v1.TemplateStateR\x05state\x12\x1a\n" +
	"\boperator\x18\t \x01(\tR\boperator\x12\x14\n" +
	"\x05ctime\x18\n" +
	" \x01(\x03R\x05ctime\x12\x14\n" +
	"\x05mtime\x18\v \x01(\x03R\x05mtime\"\x9b\x05\n" +
	"\fDeliveryInfo\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x17\n" +
	"\abiz_key\x18\x02 \x01(\tR\x06bizKey\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\x03R\x03mid\x122\n" +
	"\achannel\x18\x04 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x12#\n" +
	"\rtemplate_code\x18\x05 \x01(\tR\ftemplateCode\x12)\n" +
	"\x10template_version\x18\x06 \x01(\x05R\x0ftemplateVersion\x12\x1d\n" +
	"\n" +
	"target_ref\x18\a \x01(\tR\ttargetRef\x12%\n" +
	"\x0epayload_digest\x18\b \x01(\tR\rpayloadDigest\x124\n" +
	"\x05state\x18\t \x01(\x0e2\x1e.notification.v1.DeliveryStateR\x05state\x12\x1a\n" +
	"\bprovider\x18\n" +
	" \x01(\tR\bprovider\x12&\n" +
	"\x0fprovider_msg_id\x18\v \x01(\tR\rproviderMsgId\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\x12\"\n" +
	"\rnext_retry_at\x18\r \x01(\x03R\vnextRetryAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x0e \x01(\tR\tlastError\x12\x17\n" +
	"\asent_at\x18\x0f \x01(\x03R\x06sentAt\x12\x1b\n" +
	"\texpire_at\x18\x10 \x01(\x03R\bexpireAt\x12\x1a\n" +
	"\bpriority\x18\x11 \x01(\x05R\bpriority\x12\x19\n" +
	"\btrace_id\x18\x12 \x01(\tR\atraceId\x12\x14\n" +
	"\x05ctime\x18\x13 \x01(\x03R\x05ctime\x12\x14\n" +
	"\x05mtime\x18\x14 \x01(\x03R\x05mtime\"\xaf\x02\n" +
	"\x0eDeadLetterInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12%\n" +
	"\x0epayload_digest\x18\x05 \x01(\tR\rpayloadDigest\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x126\n" +
	"\x05state\x18\a \x01(\x0e2 .notification.v1.DeadLetterStateR\x05state\x12\x1a\n" +
	"\boperator\x18\b \x01(\tR\boperator\x12\x14\n" +
	"\x05ctime\x18\t \x01(\x03R\x05ctime\x12\x14\n" +
	"\x05mtime\x18\n" +
	" \x01(\x03R\x05mtime\"\x82\x02\n" +
	"\rDndPreference\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12?\n" +
	"\x0emuted_channels\x18\x02 \x03(\x0e2\x18.notification.v1.ChannelR\rmutedChannels\x12\x1f\n" +
	"\vquiet_start\x18\x03 \x01(\tR\n" +
	"quietStart\x12\x1b\n" +
	"\tquiet_end\x18\x04 \x01(\tR\bquietEnd\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x14\n" +
	"\x05ctime\x18\a \x01(\x03R\x05ctime\x12\x14\n" +
	"\x05mtime\x18\b \x01(\x03R\x05mtime\"\xc7\x04\n" +
	"\x13SendNotificationReq\x12:\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x1a.notification.v1.RecipientR\n" +
	"recipients\x122\n" +
	"\achannel\x18\x02 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x12#\n" +
	"\rtemplate_code\x18\x03 \x01(\tR\ftemplateCode\x12a\n" +
	"\x0ftemplate_params\x18\x04 \x03(\v28.notification.v1.SendNotificationReq.TemplateParamsEntryR\x0etemplateParams\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x17\n" +
	"\abiz_key\x18\x06 \x01(\tR\x06bizKey\x125\n" +
	"\bpriority\x18\a \x01(\x0e2\x19.notification.v1.PriorityR\bpriority\x12\x1b\n" +
	"\texpire_at\x18\b \x01(\x03R\bexpireAt\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12D\n" +
	"\x10default_language\x18\n" +
	" \x01(\x0e2\x19.notification.v1.LanguageR\x0fdefaultLanguage\x1aA\n" +
	"\x13TemplateParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\x15SendNotificationReply\x12=\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x1d.notification.v1.DeliveryInfoR\n" +
	"deliveries\x12\x1e\n" +
	"\n" +
	"suppressed\x18\x02 \x01(\x05R\n" +
	"suppressed\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\"\xfd\x02\n" +
	"\x11RenderTemplateReq\x122\n" +
	"\achannel\x18\x01 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x125\n" +
	"\blanguage\x18\x04 \x01(\x0e2\x19.notification.v1.LanguageR\blanguage\x12_\n" +
	"\x0ftemplate_params\x18\x05 \x03(\v26.notification.v1.RenderTemplateReq.TemplateParamsEntryR\x0etemplateParams\x12\x1a\n" +
	"\boperator\x18\x06 \x01(\tR\boperator\x1aA\n" +
	"\x13TemplateParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x13RenderTemplateReply\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x125\n" +
	"\blanguage\x18\x04 \x01(\x0e2\x19.notification.v1.LanguageR\blanguage\x12!\n" +
	"\fmissing_vars\x18\x05 \x03(\tR\vmissingVars\"\x91\x02\n" +
	"\x11UpsertTemplateReq\x12#\n" +
	"\rtemplate_code\x18\x01 \x01(\tR\ftemplateCode\x122\n" +
	"\achannel\x18\x02 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x125\n" +
	"\blanguage\x18\x03 \x01(\x0e2\x19.notification.v1.LanguageR\blanguage\x12\x1b\n" +
	"\ttitle_tpl\x18\x04 \x01(\tR\btitleTpl\x12\x19\n" +
	"\bbody_tpl\x18\x05 \x01(\tR\abodyTpl\x12\x1a\n" +
	"\boperator\x18\x06 \x01(\tR\boperator\x12\x18\n" +
	"\apublish\x18\a \x01(\bR\apublish\"P\n" +
	"\x13UpsertTemplateReply\x129\n" +
	"\btemplate\x18\x01 \x01(\v2\x1d.notification.v1.TemplateInfoR\btemplate\"\xf8\x01\n" +
	"\x10ListTemplatesReq\x12#\n" +
	"\rtemplate_code\x18\x01 \x01(\tR\ftemplateCode\x122\n" +
	"\achannel\x18\x02 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x125\n" +
	"\blanguage\x18\x03 \x01(\x0e2\x19.notification.v1.LanguageR\blanguage\x124\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1e.notification.v1.TemplateStateR\x05state\x12\x0e\n" +
	"\x02pn\x18\x05 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\x06 \x01(\x05R\x02ps\"g\n" +
	"\x12ListTemplatesReply\x12;\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1d.notification.v1.TemplateInfoR\ttemplates\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xda\x01\n" +
	"\x12PublishTemplateReq\x12#\n" +
	"\rtemplate_code\x18\x01 \x01(\tR\ftemplateCode\x122\n" +
	"\achannel\x18\x02 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x125\n" +
	"\blanguage\x18\x03 \x01(\x0e2\x19.notification.v1.LanguageR\blanguage\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\"Q\n" +
	"\x14PublishTemplateReply\x129\n" +
	"\btemplate\x18\x01 \x01(\v2\x1d.notification.v1.TemplateInfoR\btemplate\"7\n" +
	"\x14GetDeliveryStatusReq\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\"i\n" +
	"\x16GetDeliveryStatusReply\x129\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1d.notification.v1.DeliveryInfoR\bdelivery\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x86\x02\n" +
	"\x11ListDeliveriesReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x122\n" +
	"\achannel\x18\x02 \x01(\x0e2\x18.notification.v1.ChannelR\achannel\x124\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1e.notification.v1.DeliveryStateR\x05state\x12\x17\n" +
	"\abiz_key\x18\x04 \x01(\tR\x06bizKey\x12\x1f\n" +
	"\vstart_ctime\x18\x05 \x01(\x03R\n" +
	"startCtime\x12\x1b\n" +
	"\tend_ctime\x18\x06 \x01(\x03R\bendCtime\x12\x0e\n" +
	"\x02pn\x18\a \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\b \x01(\x05R\x02ps\"j\n" +
	"\x13ListDeliveriesReply\x12=\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x1d.notification.v1.DeliveryInfoR\n" +
	"deliveries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x9d\x01\n" +
	"\x12ListDeadLettersReq\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x126\n" +
	"\x05state\x18\x02 \x01(\x0e2 .notification.v1.DeadLetterStateR\x05state\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02pn\x18\x04 \x01(\x05R\x02pn\x12\x0e\n" +
	"\x02ps\x18\x05 \x01(\x05R\x02ps\"p\n" +
	"\x14ListDeadLettersReply\x12B\n" +
	"\fdead_letters\x18\x01 \x03(\v2\x1f.notification.v1.DeadLetterInfoR\vdeadLetters\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"X\n" +
	"\x12RetryDeadLetterReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"m\n" +
	"\x14RetryDeadLetterReply\x12!\n" +
	"\fdelivery_ids\x18\x01 \x03(\tR\vdeliveryIds\x12\x18\n" +
	"\aretried\x18\x02 \x01(\x05R\aretried\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xdf\x01\n" +
	"\x16UpdateDndPreferenceReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12?\n" +
	"\x0emuted_channels\x18\x02 \x03(\x0e2\x18.notification.v1.ChannelR\rmutedChannels\x12\x1f\n" +
	"\vquiet_start\x18\x03 \x01(\tR\n" +
	"quietStart\x12\x1b\n" +
	"\tquiet_end\x18\x04 \x01(\tR\bquietEnd\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"Z\n" +
	"\x18UpdateDndPreferenceReply\x12>\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2\x1e.notification.v1.DndPreferenceR\n" +
	"preference\"'\n" +
	"\x13GetDndPreferenceReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\"m\n" +
	"\x15GetDndPreferenceReply\x12>\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2\x1e.notification.v1.DndPreferenceR\n" +
	"preference\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found*X\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCHANNEL_PUSH\x10\x01\x12\x0f\n" +
	"\vCHANNEL_SMS\x10\x02\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x03*]\n" +
	"\bLanguage\x12\x18\n" +
	"\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLANGUAGE_ZH_CN\x10\x01\x12\x12\n" +
	"\x0eLANGUAGE_ZH_TW\x10\x02\x12\x0f\n" +
	"\vLANGUAGE_EN\x10\x03*\xb4\x01\n" +
	"\rDeliveryState\x12\x1e\n" +
	"\x1aDELIVERY_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DELIVERY_PENDING\x10\x01\x12\x11\n" +
	"\rDELIVERY_SENT\x10\x02\x12\x13\n" +
	"\x0fDELIVERY_FAILED\x10\x03\x12\x12\n" +
	"\x0eDELIVERY_RETRY\x10\x04\x12\x18\n" +
	"\x14DELIVERY_DEAD_LETTER\x10\x05\x12\x17\n" +
	"\x13DELIVERY_SUPPRESSED\x10\x06*\x83\x01\n" +
	"\rTemplateState\x12\x1e\n" +
	"\x1aTEMPLATE_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TEMPLATE_STATE_DRAFT\x10\x01\x12\x1c\n" +
	"\x18TEMPLATE_STATE_PUBLISHED\x10\x02\x12\x1a\n" +
	"\x16TEMPLATE_STATE_OFFLINE\x10\x03*\x90\x01\n" +
	"\n" +
	"EventState\x12\x1b\n" +
	"\x17EVENT_STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_RECEIVED\x10\x01\x12\x14\n" +
	"\x10EVENT_PROCESSING\x10\x02\x12\x13\n" +
	"\x0fEVENT_SUCCEEDED\x10\x03\x12\x0f\n" +
	"\vEVENT_RETRY\x10\x04\x12\x15\n" +
	"\x11EVENT_DEAD_LETTER\x10\x05*\x81\x01\n" +
	"\x0fDeadLetterState\x12!\n" +
	"\x1dDEAD_LETTER_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEAD_LETTER_PENDING\x10\x01\x12\x17\n" +
	"\x13DEAD_LETTER_RETRIED\x10\x02\x12\x19\n" +
	"\x15DEAD_LETTER_DISCARDED\x10\x03*^\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x032\xac\b\n" +
	"\fNotification\x12`\n" +
	"\x10SendNotification\x12$.notification.v1.SendNotificationReq\x1a&.notification.v1.SendNotificationReply\x12Z\n" +
	"\x0eRenderTemplate\x12\".notification.v1.RenderTemplateReq\x1a$.notification.v1.RenderTemplateReply\x12Z\n" +
	"\x0eUpsertTemplate\x12\".notification.v1.UpsertTemplateReq\x1a$.notification.v1.UpsertTemplateReply\x12W\n" +
	"\rListTemplates\x12!.notification.v1.ListTemplatesReq\x1a#.notification.v1.ListTemplatesReply\x12]\n" +
	"\x0fPublishTemplate\x12#.notification.v1.PublishTemplateReq\x1a%.notification.v1.PublishTemplateReply\x12c\n" +
	"\x11GetDeliveryStatus\x12%.notification.v1.GetDeliveryStatusReq\x1a'.notification.v1.GetDeliveryStatusReply\x12Z\n" +
	"\x0eListDeliveries\x12\".notification.v1.ListDeliveriesReq\x1a$.notification.v1.ListDeliveriesReply\x12]\n" +
	"\x0fListDeadLetters\x12#.notification.v1.ListDeadLettersReq\x1a%.notification.v1.ListDeadLettersReply\x12]\n" +
	"\x0fRetryDeadLetter\x12#.notification.v1.RetryDeadLetterReq\x1a%.notification.v1.RetryDeadLetterReply\x12i\n" +
	"\x13UpdateDndPreference\x12'.notification.v1.UpdateDndPreferenceReq\x1a).notification.v1.UpdateDndPreferenceReply\x12`\n" +
	"\x10GetDndPreference\x12$.notification.v1.GetDndPreferenceReq\x1a&.notification.v1.GetDndPreferenceReplyB$Z\"go-video/services/notification/rpcb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_notification_proto_goTypes = []any{
	(Channel)(0),                     // 0: notification.v1.Channel
	(Language)(0),                    // 1: notification.v1.Language
	(DeliveryState)(0),               // 2: notification.v1.DeliveryState
	(TemplateState)(0),               // 3: notification.v1.TemplateState
	(EventState)(0),                  // 4: notification.v1.EventState
	(DeadLetterState)(0),             // 5: notification.v1.DeadLetterState
	(Priority)(0),                    // 6: notification.v1.Priority
	(*EmptyReply)(nil),               // 7: notification.v1.EmptyReply
	(*Recipient)(nil),                // 8: notification.v1.Recipient
	(*TemplateInfo)(nil),             // 9: notification.v1.TemplateInfo
	(*DeliveryInfo)(nil),             // 10: notification.v1.DeliveryInfo
	(*DeadLetterInfo)(nil),           // 11: notification.v1.DeadLetterInfo
	(*DndPreference)(nil),            // 12: notification.v1.DndPreference
	(*SendNotificationReq)(nil),      // 13: notification.v1.SendNotificationReq
	(*SendNotificationReply)(nil),    // 14: notification.v1.SendNotificationReply
	(*RenderTemplateReq)(nil),        // 15: notification.v1.RenderTemplateReq
	(*RenderTemplateReply)(nil),      // 16: notification.v1.RenderTemplateReply
	(*UpsertTemplateReq)(nil),        // 17: notification.v1.UpsertTemplateReq
	(*UpsertTemplateReply)(nil),      // 18: notification.v1.UpsertTemplateReply
	(*ListTemplatesReq)(nil),         // 19: notification.v1.ListTemplatesReq
	(*ListTemplatesReply)(nil),       // 20: notification.v1.ListTemplatesReply
	(*PublishTemplateReq)(nil),       // 21: notification.v1.PublishTemplateReq
	(*PublishTemplateReply)(nil),     // 22: notification.v1.PublishTemplateReply
	(*GetDeliveryStatusReq)(nil),     // 23: notification.v1.GetDeliveryStatusReq
	(*GetDeliveryStatusReply)(nil),   // 24: notification.v1.GetDeliveryStatusReply
	(*ListDeliveriesReq)(nil),        // 25: notification.v1.ListDeliveriesReq
	(*ListDeliveriesReply)(nil),      // 26: notification.v1.ListDeliveriesReply
	(*ListDeadLettersReq)(nil),       // 27: notification.v1.ListDeadLettersReq
	(*ListDeadLettersReply)(nil),     // 28: notification.v1.ListDeadLettersReply
	(*RetryDeadLetterReq)(nil),       // 29: notification.v1.RetryDeadLetterReq
	(*RetryDeadLetterReply)(nil),     // 30: notification.v1.RetryDeadLetterReply
	(*UpdateDndPreferenceReq)(nil),   // 31: notification.v1.UpdateDndPreferenceReq
	(*UpdateDndPreferenceReply)(nil), // 32: notification.v1.UpdateDndPreferenceReply
	(*GetDndPreferenceReq)(nil),      // 33: notification.v1.GetDndPreferenceReq
	(*GetDndPreferenceReply)(nil),    // 34: notification.v1.GetDndPreferenceReply
	nil,                              // 35: notification.v1.SendNotificationReq.TemplateParamsEntry
	nil,                              // 36: notification.v1.RenderTemplateReq.TemplateParamsEntry
}
var file_notification_proto_depIdxs = []int32{
	1,  // 0: notification.v1.Recipient.language:type_name -> notification.v1.Language
	0,  // 1: notification.v1.TemplateInfo.channel:type_name -> notification.v1.Channel
	1,  // 2: notification.v1.TemplateInfo.language:type_name -> notification.v1.Language
	3,  // 3: notification.v1.TemplateInfo.state:type_name -> notification.v1.TemplateState
	0,  // 4: notification.v1.DeliveryInfo.channel:type_name -> notification.v1.Channel
	2,  // 5: notification.v1.DeliveryInfo.state:type_name -> notification.v1.DeliveryState
	5,  // 6: notification.v1.DeadLetterInfo.state:type_name -> notification.v1.DeadLetterState
	0,  // 7: notification.v1.DndPreference.muted_channels:type_name -> notification.v1.Channel
	8,  // 8: notification.v1.SendNotificationReq.recipients:type_name -> notification.v1.Recipient
	0,  // 9: notification.v1.SendNotificationReq.channel:type_name -> notification.v1.Channel
	35, // 10: notification.v1.SendNotificationReq.template_params:type_name -> notification.v1.SendNotificationReq.TemplateParamsEntry
	6,  // 11: notification.v1.SendNotificationReq.priority:type_name -> notification.v1.Priority
	1,  // 12: notification.v1.SendNotificationReq.default_language:type_name -> notification.v1.Language
	10, // 13: notification.v1.SendNotificationReply.deliveries:type_name -> notification.v1.DeliveryInfo
	0,  // 14: notification.v1.RenderTemplateReq.channel:type_name -> notification.v1.Channel
	1,  // 15: notification.v1.RenderTemplateReq.language:type_name -> notification.v1.Language
	36, // 16: notification.v1.RenderTemplateReq.template_params:type_name -> notification.v1.RenderTemplateReq.TemplateParamsEntry
	1,  // 17: notification.v1.RenderTemplateReply.language:type_name -> notification.v1.Language
	0,  // 18: notification.v1.UpsertTemplateReq.channel:type_name -> notification.v1.Channel
	1,  // 19: notification.v1.UpsertTemplateReq.language:type_name -> notification.v1.Language
	9,  // 20: notification.v1.UpsertTemplateReply.template:type_name -> notification.v1.TemplateInfo
	0,  // 21: notification.v1.ListTemplatesReq.channel:type_name -> notification.v1.Channel
	1,  // 22: notification.v1.ListTemplatesReq.language:type_name -> notification.v1.Language
	3,  // 23: notification.v1.ListTemplatesReq.state:type_name -> notification.v1.TemplateState
	9,  // 24: notification.v1.ListTemplatesReply.templates:type_name -> notification.v1.TemplateInfo
	0,  // 25: notification.v1.PublishTemplateReq.channel:type_name -> notification.v1.Channel
	1,  // 26: notification.v1.PublishTemplateReq.language:type_name -> notification.v1.Language
	9,  // 27: notification.v1.PublishTemplateReply.template:type_name -> notification.v1.TemplateInfo
	10, // 28: notification.v1.GetDeliveryStatusReply.delivery:type_name -> notification.v1.DeliveryInfo
	0,  // 29: notification.v1.ListDeliveriesReq.channel:type_name -> notification.v1.Channel
	2,  // 30: notification.v1.ListDeliveriesReq.state:type_name -> notification.v1.DeliveryState
	10, // 31: notification.v1.ListDeliveriesReply.deliveries:type_name -> notification.v1.DeliveryInfo
	5,  // 32: notification.v1.ListDeadLettersReq.state:type_name -> notification.v1.DeadLetterState
	11, // 33: notification.v1.ListDeadLettersReply.dead_letters:type_name -> notification.v1.DeadLetterInfo
	0,  // 34: notification.v1.UpdateDndPreferenceReq.muted_channels:type_name -> notification.v1.Channel
	12, // 35: notification.v1.UpdateDndPreferenceReply.preference:type_name -> notification.v1.DndPreference
	12, // 36: notification.v1.GetDndPreferenceReply.preference:type_name -> notification.v1.DndPreference
	13, // 37: notification.v1.Notification.SendNotification:input_type -> notification.v1.SendNotificationReq
	15, // 38: notification.v1.Notification.RenderTemplate:input_type -> notification.v1.RenderTemplateReq
	17, // 39: notification.v1.Notification.UpsertTemplate:input_type -> notification.v1.UpsertTemplateReq
	19, // 40: notification.v1.Notification.ListTemplates:input_type -> notification.v1.ListTemplatesReq
	21, // 41: notification.v1.Notification.PublishTemplate:input_type -> notification.v1.PublishTemplateReq
	23, // 42: notification.v1.Notification.GetDeliveryStatus:input_type -> notification.v1.GetDeliveryStatusReq
	25, // 43: notification.v1.Notification.ListDeliveries:input_type -> notification.v1.ListDeliveriesReq
	27, // 44: notification.v1.Notification.ListDeadLetters:input_type -> notification.v1.ListDeadLettersReq
	29, // 45: notification.v1.Notification.RetryDeadLetter:input_type -> notification.v1.RetryDeadLetterReq
	31, // 46: notification.v1.Notification.UpdateDndPreference:input_type -> notification.v1.UpdateDndPreferenceReq
	33, // 47: notification.v1.Notification.GetDndPreference:input_type -> notification.v1.GetDndPreferenceReq
	14, // 48: notification.v1.Notification.SendNotification:output_type -> notification.v1.SendNotificationReply
	16, // 49: notification.v1.Notification.RenderTemplate:output_type -> notification.v1.RenderTemplateReply
	18, // 50: notification.v1.Notification.UpsertTemplate:output_type -> notification.v1.UpsertTemplateReply
	20, // 51: notification.v1.Notification.ListTemplates:output_type -> notification.v1.ListTemplatesReply
	22, // 52: notification.v1.Notification.PublishTemplate:output_type -> notification.v1.PublishTemplateReply
	24, // 53: notification.v1.Notification.GetDeliveryStatus:output_type -> notification.v1.GetDeliveryStatusReply
	26, // 54: notification.v1.Notification.ListDeliveries:output_type -> notification.v1.ListDeliveriesReply
	28, // 55: notification.v1.Notification.ListDeadLetters:output_type -> notification.v1.ListDeadLettersReply
	30, // 56: notification.v1.Notification.RetryDeadLetter:output_type -> notification.v1.RetryDeadLetterReply
	32, // 57: notification.v1.Notification.UpdateDndPreference:output_type -> notification.v1.UpdateDndPreferenceReply
	34, // 58: notification.v1.Notification.GetDndPreference:output_type -> notification.v1.GetDndPreferenceReply
	48, // [48:59] is the sub-list for method output_type
	37, // [37:48] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
