// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"go-video/gateway/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 管理后台健康检查，返回服务存活状态
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: healthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 接收资料变更通知，失效缓存
				Method:  http.MethodPost,
				Path:    "/cache/clear",
				Handler: cacheClearHandler(serverCtx),
			},
			{
				// 失效指定用户的缓存
				Method:  http.MethodGet,
				Path:    "/cache/del",
				Handler: cacheDelHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/account"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 设置经验值（仅运营）
				Method:  http.MethodPost,
				Path:    "/exp/set",
				Handler: expSetHandler(serverCtx),
			},
			{
				// 增加经验值
				Method:  http.MethodPost,
				Path:    "/exp/update",
				Handler: expUpdateHandler(serverCtx),
			},
			{
				// 撤销节操值变更
				Method:  http.MethodPost,
				Path:    "/moral/undo",
				Handler: moralUndoHandler(serverCtx),
			},
			{
				// 变更单个用户节操值
				Method:  http.MethodPost,
				Path:    "/moral/update",
				Handler: moralUpdateHandler(serverCtx),
			},
			{
				// 批量变更节操值
				Method:  http.MethodPost,
				Path:    "/morals/update",
				Handler: moralsUpdateHandler(serverCtx),
			},
			{
				// 添加用户属性变更审核
				Method:  http.MethodPost,
				Path:    "/property/review/add",
				Handler: propertyReviewHandler(serverCtx),
			},
			{
				// 按证件号批量查询 mid
				Method:  http.MethodGet,
				Path:    "/realname/mid/by/card",
				Handler: realnameMidByCardHandler(serverCtx),
			},
			{
				// 查询脱敏实名信息
				Method:  http.MethodGet,
				Path:    "/realname/stripped/info",
				Handler: realnameStrippedHandler(serverCtx),
			},
			{
				// 查询用户登录日志
				Method:  http.MethodGet,
				Path:    "/web/login/log",
				Handler: loginLogHandler(serverCtx),
			},
		},
		rest.WithPrefix("/x/member"),
	)
}
