// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: spm.proto

package server

import (
	"context"

	"go-video/services/spm/internal/logic"
	"go-video/services/spm/internal/svc"
	"go-video/services/spm/rpc"
)

type SpmServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedSpmServer
}

func NewSpmServer(svcCtx *svc.ServiceContext) *SpmServer {
	return &SpmServer{
		svcCtx: svcCtx,
	}
}

// 读取单主体单口径单窗口的指标值
func (s *SpmServer) GetMetric(ctx context.Context, in *rpc.GetMetricReq) (*rpc.GetMetricReply, error) {
	l := logic.NewGetMetricLogic(ctx, s.svcCtx)
	return l.GetMetric(in)
}

// 批量读取主体的一组指标/多个窗口（单次上限 50 口径 × 30 窗口）
func (s *SpmServer) BatchGetMetrics(ctx context.Context, in *rpc.BatchGetMetricsReq) (*rpc.BatchGetMetricsReply, error) {
	l := logic.NewBatchGetMetricsLogic(ctx, s.svcCtx)
	return l.BatchGetMetrics(in)
}

// 热度榜投影（只读，按指标值倒序分页）
func (s *SpmServer) ListHotSubjects(ctx context.Context, in *rpc.ListHotSubjectsReq) (*rpc.ListHotSubjectsReply, error) {
	l := logic.NewListHotSubjectsLogic(ctx, s.svcCtx)
	return l.ListHotSubjects(in)
}

// 用户兴趣画像（脱敏权重，不返回行为明细）
func (s *SpmServer) GetUserInterest(ctx context.Context, in *rpc.GetUserInterestReq) (*rpc.GetUserInterestReply, error) {
	l := logic.NewGetUserInterestLogic(ctx, s.svcCtx)
	return l.GetUserInterest(in)
}

// 留存曲线
func (s *SpmServer) GetRetention(ctx context.Context, in *rpc.GetRetentionReq) (*rpc.GetRetentionReply, error) {
	l := logic.NewGetRetentionLogic(ctx, s.svcCtx)
	return l.GetRetention(in)
}

// 聚合链路写回窗口指标（幂等覆盖，来源受 MetricSource 白名单约束）
func (s *SpmServer) WriteMetricWindow(ctx context.Context, in *rpc.WriteMetricWindowReq) (*rpc.WriteMetricWindowReply, error) {
	l := logic.NewWriteMetricWindowLogic(ctx, s.svcCtx)
	return l.WriteMetricWindow(in)
}

// 从事实表重算指标（计数/指标漂移的修复入口，派生 JOB_TYPE_RECOMPUTE 作业）
func (s *SpmServer) RecomputeMetrics(ctx context.Context, in *rpc.RecomputeMetricsReq) (*rpc.RecomputeMetricsReply, error) {
	l := logic.NewRecomputeMetricsLogic(ctx, s.svcCtx)
	return l.RecomputeMetrics(in)
}

// 登记指标口径新版本（已存在版本不可变）
func (s *SpmServer) UpsertMetricDefinition(ctx context.Context, in *rpc.UpsertMetricDefinitionReq) (*rpc.UpsertMetricDefinitionReply, error) {
	l := logic.NewUpsertMetricDefinitionLogic(ctx, s.svcCtx)
	return l.UpsertMetricDefinition(in)
}

// 变更口径状态（DRAFT/ACTIVE/RETIRED），不删除历史口径
func (s *SpmServer) UpdateMetricDefinitionState(ctx context.Context, in *rpc.UpdateMetricDefinitionStateReq) (*rpc.UpdateMetricDefinitionStateReply, error) {
	l := logic.NewUpdateMetricDefinitionStateLogic(ctx, s.svcCtx)
	return l.UpdateMetricDefinitionState(in)
}

// 查询单个口径
func (s *SpmServer) GetMetricDefinition(ctx context.Context, in *rpc.GetMetricDefinitionReq) (*rpc.GetMetricDefinitionReply, error) {
	l := logic.NewGetMetricDefinitionLogic(ctx, s.svcCtx)
	return l.GetMetricDefinition(in)
}

// 口径列表（分页）
func (s *SpmServer) ListMetricDefinitions(ctx context.Context, in *rpc.ListMetricDefinitionsReq) (*rpc.ListMetricDefinitionsReply, error) {
	l := logic.NewListMetricDefinitionsLogic(ctx, s.svcCtx)
	return l.ListMetricDefinitions(in)
}

// 提交实时/离线聚合作业（request_id 幂等）
func (s *SpmServer) SubmitAggregationJob(ctx context.Context, in *rpc.SubmitAggregationJobReq) (*rpc.SubmitAggregationJobReply, error) {
	l := logic.NewSubmitAggregationJobLogic(ctx, s.svcCtx)
	return l.SubmitAggregationJob(in)
}

// 查询作业（按 job_id 或 request_id）
func (s *SpmServer) GetAggregationJob(ctx context.Context, in *rpc.GetAggregationJobReq) (*rpc.GetAggregationJobReply, error) {
	l := logic.NewGetAggregationJobLogic(ctx, s.svcCtx)
	return l.GetAggregationJob(in)
}

// 作业列表（分页）
func (s *SpmServer) ListAggregationJobs(ctx context.Context, in *rpc.ListAggregationJobsReq) (*rpc.ListAggregationJobsReply, error) {
	l := logic.NewListAggregationJobsLogic(ctx, s.svcCtx)
	return l.ListAggregationJobs(in)
}

// 消费状态汇总（位点与堆积）
func (s *SpmServer) ListConsumerState(ctx context.Context, in *rpc.ListConsumerStateReq) (*rpc.ListConsumerStateReply, error) {
	l := logic.NewListConsumerStateLogic(ctx, s.svcCtx)
	return l.ListConsumerState(in)
}

// 死信留档查询（只读；重放属于 services/cron 的待接线项）
func (s *SpmServer) ListDeadLetters(ctx context.Context, in *rpc.ListDeadLettersReq) (*rpc.ListDeadLettersReply, error) {
	l := logic.NewListDeadLettersLogic(ctx, s.svcCtx)
	return l.ListDeadLetters(in)
}
