// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: riskcontrol.proto

package server

import (
	"context"

	"go-video/services/risk-control/internal/logic"
	"go-video/services/risk-control/internal/svc"
	"go-video/services/risk-control/rpc"
)

type RiskControlServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedRiskControlServer
}

func NewRiskControlServer(svcCtx *svc.ServiceContext) *RiskControlServer {
	return &RiskControlServer{
		svcCtx: svcCtx,
	}
}

// 同步裁决一次受保护动作（名单 → 处罚 → 规则 → 降级）。
func (s *RiskControlServer) CheckAction(ctx context.Context, in *rpc.CheckActionReq) (*rpc.CheckActionReply, error) {
	l := logic.NewCheckActionLogic(ctx, s.svcCtx)
	return l.CheckAction(in)
}

// 行为上报，写 Redis 滑窗计数供 CheckAction 评估；不做 SPM 广告分析。
func (s *RiskControlServer) ReportAction(ctx context.Context, in *rpc.ReportActionReq) (*rpc.ReportActionReply, error) {
	l := logic.NewReportActionLogic(ctx, s.svcCtx)
	return l.ReportAction(in)
}

// 查询设备画像。
func (s *RiskControlServer) GetDeviceProfile(ctx context.Context, in *rpc.GetDeviceProfileReq) (*rpc.GetDeviceProfileReply, error) {
	l := logic.NewGetDeviceProfileLogic(ctx, s.svcCtx)
	return l.GetDeviceProfile(in)
}

// 写入/更新设备画像与设备-账号关联。
func (s *RiskControlServer) UpsertDeviceProfile(ctx context.Context, in *rpc.UpsertDeviceProfileReq) (*rpc.UpsertDeviceProfileReply, error) {
	l := logic.NewUpsertDeviceProfileLogic(ctx, s.svcCtx)
	return l.UpsertDeviceProfile(in)
}

// 运营/审核下发处罚。
func (s *RiskControlServer) ApplyPunishment(ctx context.Context, in *rpc.ApplyPunishmentReq) (*rpc.ApplyPunishmentReply, error) {
	l := logic.NewApplyPunishmentLogic(ctx, s.svcCtx)
	return l.ApplyPunishment(in)
}

// 解除处罚（幂等，已终态返回当前状态）。
func (s *RiskControlServer) LiftPunishment(ctx context.Context, in *rpc.LiftPunishmentReq) (*rpc.LiftPunishmentReply, error) {
	l := logic.NewLiftPunishmentLogic(ctx, s.svcCtx)
	return l.LiftPunishment(in)
}

// 分页查询处罚。
func (s *RiskControlServer) ListPunishments(ctx context.Context, in *rpc.ListPunishmentsReq) (*rpc.ListPunishmentsReply, error) {
	l := logic.NewListPunishmentsLogic(ctx, s.svcCtx)
	return l.ListPunishments(in)
}

// 新增/更新风控规则（版本递增，operator 必填）。
func (s *RiskControlServer) UpsertRule(ctx context.Context, in *rpc.UpsertRuleReq) (*rpc.UpsertRuleReply, error) {
	l := logic.NewUpsertRuleLogic(ctx, s.svcCtx)
	return l.UpsertRule(in)
}

// 分页查询风控规则。
func (s *RiskControlServer) ListRules(ctx context.Context, in *rpc.ListRulesReq) (*rpc.ListRulesReply, error) {
	l := logic.NewListRulesLogic(ctx, s.svcCtx)
	return l.ListRules(in)
}

// 新增/更新名单条目。
func (s *RiskControlServer) UpsertListEntry(ctx context.Context, in *rpc.UpsertListEntryReq) (*rpc.UpsertListEntryReply, error) {
	l := logic.NewUpsertListEntryLogic(ctx, s.svcCtx)
	return l.UpsertListEntry(in)
}

// 分页查询名单条目。
func (s *RiskControlServer) GetListEntries(ctx context.Context, in *rpc.GetListEntriesReq) (*rpc.GetListEntriesReply, error) {
	l := logic.NewGetListEntriesLogic(ctx, s.svcCtx)
	return l.GetListEntries(in)
}
