// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: opsconfig.proto

package server

import (
	"context"

	"go-video/services/ops-config/internal/logic"
	"go-video/services/ops-config/internal/svc"
	"go-video/services/ops-config/rpc"
)

type OpsConfigServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedOpsConfigServer
}

func NewOpsConfigServer(svcCtx *svc.ServiceContext) *OpsConfigServer {
	return &OpsConfigServer{
		svcCtx: svcCtx,
	}
}

// 运行时解析单个配置（命中灰度规则，返回建议 TTL）
func (s *OpsConfigServer) ResolveConfig(ctx context.Context, in *rpc.ResolveConfigReq) (*rpc.ResolveConfigReply, error) {
	l := logic.NewResolveConfigLogic(ctx, s.svcCtx)
	return l.ResolveConfig(in)
}

// 批量解析（网关聚合用，最多 50 键）
func (s *OpsConfigServer) BatchResolveConfig(ctx context.Context, in *rpc.BatchResolveConfigReq) (*rpc.BatchResolveConfigReply, error) {
	l := logic.NewBatchResolveConfigLogic(ctx, s.svcCtx)
	return l.BatchResolveConfig(in)
}

// 后台分页列出配置项
func (s *OpsConfigServer) ListConfigs(ctx context.Context, in *rpc.ListConfigsReq) (*rpc.ListConfigsReply, error) {
	l := logic.NewListConfigsLogic(ctx, s.svcCtx)
	return l.ListConfigs(in)
}

// 发布新版本（乐观锁 + 幂等 + 可选一并挂灰度规则）
func (s *OpsConfigServer) PublishConfig(ctx context.Context, in *rpc.PublishConfigReq) (*rpc.PublishConfigReply, error) {
	l := logic.NewPublishConfigLogic(ctx, s.svcCtx)
	return l.PublishConfig(in)
}

// 回滚到历史版本（生成新版本，不改写历史）
func (s *OpsConfigServer) RollbackConfig(ctx context.Context, in *rpc.RollbackConfigReq) (*rpc.RollbackConfigReply, error) {
	l := logic.NewRollbackConfigLogic(ctx, s.svcCtx)
	return l.RollbackConfig(in)
}

// 版本历史分页
func (s *OpsConfigServer) ListConfigVersions(ctx context.Context, in *rpc.ListConfigVersionsReq) (*rpc.ListConfigVersionsReply, error) {
	l := logic.NewListConfigVersionsLogic(ctx, s.svcCtx)
	return l.ListConfigVersions(in)
}

// 新建/更新灰度规则（按 config_id + version + name upsert）
func (s *OpsConfigServer) SaveRolloutRule(ctx context.Context, in *rpc.SaveRolloutRuleReq) (*rpc.SaveRolloutRuleReply, error) {
	l := logic.NewSaveRolloutRuleLogic(ctx, s.svcCtx)
	return l.SaveRolloutRule(in)
}

// 灰度规则分页查询
func (s *OpsConfigServer) ListRolloutRules(ctx context.Context, in *rpc.ListRolloutRulesReq) (*rpc.ListRolloutRulesReply, error) {
	l := logic.NewListRolloutRulesLogic(ctx, s.svcCtx)
	return l.ListRolloutRules(in)
}

// 启停灰度规则（软状态切换，保留放量证据）
func (s *OpsConfigServer) SetRolloutRuleState(ctx context.Context, in *rpc.SetRolloutRuleStateReq) (*rpc.SetRolloutRuleStateReply, error) {
	l := logic.NewSetRolloutRuleStateLogic(ctx, s.svcCtx)
	return l.SetRolloutRuleState(in)
}

// 新建/更新专题（zone_ids/tag_ids 只存引用）
func (s *OpsConfigServer) SaveTopic(ctx context.Context, in *rpc.SaveTopicReq) (*rpc.SaveTopicReply, error) {
	l := logic.NewSaveTopicLogic(ctx, s.svcCtx)
	return l.SaveTopic(in)
}

// 专题详情（可带条目）
func (s *OpsConfigServer) GetTopic(ctx context.Context, in *rpc.GetTopicReq) (*rpc.GetTopicReply, error) {
	l := logic.NewGetTopicLogic(ctx, s.svcCtx)
	return l.GetTopic(in)
}

// 专题分页查询
func (s *OpsConfigServer) ListTopics(ctx context.Context, in *rpc.ListTopicsReq) (*rpc.ListTopicsReply, error) {
	l := logic.NewListTopicsLogic(ctx, s.svcCtx)
	return l.ListTopics(in)
}

// 全量覆盖专题条目
func (s *OpsConfigServer) SaveTopicItems(ctx context.Context, in *rpc.SaveTopicItemsReq) (*rpc.SaveTopicItemsReply, error) {
	l := logic.NewSaveTopicItemsLogic(ctx, s.svcCtx)
	return l.SaveTopicItems(in)
}

// 新建/更新推荐位定义
func (s *OpsConfigServer) SaveSlot(ctx context.Context, in *rpc.SaveSlotReq) (*rpc.SaveSlotReply, error) {
	l := logic.NewSaveSlotLogic(ctx, s.svcCtx)
	return l.SaveSlot(in)
}

// 推荐位分页查询
func (s *OpsConfigServer) ListSlots(ctx context.Context, in *rpc.ListSlotsReq) (*rpc.ListSlotsReply, error) {
	l := logic.NewListSlotsLogic(ctx, s.svcCtx)
	return l.ListSlots(in)
}

// 全量覆盖坑位条目与排期
func (s *OpsConfigServer) SaveSlotItems(ctx context.Context, in *rpc.SaveSlotItemsReq) (*rpc.SaveSlotItemsReply, error) {
	l := logic.NewSaveSlotItemsLogic(ctx, s.svcCtx)
	return l.SaveSlotItems(in)
}

// 运行时坑位视图（按端/版本/mid/时间过滤，只回引用）
func (s *OpsConfigServer) ResolveSlot(ctx context.Context, in *rpc.ResolveSlotReq) (*rpc.ResolveSlotReply, error) {
	l := logic.NewResolveSlotLogic(ctx, s.svcCtx)
	return l.ResolveSlot(in)
}

// 新建/更新客户端开关（按 switch_key + platform upsert）
func (s *OpsConfigServer) SaveClientSwitch(ctx context.Context, in *rpc.SaveClientSwitchReq) (*rpc.SaveClientSwitchReply, error) {
	l := logic.NewSaveClientSwitchLogic(ctx, s.svcCtx)
	return l.SaveClientSwitch(in)
}

// 客户端开关分页查询
func (s *OpsConfigServer) ListClientSwitches(ctx context.Context, in *rpc.ListClientSwitchesReq) (*rpc.ListClientSwitchesReply, error) {
	l := logic.NewListClientSwitchesLogic(ctx, s.svcCtx)
	return l.ListClientSwitches(in)
}

// 主动失效运行时缓存（必写审计）
func (s *OpsConfigServer) RefreshCache(ctx context.Context, in *rpc.RefreshCacheReq) (*rpc.RefreshCacheReply, error) {
	l := logic.NewRefreshCacheLogic(ctx, s.svcCtx)
	return l.RefreshCache(in)
}
