// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.9
// source: privatemessage.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivateMessage_GetOrCreateConversation_FullMethodName = "/privatemessage.v1.PrivateMessage/GetOrCreateConversation"
	PrivateMessage_SendMessage_FullMethodName             = "/privatemessage.v1.PrivateMessage/SendMessage"
	PrivateMessage_ListConversations_FullMethodName       = "/privatemessage.v1.PrivateMessage/ListConversations"
	PrivateMessage_ListMessages_FullMethodName            = "/privatemessage.v1.PrivateMessage/ListMessages"
	PrivateMessage_MarkRead_FullMethodName                = "/privatemessage.v1.PrivateMessage/MarkRead"
	PrivateMessage_GetUnreadSummary_FullMethodName        = "/privatemessage.v1.PrivateMessage/GetUnreadSummary"
	PrivateMessage_WithdrawMessage_FullMethodName         = "/privatemessage.v1.PrivateMessage/WithdrawMessage"
	PrivateMessage_HideConversation_FullMethodName        = "/privatemessage.v1.PrivateMessage/HideConversation"
	PrivateMessage_UpdateUserSetting_FullMethodName       = "/privatemessage.v1.PrivateMessage/UpdateUserSetting"
	PrivateMessage_GetUserSetting_FullMethodName          = "/privatemessage.v1.PrivateMessage/GetUserSetting"
	PrivateMessage_ReportMessage_FullMethodName           = "/privatemessage.v1.PrivateMessage/ReportMessage"
	PrivateMessage_ListReports_FullMethodName             = "/privatemessage.v1.PrivateMessage/ListReports"
	PrivateMessage_HandleReport_FullMethodName            = "/privatemessage.v1.PrivateMessage/HandleReport"
	PrivateMessage_ApplyModerationVerdict_FullMethodName  = "/privatemessage.v1.PrivateMessage/ApplyModerationVerdict"
	PrivateMessage_PurgeExpiredMessages_FullMethodName    = "/privatemessage.v1.PrivateMessage/PurgeExpiredMessages"
)

// PrivateMessageClient is the client API for PrivateMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PrivateMessage 私信服务。
// 方法名表达领域动作，不暴露数据库 CRUD（docs/api-and-events.md §1.1）。
type PrivateMessageClient interface {
	// 定位或创建单聊会话（pair_key 唯一索引保证幂等）。
	GetOrCreateConversation(ctx context.Context, in *GetOrCreateConversationReq, opts ...grpc.CallOption) (*GetOrCreateConversationReply, error)
	// 发送私信（client_msg_id 幂等 + 门禁顺序见 SendMessageReq 注释）。
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageReply, error)
	// 会话列表（cursor 分页，黑名单/风控/隐藏会话在查询层过滤）。
	ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsReply, error)
	// 会话内消息分页（conversation_id + seq 游标，禁止 offset 全表扫）。
	ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesReply, error)
	// 前移已读游标（幂等，只前进不回退）。
	MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*MarkReadReply, error)
	// 未读汇总（投影，可重算）。
	GetUnreadSummary(ctx context.Context, in *GetUnreadSummaryReq, opts ...grpc.CallOption) (*GetUnreadSummaryReply, error)
	// 撤回消息（只改可见性标记 + 写审计）。
	WithdrawMessage(ctx context.Context, in *WithdrawMessageReq, opts ...grpc.CallOption) (*WithdrawMessageReply, error)
	// 本方隐藏/恢复会话。
	HideConversation(ctx context.Context, in *HideConversationReq, opts ...grpc.CallOption) (*EmptyReply, error)
	// 更新反骚扰偏好。
	UpdateUserSetting(ctx context.Context, in *UpdateUserSettingReq, opts ...grpc.CallOption) (*UserSettingInfo, error)
	// 查询反骚扰偏好。
	GetUserSetting(ctx context.Context, in *GetUserSettingReq, opts ...grpc.CallOption) (*UserSettingInfo, error)
	// 举报私信（写本域举报事实并向 moderation 送审）。
	ReportMessage(ctx context.Context, in *ReportMessageReq, opts ...grpc.CallOption) (*ReportMessageReply, error)
	// 运营侧举报分页。
	ListReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ListReportsReply, error)
	// 运营侧举报处置（幂等键防重复处置）。
	HandleReport(ctx context.Context, in *HandleReportReq, opts ...grpc.CallOption) (*HandleReportReply, error)
	// 审核结论回写（唯一写结论入口，按 event_id 去重）。
	ApplyModerationVerdict(ctx context.Context, in *ApplyModerationVerdictReq, opts ...grpc.CallOption) (*ApplyModerationVerdictReply, error)
	// 留存到期清理（正文物理删除，审计保留）。
	PurgeExpiredMessages(ctx context.Context, in *PurgeExpiredMessagesReq, opts ...grpc.CallOption) (*PurgeExpiredMessagesReply, error)
}

type privateMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivateMessageClient(cc grpc.ClientConnInterface) PrivateMessageClient {
	return &privateMessageClient{cc}
}

func (c *privateMessageClient) GetOrCreateConversation(ctx context.Context, in *GetOrCreateConversationReq, opts ...grpc.CallOption) (*GetOrCreateConversationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrCreateConversationReply)
	err := c.cc.Invoke(ctx, PrivateMessage_GetOrCreateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, PrivateMessage_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsReply)
	err := c.cc.Invoke(ctx, PrivateMessage_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesReply)
	err := c.cc.Invoke(ctx, PrivateMessage_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*MarkReadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadReply)
	err := c.cc.Invoke(ctx, PrivateMessage_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) GetUnreadSummary(ctx context.Context, in *GetUnreadSummaryReq, opts ...grpc.CallOption) (*GetUnreadSummaryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadSummaryReply)
	err := c.cc.Invoke(ctx, PrivateMessage_GetUnreadSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) WithdrawMessage(ctx context.Context, in *WithdrawMessageReq, opts ...grpc.CallOption) (*WithdrawMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawMessageReply)
	err := c.cc.Invoke(ctx, PrivateMessage_WithdrawMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) HideConversation(ctx context.Context, in *HideConversationReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, PrivateMessage_HideConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) UpdateUserSetting(ctx context.Context, in *UpdateUserSettingReq, opts ...grpc.CallOption) (*UserSettingInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSettingInfo)
	err := c.cc.Invoke(ctx, PrivateMessage_UpdateUserSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) GetUserSetting(ctx context.Context, in *GetUserSettingReq, opts ...grpc.CallOption) (*UserSettingInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSettingInfo)
	err := c.cc.Invoke(ctx, PrivateMessage_GetUserSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) ReportMessage(ctx context.Context, in *ReportMessageReq, opts ...grpc.CallOption) (*ReportMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportMessageReply)
	err := c.cc.Invoke(ctx, PrivateMessage_ReportMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) ListReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ListReportsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReportsReply)
	err := c.cc.Invoke(ctx, PrivateMessage_ListReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) HandleReport(ctx context.Context, in *HandleReportReq, opts ...grpc.CallOption) (*HandleReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleReportReply)
	err := c.cc.Invoke(ctx, PrivateMessage_HandleReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) ApplyModerationVerdict(ctx context.Context, in *ApplyModerationVerdictReq, opts ...grpc.CallOption) (*ApplyModerationVerdictReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyModerationVerdictReply)
	err := c.cc.Invoke(ctx, PrivateMessage_ApplyModerationVerdict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateMessageClient) PurgeExpiredMessages(ctx context.Context, in *PurgeExpiredMessagesReq, opts ...grpc.CallOption) (*PurgeExpiredMessagesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeExpiredMessagesReply)
	err := c.cc.Invoke(ctx, PrivateMessage_PurgeExpiredMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivateMessageServer is the server API for PrivateMessage service.
// All implementations must embed UnimplementedPrivateMessageServer
// for forward compatibility.
//
// PrivateMessage 私信服务。
// 方法名表达领域动作，不暴露数据库 CRUD（docs/api-and-events.md §1.1）。
type PrivateMessageServer interface {
	// 定位或创建单聊会话（pair_key 唯一索引保证幂等）。
	GetOrCreateConversation(context.Context, *GetOrCreateConversationReq) (*GetOrCreateConversationReply, error)
	// 发送私信（client_msg_id 幂等 + 门禁顺序见 SendMessageReq 注释）。
	SendMessage(context.Context, *SendMessageReq) (*SendMessageReply, error)
	// 会话列表（cursor 分页，黑名单/风控/隐藏会话在查询层过滤）。
	ListConversations(context.Context, *ListConversationsReq) (*ListConversationsReply, error)
	// 会话内消息分页（conversation_id + seq 游标，禁止 offset 全表扫）。
	ListMessages(context.Context, *ListMessagesReq) (*ListMessagesReply, error)
	// 前移已读游标（幂等，只前进不回退）。
	MarkRead(context.Context, *MarkReadReq) (*MarkReadReply, error)
	// 未读汇总（投影，可重算）。
	GetUnreadSummary(context.Context, *GetUnreadSummaryReq) (*GetUnreadSummaryReply, error)
	// 撤回消息（只改可见性标记 + 写审计）。
	WithdrawMessage(context.Context, *WithdrawMessageReq) (*WithdrawMessageReply, error)
	// 本方隐藏/恢复会话。
	HideConversation(context.Context, *HideConversationReq) (*EmptyReply, error)
	// 更新反骚扰偏好。
	UpdateUserSetting(context.Context, *UpdateUserSettingReq) (*UserSettingInfo, error)
	// 查询反骚扰偏好。
	GetUserSetting(context.Context, *GetUserSettingReq) (*UserSettingInfo, error)
	// 举报私信（写本域举报事实并向 moderation 送审）。
	ReportMessage(context.Context, *ReportMessageReq) (*ReportMessageReply, error)
	// 运营侧举报分页。
	ListReports(context.Context, *ListReportsReq) (*ListReportsReply, error)
	// 运营侧举报处置（幂等键防重复处置）。
	HandleReport(context.Context, *HandleReportReq) (*HandleReportReply, error)
	// 审核结论回写（唯一写结论入口，按 event_id 去重）。
	ApplyModerationVerdict(context.Context, *ApplyModerationVerdictReq) (*ApplyModerationVerdictReply, error)
	// 留存到期清理（正文物理删除，审计保留）。
	PurgeExpiredMessages(context.Context, *PurgeExpiredMessagesReq) (*PurgeExpiredMessagesReply, error)
	mustEmbedUnimplementedPrivateMessageServer()
}

// UnimplementedPrivateMessageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivateMessageServer struct{}

func (UnimplementedPrivateMessageServer) GetOrCreateConversation(context.Context, *GetOrCreateConversationReq) (*GetOrCreateConversationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrCreateConversation not implemented")
}
func (UnimplementedPrivateMessageServer) SendMessage(context.Context, *SendMessageReq) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedPrivateMessageServer) ListConversations(context.Context, *ListConversationsReq) (*ListConversationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedPrivateMessageServer) ListMessages(context.Context, *ListMessagesReq) (*ListMessagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedPrivateMessageServer) MarkRead(context.Context, *MarkReadReq) (*MarkReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedPrivateMessageServer) GetUnreadSummary(context.Context, *GetUnreadSummaryReq) (*GetUnreadSummaryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadSummary not implemented")
}
func (UnimplementedPrivateMessageServer) WithdrawMessage(context.Context, *WithdrawMessageReq) (*WithdrawMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawMessage not implemented")
}
func (UnimplementedPrivateMessageServer) HideConversation(context.Context, *HideConversationReq) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HideConversation not implemented")
}
func (UnimplementedPrivateMessageServer) UpdateUserSetting(context.Context, *UpdateUserSettingReq) (*UserSettingInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserSetting not implemented")
}
func (UnimplementedPrivateMessageServer) GetUserSetting(context.Context, *GetUserSettingReq) (*UserSettingInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSetting not implemented")
}
func (UnimplementedPrivateMessageServer) ReportMessage(context.Context, *ReportMessageReq) (*ReportMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMessage not implemented")
}
func (UnimplementedPrivateMessageServer) ListReports(context.Context, *ListReportsReq) (*ListReportsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReports not implemented")
}
func (UnimplementedPrivateMessageServer) HandleReport(context.Context, *HandleReportReq) (*HandleReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleReport not implemented")
}
func (UnimplementedPrivateMessageServer) ApplyModerationVerdict(context.Context, *ApplyModerationVerdictReq) (*ApplyModerationVerdictReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyModerationVerdict not implemented")
}
func (UnimplementedPrivateMessageServer) PurgeExpiredMessages(context.Context, *PurgeExpiredMessagesReq) (*PurgeExpiredMessagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeExpiredMessages not implemented")
}
func (UnimplementedPrivateMessageServer) mustEmbedUnimplementedPrivateMessageServer() {}
func (UnimplementedPrivateMessageServer) testEmbeddedByValue()                        {}

// UnsafePrivateMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivateMessageServer will
// result in compilation errors.
type UnsafePrivateMessageServer interface {
	mustEmbedUnimplementedPrivateMessageServer()
}

func RegisterPrivateMessageServer(s grpc.ServiceRegistrar, srv PrivateMessageServer) {
	// If the following call pancis, it indicates UnimplementedPrivateMessageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivateMessage_ServiceDesc, srv)
}

func _PrivateMessage_GetOrCreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).GetOrCreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_GetOrCreateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).GetOrCreateConversation(ctx, req.(*GetOrCreateConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).ListConversations(ctx, req.(*ListConversationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).ListMessages(ctx, req.(*ListMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).MarkRead(ctx, req.(*MarkReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_GetUnreadSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).GetUnreadSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_GetUnreadSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).GetUnreadSummary(ctx, req.(*GetUnreadSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_WithdrawMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).WithdrawMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_WithdrawMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).WithdrawMessage(ctx, req.(*WithdrawMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_HideConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HideConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).HideConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_HideConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).HideConversation(ctx, req.(*HideConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_UpdateUserSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserSettingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).UpdateUserSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_UpdateUserSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).UpdateUserSetting(ctx, req.(*UpdateUserSettingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_GetUserSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSettingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).GetUserSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_GetUserSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).GetUserSetting(ctx, req.(*GetUserSettingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_ReportMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).ReportMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_ReportMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).ReportMessage(ctx, req.(*ReportMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_ListReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).ListReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_ListReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).ListReports(ctx, req.(*ListReportsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_HandleReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).HandleReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_HandleReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).HandleReport(ctx, req.(*HandleReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_ApplyModerationVerdict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyModerationVerdictReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).ApplyModerationVerdict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_ApplyModerationVerdict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).ApplyModerationVerdict(ctx, req.(*ApplyModerationVerdictReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateMessage_PurgeExpiredMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeExpiredMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateMessageServer).PurgeExpiredMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateMessage_PurgeExpiredMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateMessageServer).PurgeExpiredMessages(ctx, req.(*PurgeExpiredMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivateMessage_ServiceDesc is the grpc.ServiceDesc for PrivateMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivateMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "privatemessage.v1.PrivateMessage",
	HandlerType: (*PrivateMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrCreateConversation",
			Handler:    _PrivateMessage_GetOrCreateConversation_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _PrivateMessage_SendMessage_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _PrivateMessage_ListConversations_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _PrivateMessage_ListMessages_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _PrivateMessage_MarkRead_Handler,
		},
		{
			MethodName: "GetUnreadSummary",
			Handler:    _PrivateMessage_GetUnreadSummary_Handler,
		},
		{
			MethodName: "WithdrawMessage",
			Handler:    _PrivateMessage_WithdrawMessage_Handler,
		},
		{
			MethodName: "HideConversation",
			Handler:    _PrivateMessage_HideConversation_Handler,
		},
		{
			MethodName: "UpdateUserSetting",
			Handler:    _PrivateMessage_UpdateUserSetting_Handler,
		},
		{
			MethodName: "GetUserSetting",
			Handler:    _PrivateMessage_GetUserSetting_Handler,
		},
		{
			MethodName: "ReportMessage",
			Handler:    _PrivateMessage_ReportMessage_Handler,
		},
		{
			MethodName: "ListReports",
			Handler:    _PrivateMessage_ListReports_Handler,
		},
		{
			MethodName: "HandleReport",
			Handler:    _PrivateMessage_HandleReport_Handler,
		},
		{
			MethodName: "ApplyModerationVerdict",
			Handler:    _PrivateMessage_ApplyModerationVerdict_Handler,
		},
		{
			MethodName: "PurgeExpiredMessages",
			Handler:    _PrivateMessage_PurgeExpiredMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "privatemessage.proto",
}
