// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.9
// source: engagement.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Engagement_Like_FullMethodName        = "/engagement.v1.Engagement/Like"
	Engagement_Stats_FullMethodName       = "/engagement.v1.Engagement/Stats"
	Engagement_MultiStats_FullMethodName  = "/engagement.v1.Engagement/MultiStats"
	Engagement_HasLike_FullMethodName     = "/engagement.v1.Engagement/HasLike"
	Engagement_UserLikes_FullMethodName   = "/engagement.v1.Engagement/UserLikes"
	Engagement_ItemLikes_FullMethodName   = "/engagement.v1.Engagement/ItemLikes"
	Engagement_UpdateCount_FullMethodName = "/engagement.v1.Engagement/UpdateCount"
	Engagement_RawStat_FullMethodName     = "/engagement.v1.Engagement/RawStat"
	Engagement_AddFav_FullMethodName      = "/engagement.v1.Engagement/AddFav"
	Engagement_DelFav_FullMethodName      = "/engagement.v1.Engagement/DelFav"
	Engagement_IsFavored_FullMethodName   = "/engagement.v1.Engagement/IsFavored"
	Engagement_IsFavoreds_FullMethodName  = "/engagement.v1.Engagement/IsFavoreds"
	Engagement_UserFolders_FullMethodName = "/engagement.v1.Engagement/UserFolders"
	Engagement_AddFolder_FullMethodName   = "/engagement.v1.Engagement/AddFolder"
	Engagement_DelFolder_FullMethodName   = "/engagement.v1.Engagement/DelFolder"
	Engagement_AddShare_FullMethodName    = "/engagement.v1.Engagement/AddShare"
)

// EngagementClient is the client API for Engagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Engagement 点赞、收藏、分享社区互动服务。
// 依据 AGENTS.md §1，不实现投币或任何商业化余额；
// 依据 §5，本服务只持有用户行为事实、收藏夹、可重算计数，
// 不复制视频主数据，不直接更新推荐结果。
type EngagementClient interface {
	// 点赞/取消点赞/点踩（幂等：重复请求不重复增加计数）
	Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeReply, error)
	// 批量查询对象计数与当前用户状态
	Stats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*StatsReply, error)
	// 跨业务批量查询计数
	MultiStats(ctx context.Context, in *MultiStatsReq, opts ...grpc.CallOption) (*MultiStatsReply, error)
	// 批量查询用户是否点赞
	HasLike(ctx context.Context, in *HasLikeReq, opts ...grpc.CallOption) (*HasLikeReply, error)
	// 用户的点赞列表（分页）
	UserLikes(ctx context.Context, in *UserLikesReq, opts ...grpc.CallOption) (*UserLikesReply, error)
	// 对象的点赞人列表（分页）
	ItemLikes(ctx context.Context, in *ItemLikesReq, opts ...grpc.CallOption) (*ItemLikesReply, error)
	// 运营修改计数（增量）
	UpdateCount(ctx context.Context, in *UpdateCountReq, opts ...grpc.CallOption) (*EmptyReply, error)
	// 查询原始计数（未修正值）
	RawStat(ctx context.Context, in *RawStatReq, opts ...grpc.CallOption) (*RawStatReply, error)
	// 添加收藏
	AddFav(ctx context.Context, in *AddFavReq, opts ...grpc.CallOption) (*EmptyReply, error)
	// 删除收藏
	DelFav(ctx context.Context, in *DelFavReq, opts ...grpc.CallOption) (*EmptyReply, error)
	// 查询是否已收藏
	IsFavored(ctx context.Context, in *IsFavoredReq, opts ...grpc.CallOption) (*IsFavoredReply, error)
	// 批量查询是否已收藏
	IsFavoreds(ctx context.Context, in *IsFavoredsReq, opts ...grpc.CallOption) (*IsFavoredsReply, error)
	// 用户收藏夹列表
	UserFolders(ctx context.Context, in *UserFoldersReq, opts ...grpc.CallOption) (*UserFoldersReply, error)
	// 创建收藏夹
	AddFolder(ctx context.Context, in *AddFolderReq, opts ...grpc.CallOption) (*AddFolderReply, error)
	// 删除收藏夹
	DelFolder(ctx context.Context, in *DelFolderReq, opts ...grpc.CallOption) (*EmptyReply, error)
	// 记录分享并返回分享数
	AddShare(ctx context.Context, in *AddShareReq, opts ...grpc.CallOption) (*AddShareReply, error)
}

type engagementClient struct {
	cc grpc.ClientConnInterface
}

func NewEngagementClient(cc grpc.ClientConnInterface) EngagementClient {
	return &engagementClient{cc}
}

func (c *engagementClient) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeReply)
	err := c.cc.Invoke(ctx, Engagement_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) Stats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*StatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsReply)
	err := c.cc.Invoke(ctx, Engagement_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) MultiStats(ctx context.Context, in *MultiStatsReq, opts ...grpc.CallOption) (*MultiStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiStatsReply)
	err := c.cc.Invoke(ctx, Engagement_MultiStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) HasLike(ctx context.Context, in *HasLikeReq, opts ...grpc.CallOption) (*HasLikeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasLikeReply)
	err := c.cc.Invoke(ctx, Engagement_HasLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) UserLikes(ctx context.Context, in *UserLikesReq, opts ...grpc.CallOption) (*UserLikesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLikesReply)
	err := c.cc.Invoke(ctx, Engagement_UserLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) ItemLikes(ctx context.Context, in *ItemLikesReq, opts ...grpc.CallOption) (*ItemLikesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemLikesReply)
	err := c.cc.Invoke(ctx, Engagement_ItemLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) UpdateCount(ctx context.Context, in *UpdateCountReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Engagement_UpdateCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) RawStat(ctx context.Context, in *RawStatReq, opts ...grpc.CallOption) (*RawStatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawStatReply)
	err := c.cc.Invoke(ctx, Engagement_RawStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) AddFav(ctx context.Context, in *AddFavReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Engagement_AddFav_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) DelFav(ctx context.Context, in *DelFavReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Engagement_DelFav_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) IsFavored(ctx context.Context, in *IsFavoredReq, opts ...grpc.CallOption) (*IsFavoredReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFavoredReply)
	err := c.cc.Invoke(ctx, Engagement_IsFavored_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) IsFavoreds(ctx context.Context, in *IsFavoredsReq, opts ...grpc.CallOption) (*IsFavoredsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFavoredsReply)
	err := c.cc.Invoke(ctx, Engagement_IsFavoreds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) UserFolders(ctx context.Context, in *UserFoldersReq, opts ...grpc.CallOption) (*UserFoldersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFoldersReply)
	err := c.cc.Invoke(ctx, Engagement_UserFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) AddFolder(ctx context.Context, in *AddFolderReq, opts ...grpc.CallOption) (*AddFolderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFolderReply)
	err := c.cc.Invoke(ctx, Engagement_AddFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) DelFolder(ctx context.Context, in *DelFolderReq, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Engagement_DelFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engagementClient) AddShare(ctx context.Context, in *AddShareReq, opts ...grpc.CallOption) (*AddShareReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddShareReply)
	err := c.cc.Invoke(ctx, Engagement_AddShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngagementServer is the server API for Engagement service.
// All implementations must embed UnimplementedEngagementServer
// for forward compatibility.
//
// Engagement 点赞、收藏、分享社区互动服务。
// 依据 AGENTS.md §1，不实现投币或任何商业化余额；
// 依据 §5，本服务只持有用户行为事实、收藏夹、可重算计数，
// 不复制视频主数据，不直接更新推荐结果。
type EngagementServer interface {
	// 点赞/取消点赞/点踩（幂等：重复请求不重复增加计数）
	Like(context.Context, *LikeReq) (*LikeReply, error)
	// 批量查询对象计数与当前用户状态
	Stats(context.Context, *StatsReq) (*StatsReply, error)
	// 跨业务批量查询计数
	MultiStats(context.Context, *MultiStatsReq) (*MultiStatsReply, error)
	// 批量查询用户是否点赞
	HasLike(context.Context, *HasLikeReq) (*HasLikeReply, error)
	// 用户的点赞列表（分页）
	UserLikes(context.Context, *UserLikesReq) (*UserLikesReply, error)
	// 对象的点赞人列表（分页）
	ItemLikes(context.Context, *ItemLikesReq) (*ItemLikesReply, error)
	// 运营修改计数（增量）
	UpdateCount(context.Context, *UpdateCountReq) (*EmptyReply, error)
	// 查询原始计数（未修正值）
	RawStat(context.Context, *RawStatReq) (*RawStatReply, error)
	// 添加收藏
	AddFav(context.Context, *AddFavReq) (*EmptyReply, error)
	// 删除收藏
	DelFav(context.Context, *DelFavReq) (*EmptyReply, error)
	// 查询是否已收藏
	IsFavored(context.Context, *IsFavoredReq) (*IsFavoredReply, error)
	// 批量查询是否已收藏
	IsFavoreds(context.Context, *IsFavoredsReq) (*IsFavoredsReply, error)
	// 用户收藏夹列表
	UserFolders(context.Context, *UserFoldersReq) (*UserFoldersReply, error)
	// 创建收藏夹
	AddFolder(context.Context, *AddFolderReq) (*AddFolderReply, error)
	// 删除收藏夹
	DelFolder(context.Context, *DelFolderReq) (*EmptyReply, error)
	// 记录分享并返回分享数
	AddShare(context.Context, *AddShareReq) (*AddShareReply, error)
	mustEmbedUnimplementedEngagementServer()
}

// UnimplementedEngagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngagementServer struct{}

func (UnimplementedEngagementServer) Like(context.Context, *LikeReq) (*LikeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedEngagementServer) Stats(context.Context, *StatsReq) (*StatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedEngagementServer) MultiStats(context.Context, *MultiStatsReq) (*MultiStatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiStats not implemented")
}
func (UnimplementedEngagementServer) HasLike(context.Context, *HasLikeReq) (*HasLikeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasLike not implemented")
}
func (UnimplementedEngagementServer) UserLikes(context.Context, *UserLikesReq) (*UserLikesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLikes not implemented")
}
func (UnimplementedEngagementServer) ItemLikes(context.Context, *ItemLikesReq) (*ItemLikesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemLikes not implemented")
}
func (UnimplementedEngagementServer) UpdateCount(context.Context, *UpdateCountReq) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCount not implemented")
}
func (UnimplementedEngagementServer) RawStat(context.Context, *RawStatReq) (*RawStatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawStat not implemented")
}
func (UnimplementedEngagementServer) AddFav(context.Context, *AddFavReq) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFav not implemented")
}
func (UnimplementedEngagementServer) DelFav(context.Context, *DelFavReq) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelFav not implemented")
}
func (UnimplementedEngagementServer) IsFavored(context.Context, *IsFavoredReq) (*IsFavoredReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFavored not implemented")
}
func (UnimplementedEngagementServer) IsFavoreds(context.Context, *IsFavoredsReq) (*IsFavoredsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFavoreds not implemented")
}
func (UnimplementedEngagementServer) UserFolders(context.Context, *UserFoldersReq) (*UserFoldersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserFolders not implemented")
}
func (UnimplementedEngagementServer) AddFolder(context.Context, *AddFolderReq) (*AddFolderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFolder not implemented")
}
func (UnimplementedEngagementServer) DelFolder(context.Context, *DelFolderReq) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelFolder not implemented")
}
func (UnimplementedEngagementServer) AddShare(context.Context, *AddShareReq) (*AddShareReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddShare not implemented")
}
func (UnimplementedEngagementServer) mustEmbedUnimplementedEngagementServer() {}
func (UnimplementedEngagementServer) testEmbeddedByValue()                    {}

// UnsafeEngagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngagementServer will
// result in compilation errors.
type UnsafeEngagementServer interface {
	mustEmbedUnimplementedEngagementServer()
}

func RegisterEngagementServer(s grpc.ServiceRegistrar, srv EngagementServer) {
	// If the following call pancis, it indicates UnimplementedEngagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Engagement_ServiceDesc, srv)
}

func _Engagement_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).Like(ctx, req.(*LikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).Stats(ctx, req.(*StatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_MultiStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).MultiStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_MultiStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).MultiStats(ctx, req.(*MultiStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_HasLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasLikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).HasLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_HasLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).HasLike(ctx, req.(*HasLikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_UserLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLikesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).UserLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_UserLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).UserLikes(ctx, req.(*UserLikesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_ItemLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemLikesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).ItemLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_ItemLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).ItemLikes(ctx, req.(*ItemLikesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_UpdateCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).UpdateCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_UpdateCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).UpdateCount(ctx, req.(*UpdateCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_RawStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawStatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).RawStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_RawStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).RawStat(ctx, req.(*RawStatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_AddFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFavReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).AddFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_AddFav_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).AddFav(ctx, req.(*AddFavReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_DelFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelFavReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).DelFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_DelFav_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).DelFav(ctx, req.(*DelFavReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_IsFavored_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFavoredReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).IsFavored(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_IsFavored_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).IsFavored(ctx, req.(*IsFavoredReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_IsFavoreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFavoredsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).IsFavoreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_IsFavoreds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).IsFavoreds(ctx, req.(*IsFavoredsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_UserFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFoldersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).UserFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_UserFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).UserFolders(ctx, req.(*UserFoldersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_AddFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).AddFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_AddFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).AddFolder(ctx, req.(*AddFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_DelFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).DelFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_DelFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).DelFolder(ctx, req.(*DelFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engagement_AddShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngagementServer).AddShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engagement_AddShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngagementServer).AddShare(ctx, req.(*AddShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Engagement_ServiceDesc is the grpc.ServiceDesc for Engagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Engagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engagement.v1.Engagement",
	HandlerType: (*EngagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Like",
			Handler:    _Engagement_Like_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Engagement_Stats_Handler,
		},
		{
			MethodName: "MultiStats",
			Handler:    _Engagement_MultiStats_Handler,
		},
		{
			MethodName: "HasLike",
			Handler:    _Engagement_HasLike_Handler,
		},
		{
			MethodName: "UserLikes",
			Handler:    _Engagement_UserLikes_Handler,
		},
		{
			MethodName: "ItemLikes",
			Handler:    _Engagement_ItemLikes_Handler,
		},
		{
			MethodName: "UpdateCount",
			Handler:    _Engagement_UpdateCount_Handler,
		},
		{
			MethodName: "RawStat",
			Handler:    _Engagement_RawStat_Handler,
		},
		{
			MethodName: "AddFav",
			Handler:    _Engagement_AddFav_Handler,
		},
		{
			MethodName: "DelFav",
			Handler:    _Engagement_DelFav_Handler,
		},
		{
			MethodName: "IsFavored",
			Handler:    _Engagement_IsFavored_Handler,
		},
		{
			MethodName: "IsFavoreds",
			Handler:    _Engagement_IsFavoreds_Handler,
		},
		{
			MethodName: "UserFolders",
			Handler:    _Engagement_UserFolders_Handler,
		},
		{
			MethodName: "AddFolder",
			Handler:    _Engagement_AddFolder_Handler,
		},
		{
			MethodName: "DelFolder",
			Handler:    _Engagement_DelFolder_Handler,
		},
		{
			MethodName: "AddShare",
			Handler:    _Engagement_AddShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engagement.proto",
}
