// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.9
// source: playback.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Playback_GetPlaybackToken_FullMethodName    = "/playback.v1.Playback/GetPlaybackToken"
	Playback_VerifyPlaybackToken_FullMethodName = "/playback.v1.Playback/VerifyPlaybackToken"
	Playback_ReportHeartbeat_FullMethodName     = "/playback.v1.Playback/ReportHeartbeat"
	Playback_GetSession_FullMethodName          = "/playback.v1.Playback/GetSession"
)

// PlaybackClient is the client API for Playback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Playback 播放授权与播放会话服务。
// 依据 AGENTS.md §5/§6：PGC 必须经 rights 校验版权窗口；签发地址短期有效；
// 心跳只写本服务表 + Outbox，异步进入 event-collector/spm，不在请求线程更新播放量。
type PlaybackClient interface {
	// 签发短期防盗链播放地址并创建播放会话（request_id 幂等）
	GetPlaybackToken(ctx context.Context, in *GetPlaybackTokenReq, opts ...grpc.CallOption) (*GetPlaybackTokenReply, error)
	// 边缘/网关回源校验 auth_key 与会话有效期，并按会话首次放行累加播放计数
	VerifyPlaybackToken(ctx context.Context, in *VerifyPlaybackTokenReq, opts ...grpc.CallOption) (*VerifyPlaybackTokenReply, error)
	// 上报播放心跳：幂等更新进度，并在同一事务写 playback.heartbeat 事件（Outbox）
	ReportHeartbeat(ctx context.Context, in *ReportHeartbeatReq, opts ...grpc.CallOption) (*ReportHeartbeatReply, error)
	// 查询播放会话与进度详情（管理后台/排障）
	GetSession(ctx context.Context, in *GetSessionReq, opts ...grpc.CallOption) (*GetSessionReply, error)
}

type playbackClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaybackClient(cc grpc.ClientConnInterface) PlaybackClient {
	return &playbackClient{cc}
}

func (c *playbackClient) GetPlaybackToken(ctx context.Context, in *GetPlaybackTokenReq, opts ...grpc.CallOption) (*GetPlaybackTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaybackTokenReply)
	err := c.cc.Invoke(ctx, Playback_GetPlaybackToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackClient) VerifyPlaybackToken(ctx context.Context, in *VerifyPlaybackTokenReq, opts ...grpc.CallOption) (*VerifyPlaybackTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPlaybackTokenReply)
	err := c.cc.Invoke(ctx, Playback_VerifyPlaybackToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackClient) ReportHeartbeat(ctx context.Context, in *ReportHeartbeatReq, opts ...grpc.CallOption) (*ReportHeartbeatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportHeartbeatReply)
	err := c.cc.Invoke(ctx, Playback_ReportHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackClient) GetSession(ctx context.Context, in *GetSessionReq, opts ...grpc.CallOption) (*GetSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionReply)
	err := c.cc.Invoke(ctx, Playback_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaybackServer is the server API for Playback service.
// All implementations must embed UnimplementedPlaybackServer
// for forward compatibility.
//
// Playback 播放授权与播放会话服务。
// 依据 AGENTS.md §5/§6：PGC 必须经 rights 校验版权窗口；签发地址短期有效；
// 心跳只写本服务表 + Outbox，异步进入 event-collector/spm，不在请求线程更新播放量。
type PlaybackServer interface {
	// 签发短期防盗链播放地址并创建播放会话（request_id 幂等）
	GetPlaybackToken(context.Context, *GetPlaybackTokenReq) (*GetPlaybackTokenReply, error)
	// 边缘/网关回源校验 auth_key 与会话有效期，并按会话首次放行累加播放计数
	VerifyPlaybackToken(context.Context, *VerifyPlaybackTokenReq) (*VerifyPlaybackTokenReply, error)
	// 上报播放心跳：幂等更新进度，并在同一事务写 playback.heartbeat 事件（Outbox）
	ReportHeartbeat(context.Context, *ReportHeartbeatReq) (*ReportHeartbeatReply, error)
	// 查询播放会话与进度详情（管理后台/排障）
	GetSession(context.Context, *GetSessionReq) (*GetSessionReply, error)
	mustEmbedUnimplementedPlaybackServer()
}

// UnimplementedPlaybackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaybackServer struct{}

func (UnimplementedPlaybackServer) GetPlaybackToken(context.Context, *GetPlaybackTokenReq) (*GetPlaybackTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaybackToken not implemented")
}
func (UnimplementedPlaybackServer) VerifyPlaybackToken(context.Context, *VerifyPlaybackTokenReq) (*VerifyPlaybackTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPlaybackToken not implemented")
}
func (UnimplementedPlaybackServer) ReportHeartbeat(context.Context, *ReportHeartbeatReq) (*ReportHeartbeatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportHeartbeat not implemented")
}
func (UnimplementedPlaybackServer) GetSession(context.Context, *GetSessionReq) (*GetSessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedPlaybackServer) mustEmbedUnimplementedPlaybackServer() {}
func (UnimplementedPlaybackServer) testEmbeddedByValue()                  {}

// UnsafePlaybackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaybackServer will
// result in compilation errors.
type UnsafePlaybackServer interface {
	mustEmbedUnimplementedPlaybackServer()
}

func RegisterPlaybackServer(s grpc.ServiceRegistrar, srv PlaybackServer) {
	// If the following call pancis, it indicates UnimplementedPlaybackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Playback_ServiceDesc, srv)
}

func _Playback_GetPlaybackToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaybackTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackServer).GetPlaybackToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Playback_GetPlaybackToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackServer).GetPlaybackToken(ctx, req.(*GetPlaybackTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playback_VerifyPlaybackToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPlaybackTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackServer).VerifyPlaybackToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Playback_VerifyPlaybackToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackServer).VerifyPlaybackToken(ctx, req.(*VerifyPlaybackTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playback_ReportHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackServer).ReportHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Playback_ReportHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackServer).ReportHeartbeat(ctx, req.(*ReportHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playback_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Playback_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackServer).GetSession(ctx, req.(*GetSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Playback_ServiceDesc is the grpc.ServiceDesc for Playback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Playback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "playback.v1.Playback",
	HandlerType: (*PlaybackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlaybackToken",
			Handler:    _Playback_GetPlaybackToken_Handler,
		},
		{
			MethodName: "VerifyPlaybackToken",
			Handler:    _Playback_VerifyPlaybackToken_Handler,
		},
		{
			MethodName: "ReportHeartbeat",
			Handler:    _Playback_ReportHeartbeat_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Playback_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playback.proto",
}
