// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operation.proto

package server

import (
	"context"

	"go-video/services/operation/internal/logic"
	"go-video/services/operation/internal/svc"
	"go-video/services/operation/rpc"
)

type OperationServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedOperationServer
}

func NewOperationServer(svcCtx *svc.ServiceContext) *OperationServer {
	return &OperationServer{
		svcCtx: svcCtx,
	}
}

// 管理员登录（口令校验 + 防爆破锁定），签发后台专用 token
func (s *OperationServer) AdminLogin(ctx context.Context, in *rpc.AdminLoginReq) (*rpc.AdminLoginReply, error) {
	l := logic.NewAdminLoginLogic(ctx, s.svcCtx)
	return l.AdminLogin(in)
}

// 权限校验（gateway/admin 每个受保护路由调用；结果带短缓存）
func (s *OperationServer) VerifyAdminPermission(ctx context.Context, in *rpc.VerifyAdminPermissionReq) (*rpc.VerifyAdminPermissionReply, error) {
	l := logic.NewVerifyAdminPermissionLogic(ctx, s.svcCtx)
	return l.VerifyAdminPermission(in)
}

// 创建管理员账号（口令只在入参出现，响应永不返回散列）
func (s *OperationServer) CreateAdminUser(ctx context.Context, in *rpc.CreateAdminUserReq) (*rpc.CreateAdminUserReply, error) {
	l := logic.NewCreateAdminUserLogic(ctx, s.svcCtx)
	return l.CreateAdminUser(in)
}

// 更新管理员账号（备注/状态/重置口令，重置口令会吊销会话）
func (s *OperationServer) UpdateAdminUser(ctx context.Context, in *rpc.UpdateAdminUserReq) (*rpc.UpdateAdminUserReply, error) {
	l := logic.NewUpdateAdminUserLogic(ctx, s.svcCtx)
	return l.UpdateAdminUser(in)
}

// 禁用管理员账号（同时吊销全部会话）
func (s *OperationServer) DisableAdminUser(ctx context.Context, in *rpc.DisableAdminUserReq) (*rpc.DisableAdminUserReply, error) {
	l := logic.NewDisableAdminUserLogic(ctx, s.svcCtx)
	return l.DisableAdminUser(in)
}

// 分页查询管理员账号
func (s *OperationServer) ListAdminUsers(ctx context.Context, in *rpc.ListAdminUsersReq) (*rpc.ListAdminUsersReply, error) {
	l := logic.NewListAdminUsersLogic(ctx, s.svcCtx)
	return l.ListAdminUsers(in)
}

// 全量覆盖管理员角色（并集生效）
func (s *OperationServer) AssignRoles(ctx context.Context, in *rpc.AssignRolesReq) (*rpc.AssignRolesReply, error) {
	l := logic.NewAssignRolesLogic(ctx, s.svcCtx)
	return l.AssignRoles(in)
}

// 创建角色并绑定权限点
func (s *OperationServer) CreateRole(ctx context.Context, in *rpc.CreateRoleReq) (*rpc.CreateRoleReply, error) {
	l := logic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

// 分页查询角色
func (s *OperationServer) ListRoles(ctx context.Context, in *rpc.ListRolesReq) (*rpc.ListRolesReply, error) {
	l := logic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

// 删除角色（仍有成员时拒绝）
func (s *OperationServer) DeleteRole(ctx context.Context, in *rpc.DeleteRoleReq) (*rpc.EmptyReply, error) {
	l := logic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

// 分页查询权限点
func (s *OperationServer) ListPermissions(ctx context.Context, in *rpc.ListPermissionsReq) (*rpc.ListPermissionsReply, error) {
	l := logic.NewListPermissionsLogic(ctx, s.svcCtx)
	return l.ListPermissions(in)
}

// 创建权限点（resource + action 唯一）
func (s *OperationServer) CreatePermission(ctx context.Context, in *rpc.CreatePermissionReq) (*rpc.CreatePermissionReply, error) {
	l := logic.NewCreatePermissionLogic(ctx, s.svcCtx)
	return l.CreatePermission(in)
}

// 按管理员角色并集返回可见菜单（后台 Web 专用）
func (s *OperationServer) GetMenu(ctx context.Context, in *rpc.GetMenuReq) (*rpc.GetMenuReply, error) {
	l := logic.NewGetMenuLogic(ctx, s.svcCtx)
	return l.GetMenu(in)
}

// 新建/更新菜单节点
func (s *OperationServer) SaveMenu(ctx context.Context, in *rpc.SaveMenuReq) (*rpc.SaveMenuReply, error) {
	l := logic.NewSaveMenuLogic(ctx, s.svcCtx)
	return l.SaveMenu(in)
}

// 读取运营配置（默认走缓存，refresh=true 强制回源）
func (s *OperationServer) GetOpsConfig(ctx context.Context, in *rpc.GetOpsConfigReq) (*rpc.GetOpsConfigReply, error) {
	l := logic.NewGetOpsConfigLogic(ctx, s.svcCtx)
	return l.GetOpsConfig(in)
}

// 写入运营配置（expect_version 乐观锁 + 操作者留痕）
func (s *OperationServer) SaveOpsConfig(ctx context.Context, in *rpc.SaveOpsConfigReq) (*rpc.SaveOpsConfigReply, error) {
	l := logic.NewSaveOpsConfigLogic(ctx, s.svcCtx)
	return l.SaveOpsConfig(in)
}

// 提交批量运营任务（request_id 幂等，状态 pending）
func (s *OperationServer) SubmitAdminTask(ctx context.Context, in *rpc.SubmitAdminTaskReq) (*rpc.SubmitAdminTaskReply, error) {
	l := logic.NewSubmitAdminTaskLogic(ctx, s.svcCtx)
	return l.SubmitAdminTask(in)
}

// 查询任务与步骤明细
func (s *OperationServer) GetAdminTask(ctx context.Context, in *rpc.GetAdminTaskReq) (*rpc.GetAdminTaskReply, error) {
	l := logic.NewGetAdminTaskLogic(ctx, s.svcCtx)
	return l.GetAdminTask(in)
}

// 分页查询任务
func (s *OperationServer) ListAdminTasks(ctx context.Context, in *rpc.ListAdminTasksReq) (*rpc.ListAdminTasksReply, error) {
	l := logic.NewListAdminTasksLogic(ctx, s.svcCtx)
	return l.ListAdminTasks(in)
}

// 取消任务（仅 pending/running 可取消）
func (s *OperationServer) CancelAdminTask(ctx context.Context, in *rpc.CancelAdminTaskReq) (*rpc.CancelAdminTaskReply, error) {
	l := logic.NewCancelAdminTaskLogic(ctx, s.svcCtx)
	return l.CancelAdminTask(in)
}

// 推进任务：逐步骤调用下游 RPC（由 cron 或人工触发，本服务不内置 worker）
func (s *OperationServer) RunAdminTask(ctx context.Context, in *rpc.RunAdminTaskReq) (*rpc.RunAdminTaskReply, error) {
	l := logic.NewRunAdminTaskLogic(ctx, s.svcCtx)
	return l.RunAdminTask(in)
}

// 查询管理操作审计索引（正文证据在下游服务/audit）
func (s *OperationServer) ListAuditIndex(ctx context.Context, in *rpc.ListAuditIndexReq) (*rpc.ListAuditIndexReply, error) {
	l := logic.NewListAuditIndexLogic(ctx, s.svcCtx)
	return l.ListAuditIndex(in)
}
