// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.9
// source: opsconfig.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpsConfig_ResolveConfig_FullMethodName       = "/opsconfig.v1.OpsConfig/ResolveConfig"
	OpsConfig_BatchResolveConfig_FullMethodName  = "/opsconfig.v1.OpsConfig/BatchResolveConfig"
	OpsConfig_ListConfigs_FullMethodName         = "/opsconfig.v1.OpsConfig/ListConfigs"
	OpsConfig_PublishConfig_FullMethodName       = "/opsconfig.v1.OpsConfig/PublishConfig"
	OpsConfig_RollbackConfig_FullMethodName      = "/opsconfig.v1.OpsConfig/RollbackConfig"
	OpsConfig_ListConfigVersions_FullMethodName  = "/opsconfig.v1.OpsConfig/ListConfigVersions"
	OpsConfig_SaveRolloutRule_FullMethodName     = "/opsconfig.v1.OpsConfig/SaveRolloutRule"
	OpsConfig_ListRolloutRules_FullMethodName    = "/opsconfig.v1.OpsConfig/ListRolloutRules"
	OpsConfig_SetRolloutRuleState_FullMethodName = "/opsconfig.v1.OpsConfig/SetRolloutRuleState"
	OpsConfig_SaveTopic_FullMethodName           = "/opsconfig.v1.OpsConfig/SaveTopic"
	OpsConfig_GetTopic_FullMethodName            = "/opsconfig.v1.OpsConfig/GetTopic"
	OpsConfig_ListTopics_FullMethodName          = "/opsconfig.v1.OpsConfig/ListTopics"
	OpsConfig_SaveTopicItems_FullMethodName      = "/opsconfig.v1.OpsConfig/SaveTopicItems"
	OpsConfig_SaveSlot_FullMethodName            = "/opsconfig.v1.OpsConfig/SaveSlot"
	OpsConfig_ListSlots_FullMethodName           = "/opsconfig.v1.OpsConfig/ListSlots"
	OpsConfig_SaveSlotItems_FullMethodName       = "/opsconfig.v1.OpsConfig/SaveSlotItems"
	OpsConfig_ResolveSlot_FullMethodName         = "/opsconfig.v1.OpsConfig/ResolveSlot"
	OpsConfig_SaveClientSwitch_FullMethodName    = "/opsconfig.v1.OpsConfig/SaveClientSwitch"
	OpsConfig_ListClientSwitches_FullMethodName  = "/opsconfig.v1.OpsConfig/ListClientSwitches"
	OpsConfig_RefreshCache_FullMethodName        = "/opsconfig.v1.OpsConfig/RefreshCache"
)

// OpsConfigClient is the client API for OpsConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OpsConfig 运营配置服务：发布式配置、灰度与回滚、专题、推荐位、客户端开关、缓存刷新。
type OpsConfigClient interface {
	// 运行时解析单个配置（命中灰度规则，返回建议 TTL）
	ResolveConfig(ctx context.Context, in *ResolveConfigReq, opts ...grpc.CallOption) (*ResolveConfigReply, error)
	// 批量解析（网关聚合用，最多 50 键）
	BatchResolveConfig(ctx context.Context, in *BatchResolveConfigReq, opts ...grpc.CallOption) (*BatchResolveConfigReply, error)
	// 后台分页列出配置项
	ListConfigs(ctx context.Context, in *ListConfigsReq, opts ...grpc.CallOption) (*ListConfigsReply, error)
	// 发布新版本（乐观锁 + 幂等 + 可选一并挂灰度规则）
	PublishConfig(ctx context.Context, in *PublishConfigReq, opts ...grpc.CallOption) (*PublishConfigReply, error)
	// 回滚到历史版本（生成新版本，不改写历史）
	RollbackConfig(ctx context.Context, in *RollbackConfigReq, opts ...grpc.CallOption) (*RollbackConfigReply, error)
	// 版本历史分页
	ListConfigVersions(ctx context.Context, in *ListConfigVersionsReq, opts ...grpc.CallOption) (*ListConfigVersionsReply, error)
	// 新建/更新灰度规则（按 config_id + version + name upsert）
	SaveRolloutRule(ctx context.Context, in *SaveRolloutRuleReq, opts ...grpc.CallOption) (*SaveRolloutRuleReply, error)
	// 灰度规则分页查询
	ListRolloutRules(ctx context.Context, in *ListRolloutRulesReq, opts ...grpc.CallOption) (*ListRolloutRulesReply, error)
	// 启停灰度规则（软状态切换，保留放量证据）
	SetRolloutRuleState(ctx context.Context, in *SetRolloutRuleStateReq, opts ...grpc.CallOption) (*SetRolloutRuleStateReply, error)
	// 新建/更新专题（zone_ids/tag_ids 只存引用）
	SaveTopic(ctx context.Context, in *SaveTopicReq, opts ...grpc.CallOption) (*SaveTopicReply, error)
	// 专题详情（可带条目）
	GetTopic(ctx context.Context, in *GetTopicReq, opts ...grpc.CallOption) (*GetTopicReply, error)
	// 专题分页查询
	ListTopics(ctx context.Context, in *ListTopicsReq, opts ...grpc.CallOption) (*ListTopicsReply, error)
	// 全量覆盖专题条目
	SaveTopicItems(ctx context.Context, in *SaveTopicItemsReq, opts ...grpc.CallOption) (*SaveTopicItemsReply, error)
	// 新建/更新推荐位定义
	SaveSlot(ctx context.Context, in *SaveSlotReq, opts ...grpc.CallOption) (*SaveSlotReply, error)
	// 推荐位分页查询
	ListSlots(ctx context.Context, in *ListSlotsReq, opts ...grpc.CallOption) (*ListSlotsReply, error)
	// 全量覆盖坑位条目与排期
	SaveSlotItems(ctx context.Context, in *SaveSlotItemsReq, opts ...grpc.CallOption) (*SaveSlotItemsReply, error)
	// 运行时坑位视图（按端/版本/mid/时间过滤，只回引用）
	ResolveSlot(ctx context.Context, in *ResolveSlotReq, opts ...grpc.CallOption) (*ResolveSlotReply, error)
	// 新建/更新客户端开关（按 switch_key + platform upsert）
	SaveClientSwitch(ctx context.Context, in *SaveClientSwitchReq, opts ...grpc.CallOption) (*SaveClientSwitchReply, error)
	// 客户端开关分页查询
	ListClientSwitches(ctx context.Context, in *ListClientSwitchesReq, opts ...grpc.CallOption) (*ListClientSwitchesReply, error)
	// 主动失效运行时缓存（必写审计）
	RefreshCache(ctx context.Context, in *RefreshCacheReq, opts ...grpc.CallOption) (*RefreshCacheReply, error)
}

type opsConfigClient struct {
	cc grpc.ClientConnInterface
}

func NewOpsConfigClient(cc grpc.ClientConnInterface) OpsConfigClient {
	return &opsConfigClient{cc}
}

func (c *opsConfigClient) ResolveConfig(ctx context.Context, in *ResolveConfigReq, opts ...grpc.CallOption) (*ResolveConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveConfigReply)
	err := c.cc.Invoke(ctx, OpsConfig_ResolveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) BatchResolveConfig(ctx context.Context, in *BatchResolveConfigReq, opts ...grpc.CallOption) (*BatchResolveConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResolveConfigReply)
	err := c.cc.Invoke(ctx, OpsConfig_BatchResolveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) ListConfigs(ctx context.Context, in *ListConfigsReq, opts ...grpc.CallOption) (*ListConfigsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigsReply)
	err := c.cc.Invoke(ctx, OpsConfig_ListConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) PublishConfig(ctx context.Context, in *PublishConfigReq, opts ...grpc.CallOption) (*PublishConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishConfigReply)
	err := c.cc.Invoke(ctx, OpsConfig_PublishConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) RollbackConfig(ctx context.Context, in *RollbackConfigReq, opts ...grpc.CallOption) (*RollbackConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackConfigReply)
	err := c.cc.Invoke(ctx, OpsConfig_RollbackConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) ListConfigVersions(ctx context.Context, in *ListConfigVersionsReq, opts ...grpc.CallOption) (*ListConfigVersionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigVersionsReply)
	err := c.cc.Invoke(ctx, OpsConfig_ListConfigVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) SaveRolloutRule(ctx context.Context, in *SaveRolloutRuleReq, opts ...grpc.CallOption) (*SaveRolloutRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRolloutRuleReply)
	err := c.cc.Invoke(ctx, OpsConfig_SaveRolloutRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) ListRolloutRules(ctx context.Context, in *ListRolloutRulesReq, opts ...grpc.CallOption) (*ListRolloutRulesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolloutRulesReply)
	err := c.cc.Invoke(ctx, OpsConfig_ListRolloutRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) SetRolloutRuleState(ctx context.Context, in *SetRolloutRuleStateReq, opts ...grpc.CallOption) (*SetRolloutRuleStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRolloutRuleStateReply)
	err := c.cc.Invoke(ctx, OpsConfig_SetRolloutRuleState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) SaveTopic(ctx context.Context, in *SaveTopicReq, opts ...grpc.CallOption) (*SaveTopicReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTopicReply)
	err := c.cc.Invoke(ctx, OpsConfig_SaveTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) GetTopic(ctx context.Context, in *GetTopicReq, opts ...grpc.CallOption) (*GetTopicReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicReply)
	err := c.cc.Invoke(ctx, OpsConfig_GetTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) ListTopics(ctx context.Context, in *ListTopicsReq, opts ...grpc.CallOption) (*ListTopicsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopicsReply)
	err := c.cc.Invoke(ctx, OpsConfig_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) SaveTopicItems(ctx context.Context, in *SaveTopicItemsReq, opts ...grpc.CallOption) (*SaveTopicItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTopicItemsReply)
	err := c.cc.Invoke(ctx, OpsConfig_SaveTopicItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) SaveSlot(ctx context.Context, in *SaveSlotReq, opts ...grpc.CallOption) (*SaveSlotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSlotReply)
	err := c.cc.Invoke(ctx, OpsConfig_SaveSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) ListSlots(ctx context.Context, in *ListSlotsReq, opts ...grpc.CallOption) (*ListSlotsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSlotsReply)
	err := c.cc.Invoke(ctx, OpsConfig_ListSlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) SaveSlotItems(ctx context.Context, in *SaveSlotItemsReq, opts ...grpc.CallOption) (*SaveSlotItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSlotItemsReply)
	err := c.cc.Invoke(ctx, OpsConfig_SaveSlotItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) ResolveSlot(ctx context.Context, in *ResolveSlotReq, opts ...grpc.CallOption) (*ResolveSlotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSlotReply)
	err := c.cc.Invoke(ctx, OpsConfig_ResolveSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) SaveClientSwitch(ctx context.Context, in *SaveClientSwitchReq, opts ...grpc.CallOption) (*SaveClientSwitchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveClientSwitchReply)
	err := c.cc.Invoke(ctx, OpsConfig_SaveClientSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) ListClientSwitches(ctx context.Context, in *ListClientSwitchesReq, opts ...grpc.CallOption) (*ListClientSwitchesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientSwitchesReply)
	err := c.cc.Invoke(ctx, OpsConfig_ListClientSwitches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsConfigClient) RefreshCache(ctx context.Context, in *RefreshCacheReq, opts ...grpc.CallOption) (*RefreshCacheReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshCacheReply)
	err := c.cc.Invoke(ctx, OpsConfig_RefreshCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpsConfigServer is the server API for OpsConfig service.
// All implementations must embed UnimplementedOpsConfigServer
// for forward compatibility.
//
// OpsConfig 运营配置服务：发布式配置、灰度与回滚、专题、推荐位、客户端开关、缓存刷新。
type OpsConfigServer interface {
	// 运行时解析单个配置（命中灰度规则，返回建议 TTL）
	ResolveConfig(context.Context, *ResolveConfigReq) (*ResolveConfigReply, error)
	// 批量解析（网关聚合用，最多 50 键）
	BatchResolveConfig(context.Context, *BatchResolveConfigReq) (*BatchResolveConfigReply, error)
	// 后台分页列出配置项
	ListConfigs(context.Context, *ListConfigsReq) (*ListConfigsReply, error)
	// 发布新版本（乐观锁 + 幂等 + 可选一并挂灰度规则）
	PublishConfig(context.Context, *PublishConfigReq) (*PublishConfigReply, error)
	// 回滚到历史版本（生成新版本，不改写历史）
	RollbackConfig(context.Context, *RollbackConfigReq) (*RollbackConfigReply, error)
	// 版本历史分页
	ListConfigVersions(context.Context, *ListConfigVersionsReq) (*ListConfigVersionsReply, error)
	// 新建/更新灰度规则（按 config_id + version + name upsert）
	SaveRolloutRule(context.Context, *SaveRolloutRuleReq) (*SaveRolloutRuleReply, error)
	// 灰度规则分页查询
	ListRolloutRules(context.Context, *ListRolloutRulesReq) (*ListRolloutRulesReply, error)
	// 启停灰度规则（软状态切换，保留放量证据）
	SetRolloutRuleState(context.Context, *SetRolloutRuleStateReq) (*SetRolloutRuleStateReply, error)
	// 新建/更新专题（zone_ids/tag_ids 只存引用）
	SaveTopic(context.Context, *SaveTopicReq) (*SaveTopicReply, error)
	// 专题详情（可带条目）
	GetTopic(context.Context, *GetTopicReq) (*GetTopicReply, error)
	// 专题分页查询
	ListTopics(context.Context, *ListTopicsReq) (*ListTopicsReply, error)
	// 全量覆盖专题条目
	SaveTopicItems(context.Context, *SaveTopicItemsReq) (*SaveTopicItemsReply, error)
	// 新建/更新推荐位定义
	SaveSlot(context.Context, *SaveSlotReq) (*SaveSlotReply, error)
	// 推荐位分页查询
	ListSlots(context.Context, *ListSlotsReq) (*ListSlotsReply, error)
	// 全量覆盖坑位条目与排期
	SaveSlotItems(context.Context, *SaveSlotItemsReq) (*SaveSlotItemsReply, error)
	// 运行时坑位视图（按端/版本/mid/时间过滤，只回引用）
	ResolveSlot(context.Context, *ResolveSlotReq) (*ResolveSlotReply, error)
	// 新建/更新客户端开关（按 switch_key + platform upsert）
	SaveClientSwitch(context.Context, *SaveClientSwitchReq) (*SaveClientSwitchReply, error)
	// 客户端开关分页查询
	ListClientSwitches(context.Context, *ListClientSwitchesReq) (*ListClientSwitchesReply, error)
	// 主动失效运行时缓存（必写审计）
	RefreshCache(context.Context, *RefreshCacheReq) (*RefreshCacheReply, error)
	mustEmbedUnimplementedOpsConfigServer()
}

// UnimplementedOpsConfigServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpsConfigServer struct{}

func (UnimplementedOpsConfigServer) ResolveConfig(context.Context, *ResolveConfigReq) (*ResolveConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveConfig not implemented")
}
func (UnimplementedOpsConfigServer) BatchResolveConfig(context.Context, *BatchResolveConfigReq) (*BatchResolveConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchResolveConfig not implemented")
}
func (UnimplementedOpsConfigServer) ListConfigs(context.Context, *ListConfigsReq) (*ListConfigsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigs not implemented")
}
func (UnimplementedOpsConfigServer) PublishConfig(context.Context, *PublishConfigReq) (*PublishConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishConfig not implemented")
}
func (UnimplementedOpsConfigServer) RollbackConfig(context.Context, *RollbackConfigReq) (*RollbackConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackConfig not implemented")
}
func (UnimplementedOpsConfigServer) ListConfigVersions(context.Context, *ListConfigVersionsReq) (*ListConfigVersionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigVersions not implemented")
}
func (UnimplementedOpsConfigServer) SaveRolloutRule(context.Context, *SaveRolloutRuleReq) (*SaveRolloutRuleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRolloutRule not implemented")
}
func (UnimplementedOpsConfigServer) ListRolloutRules(context.Context, *ListRolloutRulesReq) (*ListRolloutRulesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRolloutRules not implemented")
}
func (UnimplementedOpsConfigServer) SetRolloutRuleState(context.Context, *SetRolloutRuleStateReq) (*SetRolloutRuleStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRolloutRuleState not implemented")
}
func (UnimplementedOpsConfigServer) SaveTopic(context.Context, *SaveTopicReq) (*SaveTopicReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTopic not implemented")
}
func (UnimplementedOpsConfigServer) GetTopic(context.Context, *GetTopicReq) (*GetTopicReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopic not implemented")
}
func (UnimplementedOpsConfigServer) ListTopics(context.Context, *ListTopicsReq) (*ListTopicsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedOpsConfigServer) SaveTopicItems(context.Context, *SaveTopicItemsReq) (*SaveTopicItemsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTopicItems not implemented")
}
func (UnimplementedOpsConfigServer) SaveSlot(context.Context, *SaveSlotReq) (*SaveSlotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSlot not implemented")
}
func (UnimplementedOpsConfigServer) ListSlots(context.Context, *ListSlotsReq) (*ListSlotsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSlots not implemented")
}
func (UnimplementedOpsConfigServer) SaveSlotItems(context.Context, *SaveSlotItemsReq) (*SaveSlotItemsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSlotItems not implemented")
}
func (UnimplementedOpsConfigServer) ResolveSlot(context.Context, *ResolveSlotReq) (*ResolveSlotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveSlot not implemented")
}
func (UnimplementedOpsConfigServer) SaveClientSwitch(context.Context, *SaveClientSwitchReq) (*SaveClientSwitchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveClientSwitch not implemented")
}
func (UnimplementedOpsConfigServer) ListClientSwitches(context.Context, *ListClientSwitchesReq) (*ListClientSwitchesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClientSwitches not implemented")
}
func (UnimplementedOpsConfigServer) RefreshCache(context.Context, *RefreshCacheReq) (*RefreshCacheReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshCache not implemented")
}
func (UnimplementedOpsConfigServer) mustEmbedUnimplementedOpsConfigServer() {}
func (UnimplementedOpsConfigServer) testEmbeddedByValue()                   {}

// UnsafeOpsConfigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpsConfigServer will
// result in compilation errors.
type UnsafeOpsConfigServer interface {
	mustEmbedUnimplementedOpsConfigServer()
}

func RegisterOpsConfigServer(s grpc.ServiceRegistrar, srv OpsConfigServer) {
	// If the following call pancis, it indicates UnimplementedOpsConfigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpsConfig_ServiceDesc, srv)
}

func _OpsConfig_ResolveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).ResolveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_ResolveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).ResolveConfig(ctx, req.(*ResolveConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_BatchResolveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchResolveConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).BatchResolveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_BatchResolveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).BatchResolveConfig(ctx, req.(*BatchResolveConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_ListConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).ListConfigs(ctx, req.(*ListConfigsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_PublishConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).PublishConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_PublishConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).PublishConfig(ctx, req.(*PublishConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_RollbackConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).RollbackConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_RollbackConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).RollbackConfig(ctx, req.(*RollbackConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_ListConfigVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigVersionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).ListConfigVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_ListConfigVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).ListConfigVersions(ctx, req.(*ListConfigVersionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_SaveRolloutRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRolloutRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).SaveRolloutRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_SaveRolloutRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).SaveRolloutRule(ctx, req.(*SaveRolloutRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_ListRolloutRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolloutRulesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).ListRolloutRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_ListRolloutRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).ListRolloutRules(ctx, req.(*ListRolloutRulesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_SetRolloutRuleState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRolloutRuleStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).SetRolloutRuleState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_SetRolloutRuleState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).SetRolloutRuleState(ctx, req.(*SetRolloutRuleStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_SaveTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTopicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).SaveTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_SaveTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).SaveTopic(ctx, req.(*SaveTopicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_GetTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).GetTopic(ctx, req.(*GetTopicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).ListTopics(ctx, req.(*ListTopicsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_SaveTopicItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTopicItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).SaveTopicItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_SaveTopicItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).SaveTopicItems(ctx, req.(*SaveTopicItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_SaveSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSlotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).SaveSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_SaveSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).SaveSlot(ctx, req.(*SaveSlotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_ListSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSlotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).ListSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_ListSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).ListSlots(ctx, req.(*ListSlotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_SaveSlotItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSlotItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).SaveSlotItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_SaveSlotItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).SaveSlotItems(ctx, req.(*SaveSlotItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_ResolveSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSlotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).ResolveSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_ResolveSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).ResolveSlot(ctx, req.(*ResolveSlotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_SaveClientSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveClientSwitchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).SaveClientSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_SaveClientSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).SaveClientSwitch(ctx, req.(*SaveClientSwitchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_ListClientSwitches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientSwitchesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).ListClientSwitches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_ListClientSwitches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).ListClientSwitches(ctx, req.(*ListClientSwitchesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsConfig_RefreshCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshCacheReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsConfigServer).RefreshCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsConfig_RefreshCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsConfigServer).RefreshCache(ctx, req.(*RefreshCacheReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OpsConfig_ServiceDesc is the grpc.ServiceDesc for OpsConfig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpsConfig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsconfig.v1.OpsConfig",
	HandlerType: (*OpsConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveConfig",
			Handler:    _OpsConfig_ResolveConfig_Handler,
		},
		{
			MethodName: "BatchResolveConfig",
			Handler:    _OpsConfig_BatchResolveConfig_Handler,
		},
		{
			MethodName: "ListConfigs",
			Handler:    _OpsConfig_ListConfigs_Handler,
		},
		{
			MethodName: "PublishConfig",
			Handler:    _OpsConfig_PublishConfig_Handler,
		},
		{
			MethodName: "RollbackConfig",
			Handler:    _OpsConfig_RollbackConfig_Handler,
		},
		{
			MethodName: "ListConfigVersions",
			Handler:    _OpsConfig_ListConfigVersions_Handler,
		},
		{
			MethodName: "SaveRolloutRule",
			Handler:    _OpsConfig_SaveRolloutRule_Handler,
		},
		{
			MethodName: "ListRolloutRules",
			Handler:    _OpsConfig_ListRolloutRules_Handler,
		},
		{
			MethodName: "SetRolloutRuleState",
			Handler:    _OpsConfig_SetRolloutRuleState_Handler,
		},
		{
			MethodName: "SaveTopic",
			Handler:    _OpsConfig_SaveTopic_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _OpsConfig_GetTopic_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _OpsConfig_ListTopics_Handler,
		},
		{
			MethodName: "SaveTopicItems",
			Handler:    _OpsConfig_SaveTopicItems_Handler,
		},
		{
			MethodName: "SaveSlot",
			Handler:    _OpsConfig_SaveSlot_Handler,
		},
		{
			MethodName: "ListSlots",
			Handler:    _OpsConfig_ListSlots_Handler,
		},
		{
			MethodName: "SaveSlotItems",
			Handler:    _OpsConfig_SaveSlotItems_Handler,
		},
		{
			MethodName: "ResolveSlot",
			Handler:    _OpsConfig_ResolveSlot_Handler,
		},
		{
			MethodName: "SaveClientSwitch",
			Handler:    _OpsConfig_SaveClientSwitch_Handler,
		},
		{
			MethodName: "ListClientSwitches",
			Handler:    _OpsConfig_ListClientSwitches_Handler,
		},
		{
			MethodName: "RefreshCache",
			Handler:    _OpsConfig_RefreshCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opsconfig.proto",
}
