// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: liveroom.proto

package server

import (
	"context"

	"go-video/services/live-room/internal/logic"
	"go-video/services/live-room/internal/svc"
	"go-video/services/live-room/rpc"
)

type LiveRoomServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedLiveRoomServer
}

func NewLiveRoomServer(svcCtx *svc.ServiceContext) *LiveRoomServer {
	return &LiveRoomServer{
		svcCtx: svcCtx,
	}
}

// 创建直播间：校验分区有效与房间数上限 → 落 PENDING → 建绑定与配置 → 送资料审核
func (s *LiveRoomServer) CreateRoom(ctx context.Context, in *rpc.CreateRoomReq) (*rpc.CreateRoomReply, error) {
	l := logic.NewCreateRoomLogic(ctx, s.svcCtx)
	return l.CreateRoom(in)
}

// 修改标题/封面/分区：终态房间不可改；改动后重新送审（PENDING/READY 才允许）
func (s *LiveRoomServer) UpdateRoomInfo(ctx context.Context, in *rpc.UpdateRoomInfoReq) (*rpc.UpdateRoomInfoReply, error) {
	l := logic.NewUpdateRoomInfoLogic(ctx, s.svcCtx)
	return l.UpdateRoomInfo(in)
}

// 读房间（可按 room_id 或房主 mid），可附带配置与进行中场次
func (s *LiveRoomServer) GetRoom(ctx context.Context, in *rpc.GetRoomReq) (*rpc.GetRoomReply, error) {
	l := logic.NewGetRoomLogic(ctx, s.svcCtx)
	return l.GetRoom(in)
}

// 分页浏览房间（发现页/主播主页/运营列表）
func (s *LiveRoomServer) ListRooms(ctx context.Context, in *rpc.ListRoomsReq) (*rpc.ListRoomsReply, error) {
	l := logic.NewListRoomsLogic(ctx, s.svcCtx)
	return l.ListRooms(in)
}

// 开播前置检查：主播资格(creator) + 风控(risk-control) + 资料审核 + 未禁播，全通过才 PENDING→READY
func (s *LiveRoomServer) PrepareLive(ctx context.Context, in *rpc.PrepareLiveReq) (*rpc.PrepareLiveReply, error) {
	l := logic.NewPrepareLiveLogic(ctx, s.svcCtx)
	return l.PrepareLive(in)
}

// 开播：READY→LIVING 并新建场次（不接收推流密钥，只登记 stream_id 引用）
func (s *LiveRoomServer) StartLive(ctx context.Context, in *rpc.StartLiveReq) (*rpc.StartLiveReply, error) {
	l := logic.NewStartLiveLogic(ctx, s.svcCtx)
	return l.StartLive(in)
}

// 下播：LIVING→READY 并把场次置为 ENDED（时长簿记）
func (s *LiveRoomServer) EndLive(ctx context.Context, in *rpc.EndLiveReq) (*rpc.EndLiveReply, error) {
	l := logic.NewEndLiveLogic(ctx, s.svcCtx)
	return l.EndLive(in)
}

// 关闭房间：任意非终态 → FINISHED，强制终止进行中场次并保留审计
func (s *LiveRoomServer) CloseRoom(ctx context.Context, in *rpc.CloseRoomReq) (*rpc.CloseRoomReply, error) {
	l := logic.NewCloseRoomLogic(ctx, s.svcCtx)
	return l.CloseRoom(in)
}

// 推流状态事件入口（live.state.v1 消费者或 live-ingest 直调）：event_id 去重 + seq 乱序守卫
func (s *LiveRoomServer) ReportStreamState(ctx context.Context, in *rpc.ReportStreamStateReq) (*rpc.ReportStreamStateReply, error) {
	l := logic.NewReportStreamStateLogic(ctx, s.svcCtx)
	return l.ReportStreamState(in)
}

// 资料审核结论回写（moderation.result.v1 消费者入口），按合法状态机推进
func (s *LiveRoomServer) ApplyRoomModerationResult(ctx context.Context, in *rpc.ApplyRoomModerationResultReq) (*rpc.ApplyRoomModerationResultReply, error) {
	l := logic.NewApplyRoomModerationResultLogic(ctx, s.svcCtx)
	return l.ApplyRoomModerationResult(in)
}

// 禁播：进入 BANNED 并终止进行中场次（运营/系统，需 operator_mid）
func (s *LiveRoomServer) BanRoom(ctx context.Context, in *rpc.BanRoomReq) (*rpc.BanRoomReply, error) {
	l := logic.NewBanRoomLogic(ctx, s.svcCtx)
	return l.BanRoom(in)
}

// 解除禁播：BANNED→READY
func (s *LiveRoomServer) LiftBan(ctx context.Context, in *rpc.LiftBanReq) (*rpc.LiftBanReply, error) {
	l := logic.NewLiftBanLogic(ctx, s.svcCtx)
	return l.LiftBan(in)
}

// 分页查询禁播记录（运营侧审计）
func (s *LiveRoomServer) ListRoomBans(ctx context.Context, in *rpc.ListRoomBansReq) (*rpc.ListRoomBansReply, error) {
	l := logic.NewListRoomBansLogic(ctx, s.svcCtx)
	return l.ListRoomBans(in)
}

// 读场次（按 session_id，或按 room_id 取最近 N 场之一）
func (s *LiveRoomServer) GetSession(ctx context.Context, in *rpc.GetSessionReq) (*rpc.GetSessionReply, error) {
	l := logic.NewGetSessionLogic(ctx, s.svcCtx)
	return l.GetSession(in)
}

// cursor 分页拉取历史场次
func (s *LiveRoomServer) ListSessions(ctx context.Context, in *rpc.ListSessionsReq) (*rpc.ListSessionsReply, error) {
	l := logic.NewListSessionsLogic(ctx, s.svcCtx)
	return l.ListSessions(in)
}

// 关联回放：只写 record/asset/aid 引用与回放状态，不落媒资数据
func (s *LiveRoomServer) AttachReplay(ctx context.Context, in *rpc.AttachReplayReq) (*rpc.AttachReplayReply, error) {
	l := logic.NewAttachReplayLogic(ctx, s.svcCtx)
	return l.AttachReplay(in)
}

// 更新直播配置（弹幕/回复/录制/连麦/直播类型）
func (s *LiveRoomServer) UpdateRoomSetting(ctx context.Context, in *rpc.UpdateRoomSettingReq) (*rpc.UpdateRoomSettingReply, error) {
	l := logic.NewUpdateRoomSettingLogic(ctx, s.svcCtx)
	return l.UpdateRoomSetting(in)
}

// 绑定或解绑主播（房主/联合主播/房管），含单主播房间数上限校验
func (s *LiveRoomServer) MutateAnchor(ctx context.Context, in *rpc.MutateAnchorReq) (*rpc.MutateAnchorReply, error) {
	l := logic.NewMutateAnchorLogic(ctx, s.svcCtx)
	return l.MutateAnchor(in)
}

// 分页查询房间主播绑定
func (s *LiveRoomServer) ListAnchors(ctx context.Context, in *rpc.ListAnchorsReq) (*rpc.ListAnchorsReply, error) {
	l := logic.NewListAnchorsLogic(ctx, s.svcCtx)
	return l.ListAnchors(in)
}

// 运营侧新建/修改直播分区
func (s *LiveRoomServer) UpsertArea(ctx context.Context, in *rpc.UpsertAreaReq) (*rpc.UpsertAreaReply, error) {
	l := logic.NewUpsertAreaLogic(ctx, s.svcCtx)
	return l.UpsertArea(in)
}

// 分区列表（客户端与运营共用）
func (s *LiveRoomServer) ListAreas(ctx context.Context, in *rpc.ListAreasReq) (*rpc.ListAreasReply, error) {
	l := logic.NewListAreasLogic(ctx, s.svcCtx)
	return l.ListAreas(in)
}
