// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: livegateway.proto

package server

import (
	"context"

	"go-video/services/live-gateway/internal/logic"
	"go-video/services/live-gateway/internal/svc"
	"go-video/services/live-gateway/rpc"
)

type LiveGatewayServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedLiveGatewayServer
}

func NewLiveGatewayServer(svcCtx *svc.ServiceContext) *LiveGatewayServer {
	return &LiveGatewayServer{
		svcCtx: svcCtx,
	}
}

// 申请连接租约：校验 (mid, room_id, role) 与配额，签发 lease_id + 重连票据
func (s *LiveGatewayServer) AcquireConnectionLease(ctx context.Context, in *rpc.AcquireConnectionLeaseReq) (*rpc.AcquireConnectionLeaseReply, error) {
	l := logic.NewAcquireConnectionLeaseLogic(ctx, s.svcCtx)
	return l.AcquireConnectionLease(in)
}

// 续租（TTL 刷新）：三元组不匹配一律拒绝，不静默改绑
func (s *LiveGatewayServer) RenewConnectionLease(ctx context.Context, in *rpc.RenewConnectionLeaseReq) (*rpc.RenewConnectionLeaseReply, error) {
	l := logic.NewRenewConnectionLeaseLogic(ctx, s.svcCtx)
	return l.RenewConnectionLease(in)
}

// 释放租约（正常断开/切房）
func (s *LiveGatewayServer) ReleaseConnectionLease(ctx context.Context, in *rpc.ReleaseConnectionLeaseReq) (*rpc.EmptyReply, error) {
	l := logic.NewReleaseConnectionLeaseLogic(ctx, s.svcCtx)
	return l.ReleaseConnectionLease(in)
}

// 查询租约（下发前的权限校验入口之一）
func (s *LiveGatewayServer) GetConnectionLease(ctx context.Context, in *rpc.ConnectionLeaseReq) (*rpc.ConnectionLeaseReply, error) {
	l := logic.NewGetConnectionLeaseLogic(ctx, s.svcCtx)
	return l.GetConnectionLease(in)
}

// 客户端心跳簿记：推进 last_heartbeat/max_seq，抽样产出 QoE 事件
func (s *LiveGatewayServer) ReportClientHeartbeat(ctx context.Context, in *rpc.ReportClientHeartbeatReq) (*rpc.ReportClientHeartbeatReply, error) {
	l := logic.NewReportClientHeartbeatLogic(ctx, s.svcCtx)
	return l.ReportClientHeartbeat(in)
}

// 房间在线连接列表（Redis 视图，运营排障与主播工具）
func (s *LiveGatewayServer) ListRoomConnections(ctx context.Context, in *rpc.ListRoomConnectionsReq) (*rpc.ListRoomConnectionsReply, error) {
	l := logic.NewListRoomConnectionsLogic(ctx, s.svcCtx)
	return l.ListRoomConnections(in)
}

// 以现有租约为凭据签发一次性重连票据
func (s *LiveGatewayServer) IssueReconnectTicket(ctx context.Context, in *rpc.IssueReconnectTicketReq) (*rpc.ReconnectTicketInfo, error) {
	l := logic.NewIssueReconnectTicketLogic(ctx, s.svcCtx)
	return l.IssueReconnectTicket(in)
}

// 用票据换取新租约（校验 mid/room/有效期，一次性消费）
func (s *LiveGatewayServer) RedeemReconnectTicket(ctx context.Context, in *rpc.RedeemReconnectTicketReq) (*rpc.RedeemReconnectTicketReply, error) {
	l := logic.NewRedeemReconnectTicketLogic(ctx, s.svcCtx)
	return l.RedeemReconnectTicket(in)
}

// 撤销票据（封禁、踢人、房间关闭）
func (s *LiveGatewayServer) RevokeReconnectTicket(ctx context.Context, in *rpc.RevokeReconnectTicketReq) (*rpc.RevokeReconnectTicketReply, error) {
	l := logic.NewRevokeReconnectTicketLogic(ctx, s.svcCtx)
	return l.RevokeReconnectTicket(in)
}

// 加入房间（登记订阅关系 + 复用/创建房间路由）
func (s *LiveGatewayServer) JoinRoom(ctx context.Context, in *rpc.JoinRoomReq) (*rpc.JoinRoomReply, error) {
	l := logic.NewJoinRoomLogic(ctx, s.svcCtx)
	return l.JoinRoom(in)
}

// 退出房间
func (s *LiveGatewayServer) LeaveRoom(ctx context.Context, in *rpc.LeaveRoomReq) (*rpc.EmptyReply, error) {
	l := logic.NewLeaveRoomLogic(ctx, s.svcCtx)
	return l.LeaveRoom(in)
}

// 查询房间路由（广播第一跳与副本节点）
func (s *LiveGatewayServer) GetRoomRoute(ctx context.Context, in *rpc.RoomRouteReq) (*rpc.RoomRouteInfo, error) {
	l := logic.NewGetRoomRouteLogic(ctx, s.svcCtx)
	return l.GetRoomRoute(in)
}

// 分页查询房间路由（运营/发布排障）
func (s *LiveGatewayServer) ListRoomRoutes(ctx context.Context, in *rpc.ListRoomRoutesReq) (*rpc.ListRoomRoutesReply, error) {
	l := logic.NewListRoomRoutesLogic(ctx, s.svcCtx)
	return l.ListRoomRoutes(in)
}

// 排空某节点上的房间路由（优雅下线，版本号乐观校验）
func (s *LiveGatewayServer) DrainRoomRoute(ctx context.Context, in *rpc.DrainRoomRouteReq) (*rpc.RoomRouteInfo, error) {
	l := logic.NewDrainRoomRouteLogic(ctx, s.svcCtx)
	return l.DrainRoomRoute(in)
}

// 房间广播：权限矩阵 + 配额限流 + message_id 去重，允许丢弃但原因必须可解释
func (s *LiveGatewayServer) BroadcastToRoom(ctx context.Context, in *rpc.BroadcastToRoomReq) (*rpc.BroadcastToRoomReply, error) {
	l := logic.NewBroadcastToRoomLogic(ctx, s.svcCtx)
	return l.BroadcastToRoom(in)
}

// 房间内单播（审核处置、私信提示等）
func (s *LiveGatewayServer) SendToUser(ctx context.Context, in *rpc.SendToUserReq) (*rpc.SendToUserReply, error) {
	l := logic.NewSendToUserLogic(ctx, s.svcCtx)
	return l.SendToUser(in)
}

// 弹幕转发（弹幕事实仍归 danmaku，本服务只扇出）
func (s *LiveGatewayServer) ForwardDanmaku(ctx context.Context, in *rpc.ForwardDanmakuReq) (*rpc.ForwardDanmakuReply, error) {
	l := logic.NewForwardDanmakuLogic(ctx, s.svcCtx)
	return l.ForwardDanmaku(in)
}

// 系统事件转发（开播/断流/下播/审核处置）
func (s *LiveGatewayServer) ForwardSystemEvent(ctx context.Context, in *rpc.ForwardSystemEventReq) (*rpc.ForwardSystemEventReply, error) {
	l := logic.NewForwardSystemEventLogic(ctx, s.svcCtx)
	return l.ForwardSystemEvent(in)
}

// 强制下线（风控/审核/主播踢人），可同时撤销票据与写禁止重连窗口
func (s *LiveGatewayServer) KickConnection(ctx context.Context, in *rpc.KickConnectionReq) (*rpc.KickConnectionReply, error) {
	l := logic.NewKickConnectionLogic(ctx, s.svcCtx)
	return l.KickConnection(in)
}

// 分页查询广播审计流水（按房间）
func (s *LiveGatewayServer) ListBroadcastLogs(ctx context.Context, in *rpc.ListBroadcastLogsReq) (*rpc.ListBroadcastLogsReply, error) {
	l := logic.NewListBroadcastLogsLogic(ctx, s.svcCtx)
	return l.ListBroadcastLogs(in)
}

// 读取某作用域生效的配额（含继承链解析结果）
func (s *LiveGatewayServer) GetAccessQuota(ctx context.Context, in *rpc.AccessQuotaReq) (*rpc.AccessQuotaInfo, error) {
	l := logic.NewGetAccessQuotaLogic(ctx, s.svcCtx)
	return l.GetAccessQuota(in)
}

// 新建或更新配额配置（运营面，带版本与操作者审计）
func (s *LiveGatewayServer) UpsertAccessQuota(ctx context.Context, in *rpc.UpsertAccessQuotaReq) (*rpc.AccessQuotaInfo, error) {
	l := logic.NewUpsertAccessQuotaLogic(ctx, s.svcCtx)
	return l.UpsertAccessQuota(in)
}
