// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: comment.proto

package server

import (
	"context"

	"go-video/services/comment/internal/logic"
	"go-video/services/comment/internal/svc"
	"go-video/services/comment/rpc"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

// 发布评论或回复（state 通常为待审核）
func (s *CommentServer) PostComment(ctx context.Context, in *rpc.PostCommentReq) (*rpc.PostCommentReply, error) {
	l := logic.NewPostCommentLogic(ctx, s.svcCtx)
	return l.PostComment(in)
}

// 删除评论（本人或管理员）
func (s *CommentServer) DeleteComment(ctx context.Context, in *rpc.DeleteCommentReq) (*rpc.EmptyReply, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

// 分页查询目标下的根评论
func (s *CommentServer) ListComments(ctx context.Context, in *rpc.ListCommentsReq) (*rpc.ListCommentsReply, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}

// 分页查询某根评论下的楼中楼回复
func (s *CommentServer) ListReplies(ctx context.Context, in *rpc.ListRepliesReq) (*rpc.ListRepliesReply, error) {
	l := logic.NewListRepliesLogic(ctx, s.svcCtx)
	return l.ListReplies(in)
}

// 置顶/取消置顶评论
func (s *CommentServer) PinComment(ctx context.Context, in *rpc.PinCommentReq) (*rpc.EmptyReply, error) {
	l := logic.NewPinCommentLogic(ctx, s.svcCtx)
	return l.PinComment(in)
}

// 举报评论（写入 moderation-orchestrator 待审队列）
func (s *CommentServer) ReportComment(ctx context.Context, in *rpc.ReportCommentReq) (*rpc.EmptyReply, error) {
	l := logic.NewReportCommentLogic(ctx, s.svcCtx)
	return l.ReportComment(in)
}

// 查询目标下的评论计数快照
func (s *CommentServer) CommentStats(ctx context.Context, in *rpc.CommentStatsReq) (*rpc.CommentStatsReply, error) {
	l := logic.NewCommentStatsLogic(ctx, s.svcCtx)
	return l.CommentStats(in)
}
